- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   issue 1863 fix for inner 435
> issue 1863 fix

- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  BUG cluster NPE.  
Type:  
  BUG 
Influences：  
   cluster db HA NPE
> db HA cluster NPE

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix: fill fieldList
> fix: fill fieldList

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FieldListHandler.java
Reason:
  BUG Missing column
Type:
  BUG
Influences：
  fix: Catch all exceptions
> fix: Catch all exceptions

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863 
Type:  
  BUG
Influences：  
   Error message correct
> Error message correct

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863 
Type:  
  BUG
Influences：  
   fix NP of issue 1863
> Issue 1863

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863  
Type:  
  BUG
Influences：  
   fix NP in issue 1863
> fix NP in issue 1863

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/FreshBackendConnHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/FreshBackendConn.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
Reason:  
  Improve #2013 
Type:  
  Improve  
Influences：  
   connection pool refresh
> connection pool refresh

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UseHandler.java
Reason:  
  BUG inner 450
Type:  
  BUG
Influences：  
  fix: Use dble_information error when navict connect
> fix: Use dble_information error when navict connect

- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleSchema.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleShardingNode.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadUsage.java
Reason:  
  Improve #1987 
Type:  
  Improve  
Influences：  
  feat: Add management commands for dble_sharding_node, dble_schema, dble_thread_usage
> feat: Add management commands

- docker-images/quick-start/bootstrap.cnf
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowSysParam.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve #2015 .  
Type:  
  Improve  
Influences：  
   the default value for capClientFoundRows adjust to false
> the default value for capClientFoundRows adjust to false

- src/main/java/com/actiontech/dble/config/model/ParamInfo.java
- src/main/java/com/actiontech/dble/server/response/Heartbeat.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleVariables.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/singleton/WriteQueueFlowController.java
Reason:  
  Improve  #1987
Type:  
  Improve  
Influences：  
  
>  #1987 DBLE0REQ-379

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/factory/MySQLConnectionFactory.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBackend.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix backendconnection may be set processor for twice
> fix backendconnection may be set processor for twice

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  ATK-1244
Type:  
  Improve  
Influences：  
  add cache for visitor to let the visit faster
> add cache for visitor to let the visit faster

- src/main/java/com/actiontech/dble/backend/datasource/check/GlobalCheckJob.java
- src/main/java/com/actiontech/dble/manager/response/CheckGlobalConsistency.java
Reason:  
  BUG inner 458
Type:  
  BUG 
Influences：  
  1.no global table
  2. typo
>  inner 458

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG  
Type:  
  BUG  
Influences：  
   wrap the SQLExpr to fix bug
> wrap the SQLExpr to fix bug

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLUserLoader.java
- src/main/java/com/actiontech/dble/config/model/user/UserConfig.java
- src/main/java/com/actiontech/dble/config/model/user/UserPrivilegesConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBlacklist.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDdlLock.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntry.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntryDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntrySchema.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntryTablePrivilege.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleProcessor.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleReloadStatus.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleStatus.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleXaSession.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  Improve #1987  inner DBLE0REQ-380、382、394、397、400、401、403  
Type:  
  Improve
Influences：  
   add management tables
> add management tables

- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  Improve add debug log
Type:  
  Improve  
Influences：  
  perf: add debug log
> set AutoCommit add debug log

- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
Reason:  
  BUG #1880
Type:  
  BUG  
Influences：  
   fix manager execute sql record
> #1880 fix manager execute sql record

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG #2026 
Type:  
  BUG 
Influences：  
   minus will not treat as union
> #2026 minus

- src/main/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnit.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/sqlengine/mpp/ColumnRoute.java
- src/test/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnitTest.java
Reason:  
  BUG #1997
Type:  
  BUG
Influences：  
    #1997
> #1997 select/delete/update with '0x'

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
Type:  
  Improve  
Influences：  
  schema switch in complex query
> schema switch in complex query

- src/main/java/com/actiontech/dble/manager/dump/handler/StatementHandlerManager.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  correct schema handler
> correct schema handler

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AbstractCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/CommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/ImplicitCommitHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/CommitHandler.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG ATK-1275 
Type:  
  BUG 
Influences：  
   fix autocommit error
> ATK-1275 and spell error

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG #Inner 465. 
Type:  
  BUG
Influences：  
  slave instance keeps a heartbeat connection when rwSplitMode == RW_SPLIT_OFF
> slave instance keeps a heartbeat connection when rwSplitMode == RW_SPLIT_OFF

- src/main/assembly/bin/dble_datahosts_check.py
Reason:  
  BUG inner 466
Type:  
  BUG
Influences：  
   fix @@enable @@custom_mysql_ha don't take effect
> add default values to b variables in python scripts

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/TableMeta.java
- src/main/java/com/actiontech/dble/meta/table/AbstractSchemaMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/AbstractTableMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/DefaultNodeTablesMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/MetaHelper.java
Reason:  
  BUG
Type:  
  BUG  
Influences：  
   set schemaName for table meta when init tableMeta to avoid NPException
> set schemaName for table meta when init tableMeta

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterTableParser.java
Reason:  
  Improve #1924 
Type:  
  Improve  
Influences：  
  fix: Support alter table comment
> fix: Support alter table comment

- src/main/java/com/actiontech/dble/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/manager/handler/SplitDumpHandler.java
Reason:  
  BUG #inner 469. 
Type:  
  BUG
Influences：  
  improve exception handler in split dump file
> improve exception handler in split dump file

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix connection stolen
> fix connection stolen

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix issue for sql_mode reset
> fix issue for sql_mode reset

- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  BUG inner 471 
Type:  
  BUG  
Influences：  
   fix: in the log, only 1024 bytes are shown in the sql
> in the log, only 1024 bytes are shown in the sql.

- src/main/java/com/actiontech/dble/net/service/FrontEndService.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/services/manager/response/KillConnection.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   Resume the realization of KillConnection
> Resume the realization of KillConnection

- src/main/java/com/actiontech/dble/plan/common/item/Item.java
Reason:  
  BUG #1994 
Type:  
  BUG 
Influences：  
   fix: solve the problem of quotation marks
> solve the problem of quotation marks

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 473
Type:  
  BUG
Influences：  
   fix group by related questions
> fix group by related questions

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLDbLoader.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeat.java
Reason:  
  Improve #1987 
Type:  
  Improve  
Influences：  
  feat: Add management commands dble_db_group/dble_db_instance
> feat: Add management commands dble_db_group/dble_db_instance

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix message to fix autotest
> fix message to fix autotest

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLShardingLoader.java
- src/main/java/com/actiontech/dble/route/function/AutoPartitionByLong.java
- src/main/java/com/actiontech/dble/route/function/PartitionByFileMap.java
- src/main/java/com/actiontech/dble/route/function/PartitionByPattern.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleAlgorithm.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleTable.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  Improve #1987  inner 392
Type:  
  Improve  
Influences：  
  feat: Add management commands dble_algorithm
> feat: Add management commands dble_algorithm

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntryTablePrivilege.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleProcessor.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleStatus.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleXaSession.java
Reason:  
  BUG inner 476、484、505
Type:  
  BUG 
Influences：  
   fix inner 476、484 and optimize dble_entry_table_privilege table（505）
> fix inner 476、484 and optimize dble_entry_table_privilege table

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/services/manager/response/FreshBackendConn.java
Reason:  
  BUG inner 351.  
Type:  
  BUG  
Influences：  
   fix inner 351
> freshing connection requires add lock

- src/main/java/com/actiontech/dble/net/AbstractConnection.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix fingbug: lastWriteTime decrement
> fix fingbug: lastWriteTime decrement

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix bugs find in auto test
> fix bugs find in auto test

- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix lost of prepareStatement impl
> fix lost of prepareStatement impl

- src/main/java/com/actiontech/dble/singleton/TsQueriesCounter.java
Reason:  
  BUG #DBLE0REQ-522  
Type:  
  BUG  
Influences：  
   fix show @@Questions show result
> DBLE0REQ-522

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/savepoint/SavePointHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix error code in multiNodeQuery
> fix error code in multiNodeQuery

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #2024 
Type:  
  BUG  
Influences：  
   fix issus 2024
> fix issus 2024

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowTablesHandler.java
Reason:  
    Improve inner-511
Type:  
   Improve  
Influences：  
   show tables will  not contain tables which in the physical schema but  not in meta
> inner-511 show tables  Improve

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleChildTable.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleTable.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleTableShardingNode.java
Reason:  
  BUG inner 494/499/500
Type:  
  BUG
Influences：  
  fix: inner 494/499/500
> fix: inner 494/499/500

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/DistinctHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/HavingHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/WhereHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/manager/ManagerBaseSelectHandler.java
Reason:  
  BUG inner-526
Type:  
  BUG 
Influences：  
   join table use handler's self left property
> inner-526 join table

- src/main/resources/user_template.xml
- src/test/resources/user.xml
Reason:  
  BUG
Type:  
  BUG
Influences：  
   update configured templates
> update configured templates

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BtraceConnectionPool.java
- src/main/java/com/actiontech/dble/services/manager/response/FreshBackendConn.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionPoolProperty.java
Reason:  
  BUG inner 518/519/521
Type:  
  BUG
Influences：  
   fix fresh conn's bugs
> fix fresh conn's bugs

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix load balance in sharding mode
> fix load balance in sharding mode

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix load balance
> fix load balance

- src/main/java/com/actiontech/dble/config/model/db/PoolConfig.java
Reason:  
   Improve
Type:  
  Improve  
Influences：  
  change value of connectionTimeout from 300s to 30s
> change default value of connectionTimeout from 300s to 30s

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
   fix log of autotest
> db_instance_log of autotest

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/helper/TestSchemasTask.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix schemaExists is false after reload config
> fix schemaExists is false after reload config

- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix incorrect param
> fix incorrect param

- src/main/java/com/actiontech/dble/services/manager/response/ManagerSelectHandler.java
Reason:  
  BUG inner 533
Type:  
  BUG
Influences：  
  fix:  remove forced conversion
> fix:  remove forced conversion

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileConfig.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitDumpHandler.java
Reason:  
  Improve inner 513 
Type:  
  Improve  
Influences：  
   dump file with keyword 'ignore'
> dump file with keyword 'ignore'

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowVariablesHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerSptPrepare.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
- src/main/java/com/actiontech/dble/server/response/SptExecute.java
- src/main/java/com/actiontech/dble/services/MySQLBasedService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #1806  
Type:  
  BUG  
Influences：  
  make variables context into statement level
> Issue 1806

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAEndStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
Reason:  
  BUG #1880   
Type:  
  BUG  
Influences：  
   fix for xa rollback packetId
> fix for xa rollback packetId

- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix: show @@binlog.status only need associated dbgroup
> fix: autotest

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG #1880
Type:  
  BUG  
Influences：  
   remove useless log
> remove useless log DBLE0REQ-474

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG #1806  
Type:  
  BUG  
Influences：  
   fix set bug when try to set a value for multi-times
> fix bug for #1806

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAStage.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
Reason:  
  BUG #1880  
Type:  
  BUG  
Influences：  
   fix for xa when connection graceful close
> fix for xa when connection graceful close

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/subquery/AllAnySubQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/subquery/InSubQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/subquery/SingleRowSubQueryHandler.java
- src/main/java/com/actiontech/dble/plan/node/ManagerTableNode.java
- src/main/java/com/actiontech/dble/services/manager/information/builder/ManagerBaseHandlerBuilder.java
Reason:  
   Improve  inner-485
Type:  
   Improve  
Influences：  
   inner-485
> issue inner-485

- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/DbGroups.java
- src/main/java/com/actiontech/dble/config/model/db/PoolConfig.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner 539/540/541
Type:  
  BUG
Influences：  
  fix: inner 539/540/541
> fix: inner 539/540/541

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
Reason:  
  BUG #2063 
Type:  
  BUG 
Influences：  
   issue 2063
> issue 2063

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/PreparedResponseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MysqlBackendLogicHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/MysqlPrepareLogicHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  Improve #2075 .  
Type:  
     Improve  
Influences：  
  support prepared statement in rw
> support prepared statement in rw

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/sqlengine/MultiTablesMetaJob.java
Reason:  
  BUG #1880  
Type:  
  BUG  
Influences：  
   add more detail for response service toString to fit for the autotest
> add more detail for response service toString

- src/main/java/com/actiontech/dble/services/manager/handler/ShowProcesslistHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/BackendVariables.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/SessionVariables.java
Reason:  
  Improve #1987.  
Type:  
  Improve  
Influences：  
  add manager table  of processlist
> add manager table  of processlist

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/PasswordAuthPlugin.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/plugin/CachingSHA2Pwd.java
Reason:  
  BUG #1880  
Type:  
  BUG
Influences：  
   support multi-type of authenticate for backend
> support multi-type of authenticate for backend

- src/main/java/com/actiontech/dble/route/parser/ManagerParseHeartbeat.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeatDetail.java
- src/test/java/com/actiontech/dble/manager/ShowHeartBeatDetailTest.java
Reason:  
  BUG #2134 
Type:  
  BUG
Influences：  
   fix 'show @@heartbeat.detail where name = 'value''
> issue 2134

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnections.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPool.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner 481,491,492,493,527
Type:  
Influences：  
  fix manager table of session_connections and backend_connections
> fix manager table of session_connections and backend_connections

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG #2073  
Type:  
  BUG
Influences：  
   fix issue-2073
> issue 2073

- src/main/java/com/actiontech/dble/config/loader/xml/XMLUserLoader.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleXaSession.java
- src/main/java/com/actiontech/dble/services/manager/response/FreshBackendConn.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
Reason:  
  BUG inner 546、547、545、518
Type:  
  BUG
Influences：  
   adjustment prompt、fix bug
> adjustment prompt

- src/main/java/com/actiontech/dble/plan/common/item/ItemInt.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG #2143 
Type:  
  BUG
Influences：  
  fix: issue #2143 set charsetIndex for ItemInt
> fix: issue #2143

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogEntry.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  Improve slow log
Type:  
  Improve  
Influences：  
   add type for dble slow log
> add type for dble slow log

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
- src/main/java/com/actiontech/dble/server/handler/ViewHandler.java
Reason:  
  BUG #2135 
Type:  
  BUG 
Influences：  
   fix issue 2135
> issue 2135

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleRwSplitEntry.java
Reason:  
  BUG inner 555
Type:  
  BUG
Influences：  
  fix: Verify the correctness of Boolean values
> fix: Verify the correctness of Boolean values

- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/SelectInformationSchemaColumnsHandler.java
Reason:  
  BUG #2147 
Type:  
  BUG
Influences：  
   fix select information_schema.columns' problems with alias, table names
> issue 2147

- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/config/Isolations.java
- src/main/java/com/actiontech/dble/server/handler/SetCallBack.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
- src/main/java/com/actiontech/dble/server/variables/MysqlVariable.java
- src/main/java/com/actiontech/dble/server/variables/VariableType.java
- src/main/java/com/actiontech/dble/services/MySQLVariablesService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/BackendVariables.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/SessionVariables.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
  fix set variables and perfect manager cmd of variables
> fix set variables and perfect manager cmd of variables

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/resources/user_template.xml
Reason:  
  BUG inner 548
Type:  
  BUG
Influences：  
  different rwSplit user can use one rwGroup
> different rwSplit user can use one rwGroup

- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix collation name
> fix collation name

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileReader.java
Reason:  
  BUG #2166 
Type:  
  BUG
Influences：  
  fix: separator to increase line break mark
> fix: separator to increase line break mark

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG #2162
Type:  
  BUG
Influences：  
  fix: distinguish outer and inner join
> fix: distinguish outer and inner join

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:
  BUG #2162
Type:
  BUG
Influences：
  fix: distinguish outer and inner join
> fix: distinguish outer and inner join（cherry pick from master #2164）

- src/main/java/com/actiontech/dble/manager/dump/DumpFileReader.java
Reason:
  BUG #2166
Type:
  BUG
Influences：
  fix: separator to increase line break mark
> fix: separator to increase line break mark (cherry pick from master #2167)

- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  check syn info in backend connection
> check syn info in backend connection

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  fix: add log
> fix: add log

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner 577  
Type:  
  BUG 
Influences：  
  fix: check primary
> fix: check primary

- src/main/java/com/actiontech/dble/cluster/response/DataHostHaResponse.java
- src/main/java/com/actiontech/dble/cluster/xmltoKv/XmltoCluster.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/DataHostStatusTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/ZkMultiLoader.java
- src/main/java/com/actiontech/dble/manager/response/DataHostDisable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostSwitch.java
Reason:  
  BUG DMP-5667
Type:  
  BUG
Influences：  
   fix  DMP-5667
> no cluster ha with reload

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner 578
Type:  
  BUG
Influences：  
  fix: Session statistics are placed before the task queue
> fix: Session statistics are placed before the task queue

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
Reason:
  Improve inner 580
Type:
  Improve
Influences：
  fix: Management command lock mechanism changes
> fix: Management command lock mechanism changes

- src/main/java/com/actiontech/dble/services/manager/dump/handler/DefaultHandler.java
Reason:  
  BUG inner 560
Type:  
  BUG
Influences：  
  fix: set statement writes to all nodes
> fix: set statement writes to all nodes

- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitDumpHandler.java
Reason:  
  BUG inner 575,563
Type:  
  BUG
Influences：  
   fix parameter in any order、return error tips
> fix:inner 575,563

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG inner 590
Type:  
  BUG
Influences：  
  fix: supplement where filter
#2073
> fix: supplement where filter

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG inner 590
Type:  
  BUG
Influences：  
  fix: supplement where filter
#2073
> fix: supplement where filter(cherry pick from 2.20.04.99 #2192)

- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
Reason:  
  BUG #inner 549. 
Type:  
  BUG
Influences：  
  add default value for processlist
> add default value for processlist

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  Temp atk 1400
> charset for atk-1400

- src/main/java/com/actiontech/dble/plan/NamedField.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/node/TableNode.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  charset for atk-1406
> charset for atk-1406

- docker-images/Dockerfile
- docker-images/Dockerfile-Mgr
- docker-images/docker-compose-mgr.yml
- docker-images/docker-compose.yml
- docker-images/quick-start/db.xml
- docker-images/quick-start/db_mgr.xml
- docker-images/quick-start/docker_init_start.sh
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   add simple quick start dble
> quick start dble & mgr

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/plan/node/TableNode.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  charset for atk-1409, missing for atk-1408
> charset for atk-1409, missing for atk-1408

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
 charset for atk-1408
> alias for atk-1408

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG #inner 602.
Type:  
  BUG
Influences：  
  fix load balance in rwSplit
> fix load balance in rwSplit

- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG inner 253
Type:  
  BUG
Influences：  
   fix NPE when reload
> fix NPE when reload

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG inner 630
Type:  
  BUG
Influences：  
  fix: add judgment
> fix: add judgment

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:
  BUG inner 630
Type:
  BUG
Influences：
  fix: add judgment
#2207
> fix: add judgment (cherry pick from master #2207)

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  BUG inner 642
Type:  
  BUG
Influences：  
  fix: inner 642
auth switch request should use client configuration
> fix: inner 642

- src/main/java/com/actiontech/dble/DbleStartup.java
- src/main/java/com/actiontech/dble/util/CheckConfigurationUtil.java
Reason:  
  BUG #
Type:  
  BUG
Influences：  
   fix home only singlequotes hava error path
> Ylz master

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:
  BUG inner 642
Type:
  BUG
Influences：
  fix: inner 642
auth switch request should use client configuration
#2211
> fix: inner 642 (cherry pick from master #2211) 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/plan/NamedField.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/node/TableNode.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG
Type:  
  BUG 
Influences：  
    fix chinese in column and row
> fix chinese in column and row

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  BUG inner 645 
Type:  
  BUG
Influences：  
  fix: inner 645 and add log
auth switch request should use mysql_native_password
> fix: inner 645 and add log

- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/test/java/com/actiontech/dble/parser/ServerParserTest.java
Reason:  
  BUG #inner 608
Type:  
  BUG
Influences：  
  support rollback work
> support rollback work

- src/main/java/com/actiontech/dble/plan/common/field/FieldUtil.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  BUG #inner 609,611 
Type:  
  BUG
Influences：  
  when set value is binary, turn the value to hex string stored
> when set value is binary, turn the value to hex string stored

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:
  BUG inner 645
Type:
  BUG
Influences：
  fix: inner 645 and add log
auth switch request should use mysql_native_password
#2215
> fix: inner 645 and add log (cherry pick from master #2215)

- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
Reason:  
  BUG #inner 635.
Type:  
  BUG
Influences：  
  support expression in set statement
> support expression in set statement

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLUserLoader.java
Reason:  
  BUG #inner 639.
Type:  
  BUG 
Influences：  
  don't load sharding.xml when only rwSplit user is configured
> don't load sharding.xml when only rwSplit user is configured

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG inner 595
Type:  
  BUG
Influences：  
  fix: inner 595
> fix: inner 595

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG inner 648
Type:  
  BUG
Influences：  
  fix: inner 648
when auth request is \004 need send switch auth response
> fix: inner 648

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
Reason:  
  BUG #inner-591
Type:  
  BUG
Influences：  
  avoid the following case: 1. login 2. set autocommit=0 3. select xxx
> avoid the following case: 1. login 2. set autocommit=0 3. select xxx

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:
  BUG inner 595
Type:
  BUG
Influences：
  fix: inner 595
#2218
> fix: inner 595 (cherry pick from master #2218)

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:
  BUG inner 648
Type:
  BUG
Influences：
  fix: inner 648
when auth request is \004 need send switch auth response
#2226
> fix: inner 648(cherry pick from master #2226) 

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG #inner 641. 
Type:  
  BUG
Influences：  
  fix correctness of heartbeat retry count
> fix correctness of heartbeat retry count

- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix ci - data type is binary, need check flag to judge whether the data is number or string
> data type is binary, need check flag to judge whether the data is number or string

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
Reason:  
  BUG #inner654.
Type:  
  BUG
Influences：  
  fix bug that idleTimeout does not take effect
> fix bug that idleTimeout does not take effect

- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
Reason:  
  BUG inner 650
Type:  
  BUG
Influences：  
  fix: inner 650
Add packet number when unpacking
> fix: inner 650

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
Reason:  
  BUG inner 655
Type:  
  BUG
Influences：  
  fix: inner 655
> fix: inner 655

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLUserLoader.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/plan/NamedField.java
- src/main/java/com/actiontech/dble/plan/common/field/FieldUtil.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/node/TableNode.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
- src/test/java/com/actiontech/dble/parser/ServerParserTest.java
Reason:  
  Improve 
Type:  
  improve
Influences：  
  fix bug for rwsplit
> fix bug for rwsplit

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/MergeBuilder.java
- src/main/java/com/actiontech/dble/route/impl/DefaultRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG #2152  
Type:  
  BUG
Influences：  
   fix :not specify the table name，causes to all nodes
> issue 2152

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 652
Type:  
  BUG
Influences：  
  fix: inner 652
add the judgment of connection
> fix: inner 652

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/MysqlVisitor.java
Reason:  
  BUG  explain result error
Type:  
Influences：  
   fix issues 2042
> fix: issues 2042

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
Reason:
  BUG inner 655
Type:
  BUG
Influences：
  fix: inner 655
#2232
> fix: inner 655(cherry pick from master #2232) 

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner 627
Type:  
  BUG
Influences：  
   fix : when query SQL exist unknown schema, npe error
> when query SQL exist unknown schema, npe error

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG #inner598. 
Type:  
  BUG
Influences：  
   show statement is pushed down to master in rw
> show statement is pushed down to master in rw

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  missing for refactor
> missing for net refactor

- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG inner 253
Type:  
  BUG
Influences：  
   fix
> cherry pick from inner-253

- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
Reason:  
  BUG inner 659
Type:  
  BUG
Influences：  
  fix: inner 659
Need to increase the packet number before sending data
> fix: inner 659（Need to increase the packet number before sending data）

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:
  BUG inner 652
Type:
  BUG
Influences：
  fix: inner 652
add the judgment of connection
#2237
> fix: inner 652(cherry pick from master #2237)

- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
Reason:
  BUG inner 650、659
Type:
  BUG
Influences：
  fix: inner 650、659
Add packet number when unpacking #2231
Need to increase the packet number before sending data #2243
> fix: inner 650/659(cherry pick from master #2231/#2243) 

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDbInstance.java
Reason:  
  BUG inner 662
Type:  
  BUG
Influences：  
   1.fix  inner 662
2.execute "show @@dbinstance where shardingNode = 'dn1'"  cause npe
> fix: ci bug

- src/main/java/com/actiontech/dble/services/manager/response/ShowBackend.java
Reason:
  BUG inner 637
Type:
  BUG
Influences：
  fix: inner 637
add the judgment of connection
#2239
> fix: inner 637(cherry pick from master #2239) 

- src/main/java/com/actiontech/dble/services/manager/response/ShowBackend.java
Reason:  
  BUG inner 637
Type:  
  BUG
Influences：  
  fix: inner 637
add the judgment of connection
> fix: inner 637

- src/main/java/com/actiontech/dble/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/handler/ManagerAuthenticator.java
Reason:  
  BUG  inner DMP-5863
Type:  
  BUG
Influences：  
   fix showconnection NPE
> fix connection  NPE.(show @@connection)

- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/factory/MySQLConnectionFactory.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
  BUG inner 670
Type:  
  BUG
Influences：  
  fix: inner 670
ArrayList thread unsafe
> fix: inner 670

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
Reason:  
Type:  
Influences：  
   fix xx
> fix MySQLFrontAuthService cast to FrontEndService fail inner DMP-5863

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileReader.java
Reason:  
  BUG #1851 .
Type:  
  BUG 
Influences：  
    fix bug that the split file contains view definition
> fix bug that the split file contains view definition

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG inner 670
Type:  
  BUG
Influences：  
  fix: inner 670
Hang caused by the specified non-existent schema in the connection
#2262
> fix: inner 670(cherry pick from master #2262) 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/MysqlVisitor.java
Reason:  
  BUG error sql result 
Type:  
  BUG
Influences：  
   fix issues 2042      put brackets  in the right place
> fix: issues 2042 (cherry-pick master#2240)

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLCurrentResponseService.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix hang in performance mode
> fix bug that dble can't start in performance mode

- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  BUG inner 676
Type:  
  BUG
Influences：  
  fix: inner 676
add log
> fix: inner 676

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG #2225 
Type:  
  BUG 
Influences：  
   fix
> issue 2225

- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   inner DBLE0REQ-657
> fix inner DBLE0REQ-657

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG inner 674 
Type:  
  BUG
Influences：  
  fix: inner 674 
distinguish shardingUseless and rwSplitUseless
> fix: inner 674 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #inner680
Type:  
  BUG
Influences：  
  client lost connection when all sharding node can't connect
> client lost connection when all sharding node can't connect

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLCurrentResponseService.java
Reason:  
  BUG.  
Type:  
  BUG
Influences：  
  fix NullPointException in use performance mode
> fix NullPointException in use performance mode

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropTableParser.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
- src/main/java/com/actiontech/dble/server/response/SptDrop.java
- src/main/java/com/actiontech/dble/server/response/SptPrepare.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  BUG #inner 649, inner651.
Type:  
  BUG
Influences：  
  fix bug about kill query
> fix bug about kill query

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AutoCommitHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner 678
Type:  
  BUG
Influences：  
  fix: inner 678
* npe
* solve packet disorder
* the value of the disabled field of the DbleDbInstance table is incorrect
> fix: inner 678

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/net/executor/BackendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/Service.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLCurrentResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix bug in performance mode
> fix bug in performance mode

- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   support begin work and commit work
> fix inner DBLE0REQ-607

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner685/627、issue2225
Type:  
  BUG
Influences：  
   fix
> cherry pick from inner685/627、issue2225

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AutoCommitHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:
  BUG inner 678
Type:
  BUG
Influences：
  fix: inner 678
npe
solve packet disorder
the value of the disabled field of the DbleDbInstance table is incorrect
#2277
> fix: inner 678(cherry pick from master #2277)

- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG inner 627
Type:  
  BUG
Influences：  
   fix
> perfect the restoration of inner-627

- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG inner 627
Type:  
  BUG
Influences：  
   fix
> perfect the restoration of inner-627(master branch)

- src/main/java/com/actiontech/dble/services/manager/response/ShowBackend.java
Reason:  
  BUG ci 
Type:  
  BUG
Influences：  
  fix: service is set to null and connection close is not atomic
service is set to null earlier than connection close
> fix: service is set to null earlier than connection close

- src/main/java/com/actiontech/dble/services/manager/response/ShowBackend.java
Reason:
  BUG ci
Type:
  BUG
Influences：
  fix: service is set to null and connection close is not atomic
service is set to null earlier than connection close
#2290
> fix: service is set to null earlier than connection close(cherry pick from master #2290)

- src/main/java/com/actiontech/dble/services/manager/response/ShowDbInstance.java
Reason:  
  BUG #inner 703.
Type:  
  BUG
Influences：  
    correct size to maxCon in show @@dbInstance
> correct size to maxCon in show @@dbInstance

- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix when query dual table and schema is null, NPE Exception
> fix: Miss bug

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:
  BUG inner 674
Type:
  BUG
Influences：
  fix: inner 674
distinguish shardingUseless and rwSplitUseless
> fix: inner 674(cherry pick from master #2271)

- src/main/java/com/actiontech/dble/config/model/user/ManagerUserConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/Describe.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
Reason:  
  BUG inner-692
Type:  
  BUG
Influences：  
   fix
> cherry pick from inner-692

- src/main/java/com/actiontech/dble/config/loader/xml/XMLDbLoader.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
  add  check group url duplicated rules
> add  check group url duplicated rules inner DBLE0REQ-640

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/net/mysql/CharsetNames.java
Reason:
  BUG inner 710
Type:
  BUG
Influences：
  fix: when character_set_results is null,the default value will be used binary
> fix: when character_set_results is null,the default value will be used binary

- src/main/java/com/actiontech/dble/services/manager/information/tables/BackendVariables.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/SessionVariables.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
   Improve.  
Type:  
      Improve  
Influences：  
   add primary key for manager table
> add primary key for manager table

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:  
   Improve #inner 706.  
Type:  
   Improve  
Influences：  
   modify tips
> modify tips

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-704
Type:  
  BUG
Influences：  
   Improve   'select...for update' and 'select...lock in share mode' sql, to master node
> 'select...for update' and 'select...lock in share mode' sql, to master node

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-704
Type:  
  BUG
Influences：  
'select...for update' and 'select...lock in share mode' sql, to master node
> 'select...for update' and 'select...lock in share mode' sql, to master node(cherry pick from inner-704)

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/net/mysql/CharsetNames.java
Reason:
  BUG inner 710
Type:
  BUG
Influences：
  fix: when character_set_results is null,the default value will be used binary
#2307
> fix: when character_set_results is null,the default value will be used binary(cherry pick from master #2307)

- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   delete semicolons if last position of sql have it
>  inner DBLE0REQ-657 (cherry pick from 3.20.10 #2270)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAStage.java
Reason:  
  BUG inner 652
Type:  
  BUG
Influences：  
  fix: release and faked timing adjustment
inner 652
> fix: release and faked timing adjustment

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG #inner 709. 
Type:  
  BUG 
Influences：  
  avoid the case that the packet sequence is field,eof,err
> avoid the case that the packet sequence is field,eof,err

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG #inner 709. 
Type:  
  BUG
Influences：  
  avoid the case that the packet sequence is field,eof,err when executing select
> avoid the case that the packet sequence is field,eof,err when executing select

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:  
   Improve.  
Type:  
  Improve  
Influences：  
  inner 706
> modify tips (#2300)

- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
fix inner DBLE0REQ-607 support begin work to RWsplit (cherry pick from master#2269)
> fix inner DBLE0REQ-607 support begin work to RWsplit (cherry pick from master#2269)

- src/main/java/com/actiontech/dble/cluster/general/kVtoXml/ClusterToXml.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterClearKeyListener.java
- src/main/java/com/actiontech/dble/cluster/general/response/ConfigStatusResponse.java
Reason:  
  BUG inner DMP-6128
Type:  
  BUG
Influences：  
   fix: slave dble reload failure
> fix: slave dble reload failure

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
  fix inner DBLE0REQ-698 support help keyword load balance mode
> fix inner DBLE0REQ-698 support help keyword load balance mode

- src/main/java/com/actiontech/dble/util/IPAddressUtil.java
- src/test/java/com/actiontech/dble/util/IPAddressUtilTest.java
Reason:  
  BUG inner 712
Type:  
  BUG
Influences：  
  fix: whiteIp wildcard modification
inner 712
> fix: whiteIp wildcard modification

- src/main/java/com/actiontech/dble/util/IPAddressUtil.java
- src/test/java/com/actiontech/dble/util/IPAddressUtilTest.java
Reason:  
  BUG inner 714
Type:  
  BUG
Influences：  
  fix: whiteIp distinguish fe80.%,wildcard 
inner 714
> fix: whiteIp distinguish fe80.%,wildcard 

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG #inner 713.
Type:  
  BUG
Influences：  
  fix load data hang
> fix load data hang

- src/main/java/com/actiontech/dble/util/IPAddressUtil.java
- src/test/java/com/actiontech/dble/util/IPAddressUtilTest.java
Reason:  
  BUG inner 712/714
Type:  
  BUG
Influences：  
  fix: whiteIp wildcard modification(cherry pick from master #2321/#2326)
> fix: whiteIp wildcard modification(cherry pick from master #2321/#2326)

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  BUG inner 676
Type:  
  BUG
Influences：  
  fix: set the key of traceResult to connection id+node name+sql
> fix: set the key of traceResult to connection id+node name+sql

- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  change primary key from front_id,sharding_node to front_id,mysql_id in processlist
> change primary key from front_id,sharding_node to front_id,mysql_id in processlist

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAStage.java
Reason:
  BUG inner 652
Type:
  BUG
Influences：
  fix: release and faked timing adjustment(cherry pick from master #2317)
> fix: release and faked timing adjustment(cherry pick from master #2317)

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix inner DBLE0REQ-698 support help keyword load balance mode
> fix inner DBLE0REQ-698 support help keyword load balance mode(cherry-pick from 3.20.10.99 #2316)

- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
    Improve   
Type:  
   Improve  
Influences：  
   no sharding/split user dryrun level
> Inner 721 no sharding/split user

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  BUG inner 676
Type:  
  BUG
Influences：  
  fix: set the key of traceResult to connection id+node name+sql(cherry pick from master #2330)
> fix: set the key of traceResult to connection id+node name+sql(cherry pick from master #2330)

- dble_checkstyle_suppression.xml
- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  optimize er left join global
> optimize er left join global

- src/main/java/com/actiontech/dble/cluster/general/bean/InstanceOnline.java
- src/main/java/com/actiontech/dble/util/NetUtil.java
Reason:  
  BUG inner DMP-6236
Type:  
  BUG
Influences：  
   no fix, add log observation
> add log observation

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 720
Type:  
  BUG
Influences：  
  fix: The priority table of sqlMaxLimit is greater than the schema
> fix: the priority table of sqlMaxLimit is greater than the schema

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  BUG 717
Type:  
Influences：  
   fix xx
> inner-717 :fixed some StringIndexOutOfBoundsException

- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
Reason:  
  BUG  726
Type:  
Influences：  
   fix xx
> inner-726 kill return OK.But doesn't get any effect.

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterOffLineListener.java
- src/main/java/com/actiontech/dble/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/OnlineStatus.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG DMP-6183
Type:  
  BUG
Influences：  
   fix: distributed locks not being released
> distributed locks not being released

- src/main/java/com/actiontech/dble/cluster/general/kVtoXml/ClusterToXml.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterClearKeyListener.java
- src/main/java/com/actiontech/dble/cluster/general/response/ConfigStatusResponse.java
Reason:  
  BUG DMP-6128
Type:  
  BUG 
Influences：  
   fix: slave dble reload failure
> slave dble reload failure(cherry pick from DMP-6128)

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:
  BUG inner 720
Type:
  BUG
Influences：
  fix: the priority table of sqlMaxLimit is greater than the schema(cherry pick from master #2333)
> fix: the priority table of sqlMaxLimit is greater than the schema(cherry pick from master #2333) 

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:
  BUG inner 720
Type:
  BUG
Influences：
  fix: the priority table of sqlMaxLimit is greater than the schema(cherry pick from master #2333)
> fix: the priority table of sqlMaxLimit is greater than the schema(cherry pick from master #2333)

- dble_checkstyle_suppression.xml
- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java
Reason:  
   Improve #atk-1489.  
Type:  
  Improve  
Influences：  
  improve er left join global
> atk-1489:improve er left join global

- src/main/java/com/actiontech/dble/services/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   release pause's distributed lock logic optimization
> release pause's distributed lock logic optimization

- src/main/java/com/actiontech/dble/services/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   release pause's distributed lock logic optimization
> release pause's distributed lock logic optimization(to master)

- src/main/java/com/actiontech/dble/config/loader/xml/XMLShardingLoader.java
Reason:  
  BUG 722
Type:  
Influences：  
   fix xx
> inner-722: detect shardingNode repeat

- docker-images/quick-start/user.xml
Reason:  
  Docker quick start  guide report some error in 3.20.10 version
Type:  
  BUG
Influences：  
   fix xx
> fixed:Docker quick start guide report  some error in 3.20.10 version

- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner-772
Type:  
  Improve  
Influences：  
   fix: 't_' environment variable was referenced... in wrapper.log
> fix: 't_' environment variable was referenced... in wrapper.log

- src/main/java/com/actiontech/dble/config/loader/xml/XMLDbLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLShardingLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLUserLoader.java
Reason:  
  BUG inner-773
Type:  
  BUG
Influences：  
   fix xx
> inner-773：remove "/" and wrap in error report when reload config.

- src/main/java/com/actiontech/dble/config/loader/xml/XMLShardingLoader.java
Reason:  
   Improve inner-722
Type:  
  Improve  
Influences：  
   fix xx
> inner-722-supplement: modify description

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner 797
Type:  
  BUG
Influences：  
  fix: when the password is updated, the problem of encoding and decoding
> fix: when the password is updated, the problem of encoding and decoding

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG inner 732
Type:  
  BUG
Influences：  
   fix: not in line with expectation of routing to single node sql
>  fix: not in line with expectation of routing to single node sql

- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
Reason:  
  BUG  inner-826
Type:  
  BUG
Influences：  
   server parse about drop.
> inner-826 : fixed drop table doesn't take any effect

- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQLStatus.java
Reason:  
  BUG inner-769
Type:  
  BUG
Influences：  
   connection.sql.status
> inner-769: fixed 'show @@connection.sql.status' in python case error.

- src/main/java/com/actiontech/dble/config/ErrorCode.java
- src/main/java/com/actiontech/dble/plan/common/item/function/operator/cmpfunc/ItemFuncStrcmp.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner-744
Type:  
  BUG
Influences：  
   
   1. STRCMP fun
> inner-744: modify  error message of STRCMP()

- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncQuote.java
Reason:  
  BUG inner-756
Type:  
  BUG
Influences：  
   quote func
> inner-756: adjust quote output

- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncHex.java
Reason:  
  BUG inner-747
Type:  
  BUG
Influences：  
   ItemFunc
> inner-747: fixed: dble's HEX() should be the same as  mysql's

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
fix : the database does not exist in mysql but can be logged in rwsplituser inner 668 and 667 
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix : the database does not exist in mysql but can be logged in rwsplituser inner 668 and 667
> fix : the database does not exist in mysql but can be logged in rwsplituser inner 668 and 667 

- src/main/java/com/actiontech/dble/singleton/CustomMySQLHa.java
- src/main/java/com/actiontech/dble/util/IOUtil.java
Reason:  
  BUG inner-653
Type:  
  BUG
Influences：  
  enable/disable/show CustomMySQLHa logic
> inner-653: fixed CustomMySQLHa python script doesn't log error

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeAndOrderHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OrderByHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/groupby/DirectGroupByHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/NotInHandler.java
- src/main/java/com/actiontech/dble/plan/common/item/function/ItemCreate.java
- src/main/java/com/actiontech/dble/plan/common/item/function/ItemListDelegate.java
- src/main/java/com/actiontech/dble/plan/common/item/function/operator/cmpfunc/ItemFuncStrcmp.java
Reason:  
  BUG inner-744
Type:  
  BUG
Influences：  
   all native fun
> inner-744-supplement: check argument lack for all native fun

- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
Reason:  
  BUG inner-730
Type:  
  BUG
Influences：  
   1.show tables
   2.write slowQuery log
> inner-730: fixed: 'use schema'  cause slowQuery  thread terminated.

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
  BUG inner-711
Type:  
  BUG
Influences：  
   output of rwSplit
> inner-711-bugfix: fixed: dble send repeat packet when multiStatements enabled.

- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
This pr is  a bugfix of https://github.com/actiontech/dble/pull/2379
Reason:  
  BUG inner-557-bugfix
Type:  
  BUG
Influences：  
   1. temp table
> inner-557-bugfix: variant of 'drop table' and 'create table'  cause bug.

- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
Reason:  
  BUG.
Type:  
  BUG
Influences：  
  remove executeSql in manager
> remove executeSql in manager

- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
Reason:  
  Improve  inner-814
Type:  
  Improve  
Influences：  
   fix: when connecting, the client_found_rows value of the client and dble are inconsistent, the log will prompt
> fix: when connecting, the client_found_rows value of the client and dble are inconsistent, the log will prompt

- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve inner-764
Type:  
  Improve  
Influences：  
   dble_variables
> inner-764-supplement: add variable to dble_variables table

- src/main/java/com/actiontech/dble/services/manager/response/ShowDataDistribution.java
- src/main/java/com/actiontech/dble/sqlengine/MultiRowSQLQueryResultHandler.java
- src/main/java/com/actiontech/dble/sqlengine/OneRawSQLQueryResultHandler.java
- src/main/java/com/actiontech/dble/sqlengine/SQLQueryResult.java
Reason:  
  inner-728
Type:  
  Improve  
Influences：  
  SQLQueryResultHandler
> inner-728: add hints for nosharding table in 'show @@data_distribution' scene.

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleRwSplitEntry.java
- src/main/java/com/actiontech/dble/util/IntegerUtil.java
Reason:  
  BUG inner-841
Type:  
  BUG
Influences：  
fix: temporary configuration is not rolled back
modify the prompt message
> fix: temporary configuration is not rolled back

- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG.
Type:  
  BUG
Influences：  
  Separate load data handler and normal select handler
> Separate load data handler and normal select handler

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/config/Versions.java
- src/main/java/com/actiontech/dble/config/model/user/ManagerUserConfig.java
- src/main/java/com/actiontech/dble/config/model/user/RwSplitUserConfig.java
- src/main/java/com/actiontech/dble/config/model/user/ShardingUserConfig.java
- src/main/java/com/actiontech/dble/config/model/user/UserConfig.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/mysql/ChangeUserPacket.java
- src/main/java/com/actiontech/dble/net/mysql/ErrorPacket.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/AuthResultInfo.java
- src/main/java/com/actiontech/dble/net/service/Service.java
- src/main/java/com/actiontech/dble/server/response/SelectVersionComment.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/VariablesService.java
- src/main/java/com/actiontech/dble/services/factorys/BusinessServiceFactory.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLChangeUserService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/SecurityUtil.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLCurrentResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- version.txt
Reason:  
  Improve # inner783.  
Type:  
Influences：  
  support more protocol, eg, com_change_user, com_reset_connection,com_set_options
> support more protocol

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/cluster/ClusterPathUtil.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG inner-451
Type:  
  BUG
Influences：  
   1.bootstrap
2.pause logic
> inner-451: fixed: new node doesn't pause when the cluster is pausing.

- src/main/java/com/actiontech/dble/server/parser/PrepareChangeVisitor.java
- src/main/java/com/actiontech/dble/server/parser/PrepareStatementCalculateVisitor.java
- src/test/java/com/actiontech/dble/parser/PrepareChangeVisitorTest.java
Reason:  
  BUG inner-851
Type:  
  BUG
Influences：  
   prepareStatement/cursor
> inner-851: fixed: cachePrepare doesn't work.

- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
Reason:  
  Improve inner-451
Type:  
  Improve  
Influences：
> inner-451:typo

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #inner-872.
Type:  
  BUG
Influences：  
    fix ArrayOutOfIndex when load data
> inner-872: fix ArrayOutOfIndex when load data

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner 867
Type:  
  BUG
Influences：  
   fix 'begin'，the sql that follows commits implicitly
> fix：'begin'，the sql that follows commits implicitly

- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix  support set session transaction isolation level REPEATABLE READ  inner 863
> fix  support set session transaction isolation level REPEATABLE READ  inner 863

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/server/response/ShowDbleProcessList.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLCurrentResponseService.java
Reason:  
  BUG #inner 852 and inner 849. 
Type:  
  BUG
Influences：  
  fix that dble in performance mode doesn't work and cast exception when show connection
> fix that dble in performance mode doesn't work and cast exception when show connection

- src/main/resources/db_detail.xsd
- src/main/resources/user_detail.xsd
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
  fix: property value is String
> fix: property value is String

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/general/GeneralLogDisruptor.java
- src/main/java/com/actiontech/dble/log/general/GeneralLogProcessor.java
- src/main/java/com/actiontech/dble/server/status/GeneralLog.java
- src/main/java/com/actiontech/dble/services/manager/response/GeneralLogCf.java
Reason:  
  BUG inner 862、859、858
Type:  
  BUG
Influences：  
   fix general filePath, and btrace
> fix general filePath, and btrace（inner 862&859&858）

- src/main/java/com/actiontech/dble/config/model/user/RwSplitUserConfig.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
  fix add rwSplitUser  need check corresponding dbgroup inner 668 and 667
> fix add rwSplitUser  need check corresponding dbgroup inner 668 and 667

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  BUG.
Type:  
  BUG
Influences：  
  fix that dble hang when client keeps compression on
> fix that dble hang when client keeps compression on

- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/main/java/com/actiontech/dble/server/parser/ShardingServerParse.java
- src/main/java/com/actiontech/dble/server/response/ShowCreateView.java
- src/test/java/com/actiontech/dble/parser/ServerParserTest.java
Reason:  
  BUG #inner802,809,811. 
Type:  
  BUG
Influences：  
  fix bug about view
> inner802,809,811 - fix bug about view

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/resources/db.xsd
- src/main/resources/db_detail.xsd
- src/main/resources/sharding.xsd
- src/main/resources/sharding_detail.xsd
- src/main/resources/user.xsd
- src/main/resources/user_detail.xsd
Reason:  
  BUG 
Type:  
  BUG
Influences：  
fix: errors caused by xsd
fix: pure read-write separation scenario without loading sharding.xml
> fix: errors caused by xsd

- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG inner-885
Type:  
  BUG
Influences：  
fix: solve npe
> fix: solve npe

- src/main/java/com/actiontech/dble/server/response/ShowDbleProcessList.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix that multi statement doesn't work
> fix that multi statement doesn't work

- src/main/java/com/actiontech/dble/cluster/ClusterSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG inner-888
Type:  
  BUG
Influences：  
  1. bootstrap
  2. lock and getKv of ucore
> inner-888: fixed :dble startup with ucore cause ArrayIndexOutOfBoundsException

- src/main/java/com/actiontech/dble/meta/table/DbleCreateTableParser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix create table have AUTO_INCREMENT should  ignore  check full @@metadata inner 870
> fix create table have AUTO_INCREMENT should  ignore  check full @@metadata inner 870

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix multiple users are need cleaned up sysVariables and usrVariables inner 880
> fix multiple users are need cleaned up sysVariables and usrVariables inner 880

- src/main/java/com/actiontech/dble/server/parser/PrepareChangeVisitor.java
- src/test/java/com/actiontech/dble/parser/PrepareChangeVisitorTest.java
Reason:  
  BUG inner-851-bugfix
Type:  
  BUG
Influences：  
   prepare
> inner-851-bugfix: select with no from cause error in mysql5.7

- src/main/java/com/actiontech/dble/backend/mysql/PreparedStatement.java
- src/main/java/com/actiontech/dble/server/RequestScope.java
Reason:  
  BUG inner-884
Type:  
  BUG
Influences：  
   prepare
> inner-884: prepare phase cause NullPointException

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  BUG inner-882&879
Type:  
  BUG
Influences：  
   config load
> inner-882&879: add config check for cursor settings

- src/main/java/com/actiontech/dble/config/converter/SequenceConverter.java
- src/main/java/com/actiontech/dble/route/util/OrderedProperties.java
- src/main/java/com/actiontech/dble/route/util/PropertiesUtil.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBackend.java
Reason:  
  BUG innert-843/883
Type:  
  BUG
Influences：  
fix: properties read and write order
fix: connection service is null
> fix: properties read and write order

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  BUG #2389 
Type:  
  BUG
Influences：  
fix: auth plugin is empty when Navicat 11 is connected
> fix: auth plugin is empty when Navicat 11 is connected

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileConfig.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileContext.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/DefaultHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/DefaultValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/SchemaHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/ShardingValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitDumpHandler.java
Reason:
  Improve optimize split inner-790
Type:
  Improve
Influences：
  optimize split
> feat: optimize split

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
 fix add rwsplit mode when  all  slave node is alive  that request to master node inner 725
> fix add rwsplit mode when  all  slave node is alive  that request to master node inner 725

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/ZkSender.java
Reason:  
  BUG inner-898
Type:  
  BUG
Influences：  
   pause for zk
> inner-898: stop node when pausing cause error.

- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/cluster/values/PauseInfo.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG inner-875
Type:  
  BUG
Influences：  
   pause
> inner-875: report error if run different PAUSE command

- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG  and Improve  
Type:  
  BUG and Improve  
Influences：  
  load data send to mysql  or receive from mysql, update the readTime of the frontend connection inner 418.
fix the parameters resulting from refactoring are not available.
> load data send to mysql  or receive from mysql, update the readTime of the frontend connection inner 418

- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG.
Type:  
  BUG  
Influences：  
  revert inner-889
> revert inner-889

- src/main/assembly/assembly-linux.xml
- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
fix: null judgment and pack tar.gz to remove xsd files
> fix: null judgment and pack tar.gz to remove xsd files

- src/main/java/com/actiontech/dble/plan/common/item/function/mathsfunc/ItemFuncConv.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix bin function error inner 746.
compatibility was done in the last step
> fix bin function error inner 746

- src/main/java/com/actiontech/dble/backend/mysql/ByteUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/store/CursorCacheForGeneral.java
- src/main/java/com/actiontech/dble/backend/mysql/store/LocalResult.java
Reason:  
  BUG inner-884
Type:  
  BUG
Influences：  
   prepare
> inner-884-bugfix: prepare phase cause error

- src/main/java/com/actiontech/dble/route/parser/ManagerParseConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
  BUG inner-902/906
Type:  
  BUG
Influences：  
fix: hint statement use executeSql
fix: wrong judgment when parsing reload
> fix: hint statement use executeSql

- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  BUG inner-884
Type:  
  BUG
Influences：  
  
> inner-884-supplement: prepare phase cause error

- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
  fix dryrun check database and then check table again inner 672
> fix dryrun check database and then check table again inner 672

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  inner-879-bugfix
Type:  
  BUG
Influences：  
   fix xx
> inner-879-bugfix: modify heapTableChunkSize check

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG inner-875-bugfix
Type:  
  BUG
Influences：  
   fix xx
> inner-875-bugfix: change warning messages on single mode in PAUSE operation

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  BUG inner  865
Type:  
  BUG
Influences：  
   fix lost records for CLOSE_STMT packet in general Log
> fix lost records for CLOSE_STMT packet in general Log(inner-865)

- src/main/resources/log4j2.xml
Reason:  
  BUG inner-912
Type:  
  BUG
Influences：  
  log4j
> inner-912: try to fix log missing in automatic test pipeline

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:
  BUG #2389
Type:
  BUG
Influences：
fix: auth plugin is empty when Navicat 11 is connected
> fix: auth plugin is empty when Navicat 11 is connected(cherry pick from master #2466) 

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
   Improve #inner 913.  
Type:  
   Improve  
Influences：  
   add state column for dble backend connections
> inner-913:add state column for dble backend connections

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:
  BUG
Type:
  BUG
Influences：
conflicts:src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
fix: prepare sql use single frontConnection not multiple frontConnection inner 594
> fix:  prepare sql use single frontConnection not multiple frontConnection inner 594

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ConnectionHeartBeatHandler.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
  BUG #inner 915.
Type:  
  BUG
Influences：  
  props of testOn* take no effect
> inner 915:props of testOn* take no effect

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG #inner 916.
Type:  
  BUG
Influences：  
  props of testOn* take no effect
> inner-916:props of testOn* take no effect

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterOffLineListener.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/listen/OfflineStatusListener.java
Reason:  
  BUG inner-910
Type:  
  BUG
Influences：  
   fix xx
> inner-910: pause operation shouldn't resume when caller is down

- src/main/java/com/actiontech/dble/plan/common/item/function/ItemCreate.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  support day function inner 663
> support day function inner 663

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseReload.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/TruncateHander.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/AssociateTablesByEntryByUser.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/FrontendByBackendByEntryByUser.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/TableByUserByEntry.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG inner 923\926\927\928\931\932\934
Type:  
  BUG
Influences：  
   fix:sql statistic's small bugs
> fix:sql statistic's small bugs

- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncSubstr.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
  fix SUBSTRING function inner 757
> fix SUBSTRING function inner 757

- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   adjust prompt
> adjust prompt

- src/main/assembly/conf/log4j2.xml
- src/main/resources/log4j2.xml
Reason:  
  BUG inner-912
Type:  
  BUG
Influences：  
   fix xx
> Revert: inner-912: try to fix log missing in automatic test pipeline

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
Reason:  
  BUG inner-879-bugfix2
Type:  
  BUG
Influences：  
  config init
> inner-879-bugfix2: in config init, string to Integer report error.but  dble start successfully.

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/resources/user.xsd
- src/test/java/com/actiontech/dble/config/ConfigTest.java
Reason:  
  BUG inner-918/922
Type:  
  BUG
Influences：  
fix: no need to synchronize dbGroupStatus before reload operation(inner-922)
fix: the user order in user.xml does not need to be specified(inner-918)
> fix: no need to synchronize dbGroupStatus before reload operation

- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  
> add log for buffer

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FieldListHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  field list need synchronize context
> field list need synchronize context

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/server/response/ShowDbleProcessList.java
- src/main/java/com/actiontech/dble/services/manager/handler/ShowProcesslistHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
Reason:  
  BUG #2377.
Type:  
  BUG
Influences：  
  support rw connection in show @@processlist
> issue 2377 - support rw connection in show @@processlist

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG inner 816
Type:  
  BUG
Influences：  
   when rwSplitMode = 0 and master of mysql group is changed, dble need to build connection pool for salve.
> inner 816 - when rwSplitMode = 0 and master of mysql group is changed, dble need to build connection pool  for salve.

- src/main/java/com/actiontech/dble/server/parser/AbstractServerParse.java
- src/main/java/com/actiontech/dble/server/parser/RwSplitServerParseSelect.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/server/response/SelectVariables.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
Reason:  
  BUG 804&953
Type:  
  BUG
Influences：  
   fix xx
> Inner 804&953 - fakeMysqlVersion bug and select for  share support

- src/main/java/com/actiontech/dble/server/status/GeneralLog.java
- src/main/java/com/actiontech/dble/services/manager/response/GeneralLogCf.java
Reason:  
  BUG inner 907
Type:  
  BUG
Influences：  
   display canonical path
> display canonical path

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/XAHandler.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/BeginHandler.java
- src/main/java/com/actiontech/dble/server/handler/RollBackHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/ShardingStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticBackendSqlEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticFrontendSqlEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticTxEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/AssociateTablesByEntryByUserCalcHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/FrontendByBackendByEntryByUserCalcHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/TableByUserByEntryCalcHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   improve tx statistics
> improve tx statistics

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
Reason:  
  BUG 
Type:  
  BUG  
Influences：  
  fix dryrun multiple nodes have incorrect data inner 949
> fix dryrun  multiple nodes have incorrect data inner 949

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/general/response/DdlChildResponse.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/listen/DDLChildListener.java
Reason:  
  BUG inner-912
Type:  
  BUG
Influences：  
   fix xx
> inner-912: fixed:lost connection when dble doing cluster ddl

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:  
  inner-836-improve
Type:  
    Improve  
Influences：  
   fix xx
> inner-836-improve:fixed OOM in big packet

- src/main/resources/log4j2.xml
Reason:  
  Provide convenience for development。
A pattern like this will make the log can be clickable every line.
Type:  
  BUG
Influences：  
   fix xx
> modify  log4j pattern for developer

- pom.xml
Reason:  
  BUG
Type:  
  BUG
Influences：  
   Component version upgrade
> Component version upgrade

- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/backend/datasource/check/CheckSumChecker.java
- src/main/java/com/actiontech/dble/backend/datasource/check/CountChecker.java
Reason:  
  Improve inner-794
Type:  
  Improve 
Influences：  
   fix: global table detection alarm code modification
> fix: global table detection alarm code modification

- src/main/java/com/actiontech/dble/services/manager/response/ShowReloadStatus.java
Reason:  
     Improve #inner 952.  
Type:  
  Improve  
Influences：  
  Result of show @@reload_status is empty instead of default row when there is no reload action.
> Result of show @@reload_status is empty instead of default row when there is no reload action.

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner-943
Type:  
  BUG
Influences：  
  fix: when the schemas of the front and back ends are inconsistent, reset the connection status
> fix: when the schemas of the front and back ends are inconsistent, reset the connection status

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG #inner 915. 
Type:  
  BUG
Influences：  
  testOnBorrows takes no effect when backend connection was take directly from connection pool
> testOnBorrows takes no effect when backend connection was take directly from connection pool

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/FrontendByBackendByEntryByUserCalcHandler.java
Reason:  
  BUG inner 959
Type:  
  BUG
Influences：  
   fix
> correct the accumulation of tx_rows

- src/main/java/com/actiontech/dble/util/NameableThreadFactory.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  fix dble crash when load data statement have local field inner 966
> the log shows an uncaught exception inner 967

- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix connection crash when load data inner 828
> fix connection crash when load data inner 828

- src/main/java/com/actiontech/dble/plan/common/item/function/mathsfunc/ItemFuncConv.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix connection crash when load data inner 828
> fix conv function format error return value  innner 908

- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncSubstr.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix SUBSTRING function  index out of range inner 945
> fix SUBSTRING function  index out of range inner 945

- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/listen/DDLChildListener.java
Reason:  
    inner 912 supplement
Type:  
  BUG
Influences：  
   ddl
> inner 912 supplement - ddl response skip init event

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAEndStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
Reason:  
  BUG inner 874
Type:  
  BUG
Influences：  
   fix xx
> [inner 874] fixed npe when kill xa query

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
   Improve #inner 915.  
Type:  
   Improve  
Influences：  
   props of testOn* take no effect
> inner 915 - props of testOn* take no effect

- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
Reason:  
  BUG inner-876
Type:  
  BUG
Influences：  
show @@ help increase thread parameters
> fix: show @@help increase thread parameters

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/UnionHandler.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   eg: select id from  tb_hash_sharding union SELECT CURRENT_TIME /*allow_diff*/;
> fix NullPointException using CURRENT_TIME function

- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/resources/db.xsd
Reason:  
  BUG inner-976
Type:  
  BUG
Influences：  
fix: db.xml allows the content to be empty
> fix: db.xml allows the content to be empty

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
Reason:  
  inner-977
Type:  
  BUG
Influences：  
   fix xx
> inner-977: "select ... for update" with non-transaction should send to master

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG inner 959
Type:  
  BUG
Influences：  
   fix:'lock tables ...' sql ,tx_count does not add up
> fix:'lock tables ...' sql ,tx_count does not add up

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
Reason:  
   Improve.  
Type:  
  Improve  
Influences：  
  add log for ci
> add log for ci

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadLoadDataNum.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  Improve   
Type:  
   Improve  
Influences：  
   fix bug inner 961 and 962  and 963
> fix load data prompt optimized

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLog.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLogByTxByEntryByUser.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
  Improve #inner 781.  
Type:  
  Improve  
Influences：  
  add sql statistic for sampling
> add sql statistic for sampling

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/LoadDataProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG  
Type:  
  BUG 
Influences：  
   fix xx
> fix special handing load data local sql keep putting SQL on the queue inner 971

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FileUtils.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/server/status/LoadDataBatch.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  fix some bug and improved display
Type:  
  BUG & Improve  
Influences：  
  fix  load data error inner 452 subtask
> fix  load data error inner 452 subtask

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ConnectionHeartBeatHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLog.java
Reason:  
  BUG #inner 987.
Type:  
  BUG
Influences：  
  ok packet of conn heartbeat returns when heartTimeout isn't initialized
> ok packet of conn heartbeat returns when heartTimeout isn't initialized

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/service/ServiceTask.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  inner-983
Type:  
  BUG
Influences：  
   fix xx
> inner-983: fixed load data lost connection

- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner 944
Type:  
  BUG
Influences：  
   fix :Sharding user configuring the blacklist fails to execute begin
> Sharding user configuring the blacklist fails to execute begin

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   adjust log level
> adjust log level

- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG  
Type:  
  BUG  
Influences：  
  fix load data error inner 1000 and 986
> fix load data error inner 1000

- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix 'begin' to repeat on sql_log table
> fix 'begin' to repeat on sql_log table

- src/main/java/com/actiontech/dble/route/parser/ManagerParseReload.java
- src/main/java/com/actiontech/dble/services/manager/handler/ReloadHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleVariables.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLog.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLogByTxByEntryByUser.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/AssociateTablesByEntryByUserCalcHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/FrontendByBackendByEntryByUserCalcHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/TableByUserByEntryCalcHandler.java
- src/test/java/com/actiontech/dble/parser/ManagerParserTest.java
Reason:  
   Improve
Type:  
  Improve  
Influences：  
  optimize sampling statistic
> optimize sampling statistic

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
Reason:  
  BUG inner-1019
Type:  
  BUG
Influences：  
fix: the listening thread(ddl/view/ha) is not started
> fix: the listening thread(ddl/view/ha) is not started

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  BUG inner-914
Type:  
  BUG
Influences：  
   fix xx
> inner-914: fix cpu high load in FrontendRunnable Thread.

- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
Reason:  
  BUG inner-942
Type:  
  BUG
Influences：  
fix: eliminate invalid connections
> fix: eliminate invalid connections

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  remove log
> remove log

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/handler/LoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG & Improve
Type:  
  BUG & Improve  
Influences：  
   fix skip idleTimeout checks inner 418 and  load data error when mysql crash
> fix skip idleTimeout checks inner 418 and  load data error when mysql crash

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG inner-DMP-7317
Type:  
  BUG
Influences：  
fix: resolve DBLE_REACH_MAX_CON
> fix: resolve DBLE_REACH_MAX_CON

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
Reason:
  BUG inner-1019
Type:
  BUG
Influences：
fix: the listening thread(ddl/view/ha) is not started
> fix: the listening thread(ddl/view/ha) is not started(cherry-pick 2559)

- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUGinner-983
Type:  
  BUG
Influences：  
   fix xx
> inner-983:fixed load data   out of order

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  inner-914-supplement
Type:  
  Improve  
Influences：  
   fix xx
> inner-914-supplement：limit size for frontQueue

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  fix spelling and modify tips
> fix spelling and modify tips

- pom.xml
Reason:  
    add_exclusion
Type:  
   Improve  
Influences：  
  add_exclusion
> add_exclusion

- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
Reason:  
  BUG inner-DMP-7363
Type:  
  BUG
Influences：  
fix: xa retry mechanism update
> fix: xa retry mechanism update

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
Reason:  
  BUG 
Type:  
  BUG  
Influences：  
   fix in some cases there is no update time inner 418
> fix in some cases there is no update time

- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
  BUG #inner 1032, inner 1033.
Type:  
  BUG
Influences：  
  fix bug about sampling
> fix bug about sampling

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #inner 1044. 
Type:  
  BUG
Influences：  
  packetId is incorrect when doing ddl
> packetId is incorrect when doing ddl

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FetchStoreNodeOfChildTableHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
Reason:  
  BUG inner-1045:
Type:  
  BUG
Influences：  
   fix xx
> inner-1045: fix ER table cause NPE and hang.

- src/main/java/com/actiontech/dble/backend/mysql/view/FileSystemRepository.java
Reason:  
  BUG inner-1046
Type:  
  BUG
Influences：  
   fix xx
> inner-1046: fixed: init view from empty file

- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix flow control error when turn off flow control inner 418
> fix flow control error when turn off flow control inner 418

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResultCode.java
Reason:  
   Improve
Type:  
  Improve  
Influences：  
   fix xx
>  modify doc for ProtoHandlerResultCode

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> show idleTimeout value

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
Reason:  
  BUG #inner 1047. 
Type:  
  BUG
Influences：  
  avoid npe when keeping useSerializableMode on
> avoid npe when keeping useSerializableMode on

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ConnectionHeartBeatHandler.java
Reason:  
  BUG #inner 1028. 
Type:  
  BUG
Influences：  
  dble hang when backend connection is closed in process of testOnCreate
> dble hang when backend connection is closed in process of testOnCreate

- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
Reason:  
  BUG #inner 1048.
Type:  
  BUG 
Influences：  
  reloading samplingRate doesn't work
> reloading samplingRate doesn't work

- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   fix in some cases there is no update time
> fix in some cases there is no update time(cherry-pick 2579 and 2573)

- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
 fix  description of parameters
> fix  description of parameters inner 1050

- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix description of parameters
> fix  description of parameters(cherry-pick2587)

- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/test/java/com/actiontech/dble/util/ManagerTableTest.java
Reason:  
  BUG inner 1051
Type:  
  BUG
Influences：  
  fix：table name was not resolved in the hint sql
> fix：table name was not resolved in the hint sql

- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/GetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowShardingNode.java
Reason:  
  BUG inner-1043
Type:  
  BUG
Influences：  
fix: when dbGroup is not configured, it should start successfully
DBLE0REQ-1043
> fix: when dbGroup is not configured, it should start successfully

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ConnectionHeartBeatHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  parameter testoncreate doesn't work
> fix some bug for connection heartbeat

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  inner-914
Type:  
  BUG
Influences：  
   fix xx
> inner-914: fix cpu high load in FrontendRunnable Thread and fix oom

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  BUG inner-1056
Type:  
  BUG
Influences：  
   prepare
> [inner-1056] COM_STMT_CLOSE packet cause hang

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandlerForPrepare.java
Reason:  
  BUG inner-1057
Type:  
  BUG
Influences：  
   connection pool
> [inner-1057] prepareStatement  doesn't release connection

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ConnectionHeartBeatHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  cherrry pick from 3.21.02.99
> fix some bug from 3.21.02.0

- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner 1052
Type:  
  BUG
Influences：  
   fix: after configuring blacklist, execute error sql, prompt is not reasonable
> fix: after configuring blacklist, execute error sql, prompt is not reasonable

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  inner-1006
Type:  
  Improve
Influences：  
   prepare
> inner-1006: set option for enable cursor

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandlerForPrepare.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  BUG inner1056 1057
Type:  
  BUG
> cherry-pick from 02.99

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
 the sequence is params,field in com_stmt_prepare response
> the sequence is params,field in com_stmt_prepare response

- docker-images/dble-image/Dockerfile
Reason:  
  BUG
Type:  
  BUG
Influences：  
  build arg of Dockerfile can't be assigned
> build arg of Dockerfile can't be assigned

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLInstance.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-1064
Type:  
  BUG 
Influences：  
   in subquery explain
> inner-1064 in subquery explain

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG Atk-1818
Type:  
  BUG
Influences：  
   fix xx
> atk-1818: multiStatement bug.

- src/main/java/com/actiontech/dble/services/rwsplit/MysqlPrepareLogicHandler.java
Reason:  
  BUG #inner 1065.
Type:  
  BUG
Influences：  
  fix bug for com_stmt_prepare
> fix bug for com_stmt_prepare

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #inner1074.
Type:  
  BUG
Influences：  
  set autocommit=0;set autocommit=1;dml;rollback; dml is rollback
> fix bug that "set autocommit=1" doesn't work,eg set autocommit=0;set autocommit=1;dml;rollback; dml is rollback

- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOReactor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
  BUG inner-690
Type:  
  BUG
Influences：  
   ioReactor
> inner-690: fix AsynchronousCloseException while read

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix support  like database.table.Column insert inner 905
> fix support  like database.table.Column insert inner 905

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
Reason:  
  BUG inner-1006
Type:  
  BUG
Influences：  
   cursor
> inner-1006-bugfix: check heapTableBufferChunkSize event if cursor is disabled

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   multi statement packet.
PS: cherry pick doesn't succeed. Has conflict.
>  Atk 1818 

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateTableParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
Reason:  
  BUG inner 982
Type:  
  BUG
Influences：  
   Optimizing Transactions statistics
> Optimizing Transactions statistics

- src/main/java/com/actiontech/dble/route/handler/HintShardingNodeHandler.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/impl/DefaultRouteStrategy.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
- src/main/java/com/actiontech/dble/singleton/RouteService.java
Reason:  
  BUG #2638 .
Type:  
  BUG
Influences：  
  fix bug that keep slow log on, dble may occur oom
> fix bug that keep slow log on, dble may occur oom

- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  enlarge metaspace and shrink thread stack size
> enlarge metaspace and shrink thread stack size

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/net/executor/FrontendBlockRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/mysql/ErrorPacket.java
- src/main/java/com/actiontech/dble/net/service/NotificationServiceTask.java
- src/main/java/com/actiontech/dble/net/service/ServiceTask.java
- src/main/java/com/actiontech/dble/net/service/ServiceTaskType.java
- src/main/java/com/actiontech/dble/server/response/PreparedStmtResponse.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/singleton/ConnectionSerializableLock.java
Reason:  
  Improve Inner 1010 
Type:  
  Improve
Influences：  
   front task process
> Inner 1010 Refactor the front-end thread pool （ use planE）

- src/main/java/com/actiontech/dble/backend/mysql/PreparedStatement.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  BUG inner-1006-bugfix
Type:  
  BUG
Influences：  
 fix cursor for blob type
> inner-1006-bugfix:fix cursor for blob type

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix table name  may not correct inner 905
> fix table name  may not correct inner 905

- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
  BUG #inner 1087,1088,1093,1094.
Type:  
  BUG
Influences：  
  fix bug about sql digest
> fix bug about sql digest

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandlerForPrepare.java
- src/main/java/com/actiontech/dble/net/executor/FrontendBlockRunnable.java
Reason:  
  inner-1078
Type:  
  BUG
Influences：  
  prepare statement
> inner-1078: fix prepare statement bug for set context.

- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  BUG inner-1079
Type:  
  BUG
Influences：  
  fix ConcurrentModificationException in PrepareStatement
> inner-1079:fix ConcurrentModificationException in PrepareStatement

- src/main/java/com/actiontech/dble/backend/mysql/PreparedStatement.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
- src/main/java/com/actiontech/dble/server/parser/PrepareStatementParseInfo.java
Reason:  
  inner-1080:Improve the judgment of placeholders for prepareStatement. 
Type:  
  BUG
Influences：  
   PrepareStatement
> Inner 1080:Improve the judgment of placeholders for prepareStatement.          

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinInnerHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinNodeHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG #2408  inner-504
Type:  
  BUG
Influences：  
fix: remove schema when merging and issuing
after join and condition is spliced to where
#2617
> fix: remove schema when merging and issuing

- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticBackendSqlEntry.java
Reason:  
  BUG inner 1062
Type:  
  BUG
Influences：  
  fix: occasional statistical problems
> fix(inner-1062): the backendSqlEntry been tampered with

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/route/handler/HintDataNodeHandler.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/impl/DefaultRouteStrategy.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
- src/test/java/com/actiontech/dble/route/RouteWithOrTest.java
Reason:  
  BUG #2638. 
Type:  
  BUG
Influences：  
   fix bug that keep slow log on, dble may occur oom
> BUG #2638 - fix bug that keep slow log on, dble may occur oom

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropTableParser.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   just drop table that do not exist should prompt error
> just drop table that do not exist should prompt error

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix add dbGroup check inner 1121
> fix add dbGroup check inner 1121

- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
Reason:  
  BUG. 
Type:  
  BUG  
Influences：  
  fix ArrayIndexOutOfBoundException using big packet
> fix ArrayIndexOutOfBoundException using big packet

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAAnalysisHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
Reason:  
  BUG inner 1120、1123
Type:  
  BUG
Influences：  
   fix detect XA residual bugs
> fix: detect XA residual bugs

- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG inner 1108
Type:  
  BUG
Influences：  
   trace is not supported for rwSplitUser
> trace is not supported for rwSplitUser

- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnections.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/singleton/ConnectionSerializableLock.java
Reason:  
  inner-1010-supplement.  
Type:  
  Improve  
Influences：  
  show @@connection
> inner-1010-supplement: add RECV_QUEUE in show @@connection

- src/main/java/com/actiontech/dble/btrace/provider/IODelayProvider.java
- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/Connection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOWriteHandler.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/CloseServiceTask.java
- src/main/java/com/actiontech/dble/net/service/InnerServiceTask.java
- src/main/java/com/actiontech/dble/net/service/NormalServiceTask.java
- src/main/java/com/actiontech/dble/net/service/NotificationServiceTask.java
- src/main/java/com/actiontech/dble/net/service/ServiceTask.java
- src/main/java/com/actiontech/dble/net/service/ServiceTaskFactory.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLChangeUserService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG  inner-960
Type:  
  BUG
Influences：  
   1. modfiy  logic for close.
2. add new ServiceTaskType
> inner-960:support gracefulclose in IO thread

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAAnalysisHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleXaRecover.java
Reason:  
  BUG inner 1129
Type:  
  BUG
Influences：  
   correction expression
> correction expression

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnections.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnection.java
Reason:  
  Improve inner 1003
Type:  
  Improve  
Influences：  
   add the xa_id field
> add the xa_id field

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  BUG #2655 and pr#2397. 
Type:  
  BUG
Influences：  
  cherry pick from pr#2397 and fix NullPointException from issue#2655
> cherry pick from pr#2397 and fix NullPointException from issue#2655

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   fix rwSplitMode check inner 1081
> fix rwSplitMode check inner 1081

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  Improve inner#1077.  
Type:  
  Improve  
Influences：  
  ignore error ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION
> ignore error ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/main/java/com/actiontech/dble/plan/optimizer/SubQueryPreNoTransformProcessor.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve inner 1055
Type:  
  Improve  
Influences：  
   in subquery not transform join inner 1055
> in subquery  not transform join inner 1055

- src/main/java/com/actiontech/dble/net/executor/FrontendBlockRunnable.java
- src/main/java/com/actiontech/dble/net/executor/WriteToBackendRunnable.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
Reason:  
  BUG inner-1132
Type:  
  BUG
Influences：  
fix: wakeup selector
> fix: wakeup selector

- src/main/java/com/actiontech/dble/net/executor/BackendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendBlockRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/WriteToBackendRunnable.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  BUG inner-957
Type:  
  BUG
Influences：  
fix: capture Throwable to ensure that the thread will not exit when an error or exception occurs
> fix: capture Throwable to ensure that the thread will not exit when an error or exception occurs

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
   inner-1124 prevent illegal auth packet &modify packet read
Type:  
  Improve
Influences：  
  
> inner-1124:prevent illegal auth packet& modify packet read

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/util/DebugUtil.java
Reason:  
  BUG inner-960
Type:  
  BUG
Influences：  
  bugfix for NullPointException
> inner-960:bugfix for NullPointException

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/net/mysql/PingPacket.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  inner-1115
Type:  
  BUG
Influences：  
  fix cursor hang
> inner-1115 : fix cursor hang

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG inner-1136: can bootstrap if sharding.xml is empty
Type:  
  BUG
Influences：  
   bootstrap
> inner-1136: can bootstrap if sharding.xml is empty

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
   Improve 
Type:  
     Improve  
Influences：  
   fix dbGroup will disabled need more explicit error reporting inner 893 
fix start dble not check dbgroup
> fix dbGroup will disabled need more explicit error reporting inner 893

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnections.java
Reason:  
  BUG #inner 1133.
Type:  
  BUG
Influences：  
  fix service ClassCastException using dble rwSplit
> fix service ClassCastException using dble rwSplit

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/cluster/JsonFactory.java
- src/main/java/com/actiontech/dble/cluster/values/ClusterValueAdapterForWrite.java
- src/main/java/com/actiontech/dble/cluster/values/JsonObjectWriter.java
- src/main/java/com/actiontech/dble/cluster/values/RawJson.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/converter/SequenceConverter.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  inner-1138:remove null field in json
Type:  
  BUG
Influences：  
   fix xx
> inner-1138:remove null field in json

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidImplicitCommitParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropTableParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> DDL is not actually executed

- src/main/java/com/actiontech/dble/net/executor/BackendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/WriteToBackendRunnable.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:
  BUG inner-957
Type:
  BUG
Influences：
fix: capture Throwable to ensure that the thread will not exit when an error or exception occurs
> fix: capture Throwable to ensure that the thread will not exit when an error or exception occurs(cherry-pick #2665)

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidImplicitCommitParser.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> correct judgment

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropViewParser.java
Reason:  
  BUG inner 1153
Type:  
  BUG
Influences：  
   fix xx
> processing key

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  BUG inner-1124:prevent illegal auth packet
pick from 02.99
Type:  
  BUG
Influences：  
   auth
> inner-1124:prevent illegal auth packet (#2673)

- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
Reason:  
  BUG inner 1141
Type:  
  BUG
Influences：  
   fix：sql statistics for NPE
> fix: sql statistics for NPE

- src/main/java/com/actiontech/dble/cluster/AbstractGeneralListener.java
Reason:  
  Bug: Supplement to pr #2680  
Type:  
  Bug  
Influences：  
   cluster
> inner-1008: supplement to pr #2680

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1157
Type:  
  BUG
Influences：  
   fix xx
> adjust the error reporting content

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidImplicitCommitParser.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  BUG inner 1117
Type:  
  BUG
Influences：  
   fix xx
> rwsplitUser, execute multi-query,  questions +1 and transactions +1

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1158
Type:  
  BUG
Influences：  
   fix xx
> adjust part of the locktable code

- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
Reason:  
  BUG inner 1146
Type:  
  BUG
Influences：  
   fix xx
> correct the error code

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix load data  incorrect execution result inner 1098
> fix load data  incorrect execution result inner 1098

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/views/SqlLogByTxByEntryByUser.java
- src/main/java/com/actiontech/dble/services/manager/information/views/SqlLogByTxDigestByEntryByUser.java
Reason:  
  BUG.  
Type:  
  BUG
Influences：  
  fix some bug about sql digest
> fix some bug about sql digest

- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix: precision problem

- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnit.java
- src/main/java/com/actiontech/dble/route/util/ConditionUtil.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-1139: move ddl trace to another  log file
Type:  
  BUG
Influences：  
  trace log
> inner-1139: move ddl trace to another  log file

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner-950
Type:  
  BUG
Influences：  
fix: adjust the sequence of locks
> fix: adjust the sequence of locks

- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
Reason:  
  BUG inner 920
Type:  
  BUG
Influences：  
   fix  use the same method to deal with property inner 920
> fix  use the same method to deal with property inner 920

- src/main/java/com/actiontech/dble/btrace/provider/ClusterDelayProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BtraceClusterDelay.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> add btrace

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropIndexParser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix check tableName inner 1104
> fix check tableName inner 1104

- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG  inner 911, inner 1150
Type:  
  BUG
Influences：  
   fix filter conditions like group by, order by ,having inner 911
> fix filter conditions like group by, order by ,having inner 911

- src/main/java/com/actiontech/dble/statistic/sql/ShardingStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
Reason:  
  BUG inner 1164
Type:  
  BUG
Influences：  
   fix xx
> fix: the DDL examined_rows value is not counted correctly

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/handler/HintShardingNodeHandler.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidLockTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterViewParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateOrReplaceViewParser.java
- src/main/java/com/actiontech/dble/route/util/RouteResultCopy.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/server/response/FieldList.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
- src/main/java/com/actiontech/dble/server/response/ShowVariables.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLShardingSQLHandler.java
Reason:  
  BUG inner-936
Type:  
  BUG
Influences：  
fix: connection affinity in a transaction
> fix: connection affinity in a transaction

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
Reason:
  BUG inner-1063
Type:
  BUG
Influences：
fix: rule verification should be before acquiring the lock
> fix: rule verification should be before acquiring the lock

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MysqlDropViewHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropViewParser.java
Reason:  
  BUG inner 1163 ,inner 1171
Type:  
  BUG
Influences：  
 fix drop view sql hang  and add checkView
> fix drop view sql hang  and add checkView

- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/parser/AbstractServerParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
Reason:  
  BUG inner 1173
Type:  
  BUG
Influences：  
   fix xx
> fix: execute multi-sql,statistics table is not correct

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/Connection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
Reason:  
  BUG inner-1151: fixed closedChannelException cause npe.
Type:  
  BUG
Influences：  
  
> inner-1151: fixed closedChannelException cause npe.

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeat.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowShardingNode.java
- src/main/java/com/actiontech/dble/services/manager/response/StopHeartbeat.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG #inner 1125.  
Type:  
  BUG
Influences：  
   handle error packet in backend handshake phase to avoid ArrayIndexOutOfBoundException
> handle error packet in backend handshake phase to avoid ArrayIndexOutOfBoundException

- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLog.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticFrontendSqlEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
  BUG #inner 994.
Type:  
  BUG
Influences：  
  make start_time in sql_log manager table human readable
> make start_time in sql_log manager table human readable

- src/main/java/com/actiontech/dble/btrace/provider/DbleThreadPoolProvider.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPool.java
- src/main/java/com/actiontech/dble/util/NameableExecutor.java
Reason:  
  BUG inner-1149/inner-1160
Type:  
  BUG 
Influences：  
* optimize the error message
* adjust the decreasePoolSize strategy
* increase btrace points
> fix: optimize DbleThreadPool

- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnit.java
- src/main/java/com/actiontech/dble/route/util/ConditionUtil.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-1139-bugfix: move ddl trace to another  log file
Type:  
  BUG
Influences：  
   fix xx
> inner-1139-bugfix: move ddl trace to another  log file

- src/main/java/com/actiontech/dble/config/WallErrorCode.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner 1155
Type:  
  BUG
Influences：  
   Adjust the SQL prompt blocked by the blacklist
> Adjust the SQL prompt blocked by the blacklist

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/plan/common/item/function/sumfunc/ItemFuncGroupConcat.java
- src/main/java/com/actiontech/dble/services/manager/information/views/SqlLogByTxDigestByEntryByUser.java
Reason:  
  BUG #inner 1093. 
Type:  
  BUG
Influences：  
  limit group_concat result length
> limit group_concat result length

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
Reason:  
  Improve inner-1199:adjust log
Type:  
  Improve  
Influences：  
   fix xx
> inner-1199:adjust log

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAEndStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/CoordinatorLogEntry.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/Deserializer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/ParticipantLogEntry.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/Serializer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XaCheckHandler.java
- src/main/java/com/actiontech/dble/config/model/user/UserConfig.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner-1188
Type:  
  BUG
Influences：  
* xa-id adds table information
* user-max_conn_count default value is 0
> fix: xa-id adds table information

- src/main/java/com/actiontech/dble/config/WallErrorCode.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner 1155
Type:  
  BUG
Influences：  
   handle duplicate errorCode
> handle duplicate errorCode

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
Reason:
  BUG inner-1063
Type:
  BUG
Influences：
fix: rule verification should be before acquiring the lock
#2725
> fix: rule verification should be before acquiring the lock(cherry pick from 2725)

- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/singleton/ConnectionSerializableLock.java
Reason:  
  BUG inner-1202:fix bug for create so many NotificationServiceTask 
Type:  
  BUG
Influences：  
   fix xx
> inner-1202:fix bug for create so many NotificationServiceTask 

- src/main/java/com/actiontech/dble/cluster/values/JsonObjectWriter.java
- src/main/java/com/actiontech/dble/cluster/values/RawJson.java
- src/main/java/com/actiontech/dble/config/converter/SequenceConverter.java
- src/main/java/com/actiontech/dble/route/util/PropertiesUtil.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleConfig.java
Reason:  
  BUG inner-1156:adjust sequence format to fix convertException
Type:  
  BUG
Influences：  
   fix xx
> inner-1156:adjust sequence format to fix convertException

- src/main/java/com/actiontech/dble/btrace/provider/IODelayProvider.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOWriteHandler.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/CloseServiceTask.java
- src/main/java/com/actiontech/dble/util/DebugUtil.java
- src/main/java/com/actiontech/dble/util/TraceUtil.java
Reason:  
   Improve:inner-960-optimize:reduce logs and adjust delay logic.
Type:  
  Improve
Influences：  
   graceful close
> inner-960-optimize:reduce logs and adjust delay logic.

- src/main/java/com/actiontech/dble/route/parser/druid/DruidShardingParseInfo.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/util/ConditionUtil.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-1193
Type:  
  BUG
Influences：  
fix: when using split fields to associate tables, try to optimize
> fix: when using split fields to associate tables, try to optimize

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidImplicitCommitParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/BeginHandler.java
- src/main/java/com/actiontech/dble/server/handler/RollBackHandler.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   SQL statistics should not affect the business logic
> SQL statistics should not affect the business logic

- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerWritableTable.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
Reason:  
  BUG inner-1212/inner-1217/inner-1061
Type:  
  BUG
Influences：  
fix: lock degradation of dble_information
fix npe
> fix: lock degradation of dble_information

- src/main/java/com/actiontech/dble/plan/optimizer/FilterPusher.java
- src/main/java/com/actiontech/dble/plan/optimizer/OrderByPusher.java
Reason:  
  BUG  inner 1192
Type:  
  BUG
Influences：  
  subquery  push down  inner 1192
> subquery  push down  inner 1192

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/savepoint/SavePointHandler.java
- src/main/java/com/actiontech/dble/net/connection/WriteAbleService.java
- src/main/java/com/actiontech/dble/net/mysql/EOFPacket.java
- src/main/java/com/actiontech/dble/net/mysql/OkPacket.java
- src/main/java/com/actiontech/dble/net/mysql/PingPacket.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
- src/main/java/com/actiontech/dble/server/response/Ping.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/services/manager/handler/UseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner-1204:fix multi statement issue 
Type:  
  BUG
Influences：  
   fix xx
> inner-1204:fix multi statement issue

- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/ShardingStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticTxEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
  BUG inner 1186
Type:  
  BUG
Influences：  
   SQL statistical adjustment
> SQL statistical adjustment

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
  BUG inner-1160:fix CancelledKeyException
Type:  
  BUG
Influences：  
   io
> inner-1160:fix CancelledKeyException

- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
Reason:  
  BUG inner-1211/inner-1212
Type:  
  BUG
Influences：  
fix: unlock should be after return the packet
> fix: unlock should be after return the packet

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/BeginHandler.java
- src/main/java/com/actiontech/dble/server/handler/RollBackHandler.java
- src/main/java/com/actiontech/dble/server/parser/AbstractServerParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/statistic/SqlLog.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/ShardingStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticDisruptor.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticFrontendSqlEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/entry/StatisticTxEntry.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
  BUG cherry pick from pr: 2745、2742、2741、2729、2724
Type:  
  BUG
Influences：  
   fix xx
> fix:SQL statistics bugs(cherry pick from master)

- src/main/java/com/actiontech/dble/memory/unsafe/utils/JavaUtils.java
- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
- src/main/java/com/actiontech/dble/statistic/sql/UsageData.java
- src/main/java/com/actiontech/dble/statistic/sql/UsageDataBlock.java
Reason:  
  BUG inner 1223、1225
Type:  
  BUG
Influences：  
   fix: Observers statistical queue related bugs
> fix: Observers statistical queue related bugs

- src/main/java/com/actiontech/dble/memory/unsafe/utils/JavaUtils.java
Reason:  
  BUG inner 1223
Type:  
  BUG
Influences：  
   fix xx
> Cannot be zero

- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
Reason:  
  BUG 1225
Type:  
  BUG
Influences：  
   fix:the closing logic is not as expected(cherry pick inner 1225)
> fix:the closing logic is not as expected(cherry pick inner 1225)

- src/main/java/com/actiontech/dble/plan/optimizer/SubQueryPreNoTransformProcessor.java
Reason:  
  BUG inner 1165
Type:  
  BUG
Influences：  
  fix  sub query too much rows inner 1165
> fix  sub query too much rows inner 1165

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/NormalServiceTask.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner-1234:move beforeHandlingTask to prevent NPE when using multiPacket .
Type:  
  BUG
Influences：  
   trace +Statistic
> inner-1234:move beforeHandlingTask to prevent NPE when using multiPacket .

- src/main/java/com/actiontech/dble/plan/optimizer/SubQueryPreProcessor.java
Reason:  
  BUG inner-1187: fix error when a column contains a subquery
Type:  
  BUG
Influences：  
   the scenario that contains subqueries
> inner-1187: fix error when column  contains subquery

- docker-images/dble-image/mgr/bootstrap.cnf
- docker-images/dble-image/quick-start/bootstrap.cnf
- docker-images/dble-image/rwSplit/bootstrap.cnf
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  turn Parallel Collector to CMS Collector
> turn Parallel Collector to CMS Collector

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPool.java
Reason:  
  BUG inner-894/inner-1226
Type:  
  BUG
Influences：  
fix: adjust the order of fixField and modify dble_thread_pool
> fix: adjust the order of fixField and modify dble_thread_pool

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/CloseServiceTask.java
- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  inner-960-improve: adjuct log in gracelful close scenarios.
Type:  
  Improve  
Influences：  
   log
> inner-960-improve: adjuct log in gracelful close scenarios.

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/OwnThreadDMLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OrderByHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/groupby/DirectGroupByHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/groupby/directgroupby/GroupByBucket.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/NotInHandler.java
Reason:  
  BUG #inner 1239.
Type:  
  BUG
Influences：  
  avoid thread remaining for group by
> inner-1239:avoid thread leaking for group by

- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  deal with property inner 920
> deal with property inner 920

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG inner-1248: adjust maxCon if maxCon is less than minCon
Type:  
  BUG
Influences：  
   config init
> inner-1248: adjust maxCon if maxCon is less than minCon

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOReactor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG bugfix :fix some NPE when concurrent close happens.
Type:  
Influences：  
   fix xx
> 🐛  :fix some NPE when concurrent close happens.

- src/main/java/com/actiontech/dble/meta/PauseEndThreadPool.java
Reason:  
  BUG inner-1102
Type:  
  BUG
Influences：  
fix: pause thread leak
> fix: pause thread leak

- src/main/java/com/actiontech/dble/server/response/Ping.java
Reason:  
  BUG inner-1244:fix connection.isValid() cause error
Type:  
  BUG
Influences：  
   fix xx
> inner-1244:fix connection.isValid() cause error

- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner 920
Type:  
  /Improve  
Influences：  
  fix check all parameter
> fix check all parameter

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MysqlCreateViewHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MysqlDropViewHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/log/transaction/TxnLogHelper.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidImplicitCommitParser.java
Reason:  
  BUG inner 853
Type:  
  BUG
Influences：  
   adjust the tx record
> adjust the tx record

- src/main/java/com/actiontech/dble/net/mysql/AuthPacket.java
- src/main/java/com/actiontech/dble/net/mysql/AuthSwitchRequestPackage.java
- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
- src/main/java/com/actiontech/dble/net/mysql/EOFPacket.java
- src/main/java/com/actiontech/dble/net/mysql/EOFRowPacket.java
- src/main/java/com/actiontech/dble/net/mysql/ErrorPacket.java
- src/main/java/com/actiontech/dble/net/mysql/ExecutePacket.java
- src/main/java/com/actiontech/dble/net/mysql/FieldPacket.java
- src/main/java/com/actiontech/dble/net/mysql/HandshakeV10Packet.java
- src/main/java/com/actiontech/dble/net/mysql/LongDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/MySQLPacket.java
- src/main/java/com/actiontech/dble/net/mysql/OkPacket.java
- src/main/java/com/actiontech/dble/net/mysql/PingPacket.java
- src/main/java/com/actiontech/dble/net/mysql/PreparedOkPacket.java
- src/main/java/com/actiontech/dble/net/mysql/QuitPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RequestFilePacket.java
- src/main/java/com/actiontech/dble/net/mysql/ResetConnectionPacket.java
- src/main/java/com/actiontech/dble/net/mysql/ResetPacket.java
- src/main/java/com/actiontech/dble/net/mysql/ResultSetHeaderPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
Reason:  
  BUG inner-1252: add default method for buffer write
Type:  
  BUG
Influences：  
   write EOF packet
> inner-1252: add default method for buffer write

- src/main/java/com/actiontech/dble/services/manager/information/views/SqlLogByTxDigestByEntryByUser.java
Reason:  
   Improve #inner 1220.  
Type:  
  Improve  
Influences：  
  stable results for sql_log_by_tx_digest_by_entry_by_user
> inner 1220 - stable results for sql_log_by_tx_digest_by_entry_by_user

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix load data incomplete data import of multiple nodes inner 1256
> fix load data incomplete data import of multiple nodes inner 1256

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  Improve inner-1262&1259: add some btrace point
Type:  
  Improve
Influences：  
   btrace
> inner-1262&1259: add some btrace point

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/DbleStartup.java
- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/ZkSender.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/ZktoXmlMain.java
- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix zk starts the process inner 1243
> fix zk starts the process inner 1243

- src/main/java/com/actiontech/dble/btrace/provider/ClusterDelayProvider.java
- src/main/java/com/actiontech/dble/cluster/general/response/DbGroupHaResponse.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/xmltozk/listen/DbGroupStatusToZkLoader.java
Reason:  
  Improve inner-1253-btrace: add some btrace point
Type:  
  Improve  
Influences：  
   btrace
> inner-1253-btrace: add some btrace point

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  Improve inner-1263: adjust the timing of tracing backendResponse time
Type:  
  Improve
Influences：  
   time cost
> inner-1263: adjust the timing of tracing backendResponse time

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG inner 1264
Type:  
  BUG 
Influences：  
   fix: cannot find view with schema
> fix: cannot find view with schema

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnections.java
Reason:  
  BUG inner-1262&1259: filter changeUserService and authService in some manage command
Type:  
  BUG
Influences：  
   fix xx
> inner-1262&1259: filter changeUserService and authService in some manage command

- src/main/java/com/actiontech/dble/plan/common/item/function/sumfunc/ItemFuncGroupConcat.java
Reason:  
  BUG #inner 1220.
Type:  
  BUG 
Influences：  
  fix bug about group_concat order by
> fix bug about group_concat order by

- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner-1271
Type:  
  BUG
Influences：  
fix: reference startExecuteBackend method
> fix: reference startExecuteBackend method

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/OwnThreadDMLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeAndOrderHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HeapItem.java
Reason:  
  BUG #inner 1997
Type:  
  BUG 
Influences：  
  fix MultiNodeMergeAndOrderHandler ownThread leak
> inner-1997 : fix MultiNodeMergeAndOrderHandler ownThread leak

- src/main/java/com/actiontech/dble/backend/mysql/view/FileSystemRepository.java
- src/main/java/com/actiontech/dble/backend/mysql/view/KVStoreRepository.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/ZkSender.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG 
Type:  
  BUG  
Influences：  
  fix  zk view initialization failed inner 1243
> fix  zk view initialization failed inner 1243

- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/util/LongUtil.java
- src/main/java/com/actiontech/dble/util/NameableExecutor.java
Reason:  
  BUG inner-1260/inner-1226
Type:  
  BUG
Influences：  
fix: error message adjustment/sync map
> fix: error message adjustment/sync map

- src/main/java/com/actiontech/dble/route/function/PartitionByJumpConsistentHash.java
Reason:  
  Improve inner-1272: change default value of jumpStringHash
Type:  
  Improve
Influences：  
  jumpStringHash
> inner-1272: change default value of jumpStringHash

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner-1270/inner-1271
Type:  
  BUG
Influences：  
fix: reference startExecuteBackend method/NPE
> fix: reference startExecuteBackend method/NPE

- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/GetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowShardingNode.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix shardingNode have fake dbGroup need to start failure inner 1265
> fix shardingNode have fake dbGroup need to start failure inner 1265

- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/GetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowShardingNode.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> cherry pick from pr(2799)  and fix shardingNode have fake dbGroup need to start failure inner 1265 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MysqlCreateViewHandler.java
Reason:  
  BUG inner 1279
Type:  
  BUG
Influences：  
   fix: lost connection occurs when creating (mysql) view
> fix: lost connection occurs when creating (mysql) view

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  cherry pick from pr(2686)
cherry pick from pr(2779)
> cherry pick from pr amd fix load data  incorrect execution result 

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
Type:  
Influences：  
   add issue-1231 related btrace breakpoint(for regression testing)
> add issue-1231 related btrace breakpoint(for regression testing)

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix zk create view not have view lock inner 1281
> fix zk create view not have view lock inner 1281

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG 
Type:  
  BUG
 
> cherry pick from pr(2804) and fix zk create view not have view lock inner 1281 

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG inner-1289
Type:  
  BUG
Influences：  
fix: remove the empty judgment of sharding
> fix: remove the empty judgment of sharding

- src/main/java/com/actiontech/dble/singleton/FlowController.java
Reason:  
  BUG inner 1288
Type:  
  BUG
Influences：  
   flow control exceptions try catch handling
> flow control exceptions try catch handling

- src/main/java/com/actiontech/dble/singleton/TsQueriesCounter.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix management execution sql will have conversion errors inner 1293
> fix management execution sql will have conversion errors inner 1293

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix  npe  when zk fisrt start  inner 1292

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOReadHandler.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOWriteHandler.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/CloseServiceTask.java
- src/main/java/com/actiontech/dble/net/service/CloseType.java
- src/main/java/com/actiontech/dble/net/service/ServiceTaskFactory.java
Reason:  
  BUG inner-1291:normally close if write error & interval check close timeout
Type:  
  BUG
Influences：  
  close
> inner-1291:normally close if write error & interval check close timeout

- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
Reason:  
  BUG inner-1296
Type:  
  BUG
Influences：  
fix: requests are evenly distributed to io threads
> fix: requests are evenly distributed to io threads

- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
Reason:  
  BUG inner-1296
Type:  
  BUG
Influences：  
fix: requests are evenly distributed to io threads
> fix: requests are evenly distributed to io threads(cherry-pick)

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG #2819/inner-1298
Type:  
  BUG
Influences：  
fix: modify the status of the backend
> fix: modify the status of the backend

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:
  BUG #2819/inner-1298
Type:
  BUG
Influences：
fix: modify the status of the backend
> fix: modify the status of the backend(cherry-pick)

- .gitignore
- pom.xml
Reason:  
  Improve inner-1300:replace from copyResource.sh to maven profile
Type:  
  Improve
Influences：  
develop
> inner-1300:replace from copyResource.sh to maven profile

- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/services/manager/response/FlowControlList.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   fix buffer bug and wrong log
> buffer bug and wrong log

- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
Reason:  
  BUG inner-1345
Type:  
  BUG
Influences：  
fix: sorting to eliminate thread interference
> fix: sorting to eliminate thread interference

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/cluster/general/response/BinlogPauseStatusResponse.java
- src/main/java/com/actiontech/dble/cluster/general/response/ConfigStatusResponse.java
- src/main/java/com/actiontech/dble/cluster/general/response/DdlChildResponse.java
- src/main/java/com/actiontech/dble/cluster/general/response/SequencePropertiesLoader.java
- src/main/java/com/actiontech/dble/cluster/general/response/XmlDbLoader.java
- src/main/java/com/actiontech/dble/cluster/general/response/XmlShardingLoader.java
- src/main/java/com/actiontech/dble/cluster/logic/BinlogClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/ConfigClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/DDLClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/MetaClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/OnlineClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/PauseResumeClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/values/DDLInfo.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/listen/BinlogPauseStatusListener.java
- src/main/java/com/actiontech/dble/route/handler/HintDbInstanceHandler.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/server/parser/AbstractServerParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
  Improve #inner 1284.  
Type:  
  Improve  
Influences：  
  add log for manager command
> inner 1284 - add log for manager command

- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG #2611
Type:  
  BUG 
Influences：  
   fix childtable finish route
> #2611 child table no need finish route

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
Reason:  
   Improve  
Type:  
   Improve  
Influences：  
   tryRouteInsertQuery and  parserNoSharding is duplicated
> tryRouteInsertQuery and  parserNoSharding is duplicated

- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
Reason:  
   Improve inner-1114-supplement: add command to show @@help
Type:  
  Improve  
Influences：  
  show @@help
> inner-1114-supplement: add command to show @@help

- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBlacklist.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
  rw support blacklist inner 1224
> rw support blacklist inner 1224

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner-1365&1364:1. ha command should detached ,too. 2. resolve pause hang when detached
Type:  
  BUG
Influences：  
   cluster detach
> inner-1365&1364&1366:1. ha command should detached ,too. 2. resolve pause hang when detached

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFlowControl.java
- src/main/java/com/actiontech/dble/services/manager/response/FlowControlList.java
Reason:  
  BUG inner 1367
Type:  
  BUG 
Influences：  
   fix npe
> inner 1367

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  BUG #inner 1361.
Type:  
  BUG
Influences：  
  fix that some manager command doesn't support comment
> inner 1361 - fix that some manager command doesn't support comment

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix some unsupported manager command due to inner#1284
> fix some unsupported manager command due to inner#1284

- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
  BUG inner 1306
Type:  
  BUG
Influences：  
   fix: connection failed during handshake phase did not count 'totalConnections' correctly
> fix: connection failed during handshake phase did not count 'totalConnections' correctly

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  Improve inner-1376&1378 RoutePenetration support
Type:  
  Improve  
Influences：  
   RoutePenetration
> RoutePenetration support

- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
intellij prompt optimization
> style: intellij prompt optimization

- pom.xml
- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FileNioMapped.java
- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
- src/main/java/com/actiontech/dble/route/util/PropertiesUtil.java
- src/main/java/com/actiontech/dble/util/DateUtil.java
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
  support jdk 11 in maven
> support jdk 11 in maven

- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FilePath.java
Reason:  
  BUG inner 1275
Type:  
  BUG
Influences：  
   fix NPE
> resolve NPE

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  BUG inner-1376-supplement:  1.change part match to full match.2. add log
Type:  
  Bug  
Influences：  
  change part match to full match
> inner-1376-supplement:  1.change part match to full match.2. add log

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 1382
Type:  
  BUG 
Influences：  
   fix xx
> inner 1382

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionAuthenticator.java
- src/main/java/com/actiontech/dble/btrace/provider/ClusterDelayProvider.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOReactor.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
Reason:  
  BUG 
Type:  
  BUG  
Influences：  
  fix heartbeat deadlock inner  1372
> fix heartbeat deadlock inner  1372

- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  Improve inner-1376-supplement:  change format to json
Type:  
  Improve  
Influences：  
  route-penetration-match
> inner-1376-supplement:  change format to json & inner-1386: bug fix[ treat line-break as normal character]

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  Bug inner-1387: fix closeTimeout doesn't set
Type:  
  BUG
Influences：  
   fix xx
> inner-1387: fix closeTimeout doesn't set

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BtraceClusterDelay.java
- src/main/java/com/actiontech/dble/meta/ReloadLogHelper.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/meta/table/ConfigTableHandler.java
Reason:  
Type:  
Influences：  
   fix xx
> provides new btrace breakpoint

- src/main/java/com/actiontech/dble/server/util/SetItemUtil.java
Reason:  
  BUG #2873
Type:  
  BUG 
Influences：  
   fix set autocommit=true
> Set problem #2873

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  BUG inner-1390: change property from boolean to int& add more log& inner-1393: avoid json cast string to boolean
Type:  
  BUG
Influences：  
   route Penetration
>  inner-1390: change property from boolean to int& add more log& inner-1393: avoid json cast string to boolean

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  BUG inner-1387: fix closeTimeout doesn't set
Type:  
  BUG
Influences：  
   fix xx
> cherry-pick:inner-1387: fix closeTimeout doesn't set

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseStart.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/ClusterManageHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DatabaseHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/FlowControlHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/FreshBackendConnHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/StartHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ReleaseReloadMetadata.java
- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEvents.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
Reason:  
   Improve inner# 1284.  
Type:  
  Improve  
Influences：  
  support comment for some manager command
> support comment for some manager command

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  BUG inner-1394: report warn if set -1 to property enableRoutePenetration
Type:  
  BUG
Influences：  
  enableRoutePenetration
> inner-1394: report warn if set -1 to property enableRoutePenetration

- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQL.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
 fix manager sql error inner 1381
> fix manager sql error inner 1381

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/singleton/ProxyMeta.java
Reason:  
  BUG #inner 1351.
Type:  
  BUG
Influences：  
  update reloading timestamp after reload @@metadata
> inner 1351 - update reloading timestamp after reload @@metadata

- src/main/java/com/actiontech/dble/btrace/provider/IODelayProvider.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:  
  Improve: inner-1308: add btrace point
Type:  
  Improve  
Influences：  
   fix xx
> inner-1308: add btrace point

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionAuthenticator.java
- src/main/java/com/actiontech/dble/btrace/provider/ClusterDelayProvider.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
fix name
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   delete unnecessary code and fix missing lastSendQryTime  inner  1402
> delete unnecessary code and fix missing lastSendQryTime  inner  1402

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  enhanced create syntax in manager command
> enhanced create syntax in manager command

- pom.xml
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  fix that errorprone is slow
> fix that errorprone is slow

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterTableParser.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
  
> support partitioning operations sql inner 1313

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/singleton/ProxyMeta.java
Reason:  
  BUG inner 1400
Type:  
  BUG
Influences：  
   fix :resolve residual scheduled tasks
> resolve residual scheduled tasks

- pom.xml
Reason:  
  BUG inner-1408: fix multi log4j binding
Type:  
  BUG
Influences：  
   fix xx
> inner-1408: fix multi log4j binding

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/meta/table/ConfigTableHandler.java
- src/main/java/com/actiontech/dble/meta/table/DefaultNodeTableHandler.java
- src/main/java/com/actiontech/dble/meta/table/ModeTableHandler.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:
  BUG inner 1392、1395
Type:
  BUG
Influences：
   fix：1、An alarm is generated when tables are inconsistent during startup
   2、Optimization hints
> An alarm is generated when tables are inconsistent

- src/main/java/com/actiontech/dble/cluster/logic/DDLClusterLogic.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/SchemaConfig.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/AbstractSchemaMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/AbstractTableMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/DDLNotifyTableMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/SchemaInitMetaHandler.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:
  BUG inner 1407、1405
Type:
  BUG
Influences：
   fix：1、metadata loading requires a re-election of columns
2、reload does not take effect after ‘function’ or ‘sqlMaxLimit’ is modified
> reload problem

- pom.xml
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  remove resource in pom.xml
> remove resource in pom.xml

- src/main/java/com/actiontech/dble/btrace/provider/ClusterDelayProvider.java
- src/main/java/com/actiontech/dble/cluster/logic/AbstractClusterLogic.java
Reason:  
  Improve:inner-1414:add btrace point
Type:  
  Improve  
Influences：  
  
> inner-1414:add btrace point
