- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
Reason: 
mark falsely the role of sharding server.
type:
debug
Influences:
heartbeat detect and the relation of master and slave
> #264, mark exactly the role of sharding server

- src/main/java/com/actiontech/dble/manager/response/KillConnection.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
Reason:
  the 'kill @@connection' only cut off the frontend connection & the backend query is still running,when slow query occurred there has no effective order to stop the backend query
Type:
  Improvement
Influences：
  Send kill processlist_id to backend connection when the manager port send the kill command to dble(record can be find in general log)
  Ddl query wouldn't be killed by 'kill @@connection'
  Connection with a XA transaction can not be canceled wouldn't be killed
>  #276 Kill @@connection send kill command to backend connection

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:
don't get file name when quote characters for file name and other fields are different.
don't get exact value when enclose character is not whitespace.
Type:
   Improvement
Influences：
load data infile statement.
> #242, fix defect, file name parse and value parse

- src/main/java/com/actiontech/dble/manager/ManagerConnection.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
Reason:
  the manager connection should also be closeable 
Type:
  Improvement
Influences：
  kill @@ connection can kill the manager connection
> #276 kill connection about managerConnection

- src/main/java/com/actiontech/dble/net/handler/FrontendAuthenticator.java
Reason:
  when use customized keepalived to TCP check the server ,the server would ask client to login instead  of  return OK packet
Type:
  Improvement
Influences：
  will return OK when use the  customized keepalived to check TCP
> #279 Error when Configure TCP_CHECK in keepalived.conf

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AbstractCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
Reason:
  `prepare` one of the nodes on sharding table failed,xa transaction hangs
Type:  
  Bug fix
Influences：  
  Add lock when send the xa command 
  If the connection is closed when the 'prepare' command is sending ,rollback this xa transaction
> #289 fix the error handling when xa transaction error in prepare

- src/main/java/com/actiontech/dble/net/handler/FrontendAuthenticator.java
Reason:
   The strict plugin type check would cause some mysql connecter can't connect correctly
Type:
   Bug fix
Influences:
   Would not check the plugin when the authPacket did not specify the plugin type
> #292 do not check the plugin if the authPacket use the default one

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:
  When prepare failed ，rollbackHandler try to get a new connection of mysql,and will wait until the connection acquired.That whould cause the rollbackHandler hanging when the mysql server is crashed down
Type:
  Bug fix
Influences：
  Change the behavior of get a new connection 
  If not rollback successfully,try to rollback for several times
> Issue-289 fix the error handling when xa transaction error in prepare

- src/main/java/com/actiontech/dble/config/Versions.java
- src/main/java/com/actiontech/dble/server/ServerSptPrepare.java
- src/test/java/com/actiontech/dble/parser/ServerParseTest.java
- version.txt
Reason:
when prepare statement is from user variable, eg. prepare stmt from @stmt1, we get two level quote in the
constructed statement, because @stmt1 is primordial.
Type:  
fix
Influences：  
prepare
> fix repeat quotes

- src/main/java/com/actiontech/dble/server/response/SptExecute.java
Reason:
don't make up script execute statement when statement contain multi variables
Type: 
fix
Influences：  
execute statment in script
> fix, don't make up script execute statement

- src/main/java/com/actiontech/dble/config/Versions.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- version.txt
Reason: 
when the first key is incorrect， the parser skips it and continues parseing. 
eg. 
shsh create table xxx(a int, b char(32))；
when the statement was parse, the shsk will be skiped, the actual result is executing：
create table xxx(a int, b char(32))；
This is wrong. The bug was brought in from the commit ff7f9160acff462fdc02bae9e6f2cf99c5fb1dc0 in mycat. But I don't find the reason and a statement that should be parsed by the way. Maybe the writer only get to the root of the matter. I just fix it.
Type:  fix
Influences：  
all statement.
> fix incorrect key being ignored

- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
Reason:
dble must restart if db sequence don't been set.
Type:  bug
Influences：  
global sequence in db mode
> fix, must restart if not setting

- src/main/java/com/actiontech/dble/server/ServerSptPrepare.java
Reason:
the method HashMap.replace  is a new methon in java 1.8. So useing jre 1.7 will throw a runtime exception that don't be catch. 
Type:  bug
Influences：  
script prepare statement
> #387, jvm version incompatibility about HashMap.replace

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
- src/main/java/com/actiontech/dble/server/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParseShow.java
- src/main/java/com/actiontech/dble/server/response/ShowCreateView.java
Reason:
  In `view`,The return messages of unsupported syntax and wrong syntax are not accurate
Type:  
  Improve #363   
Influences：  
  Add 'show create view' support
  Improve the error message when the create view sql is not correct
> #363 fix and show create view support

- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:
  the view use in subquery would be identified as nosharding table
Type:  
  Bug #375 
Influences：  
  Add nosharding conditions whether the tableName is a viewName
> Error when `subquery ` contains `view`

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:
Bug #411
Type:  
Bug fix 
Influences：  
Default dataHostWithoutWH set to true,only set false when the dataHosts is not empty
> #411 Dble can not startup when the schema.xml is almost empty

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:
  Bug  when the config incomplete Cluster online miss
Type:
  Bug fix
Influences：
  Set online ever if the config is incomplete
> ucore online init when the config is incomplete

- src/main/java/com/actiontech/dble/manager/response/ShowCache.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/manager/response/ShowSQL.java
- src/main/java/com/actiontech/dble/manager/response/ShowSQLHigh.java
- src/main/java/com/actiontech/dble/manager/response/ShowSQLLarge.java
- src/main/java/com/actiontech/dble/manager/response/ShowSQLSlow.java
- src/main/java/com/actiontech/dble/manager/response/ShowSQLSumTable.java
- src/main/java/com/actiontech/dble/manager/response/ShowSQLSumUser.java
- src/main/java/com/actiontech/dble/manager/response/ShowServer.java
- src/main/java/com/actiontech/dble/manager/response/ShowTime.java
Reason:
  Python execute manager sql  would get error when the result set has timestamp
Type:
  BUG
Influences：
  show @@cache
  show @@server
  show @@sql.slow
  show @@sql.high
  show @@sql.large;
  show @@sql.sum.table
  show @@connection.sql
  show @@sql.sum.table
  show @@time.current
  show @@sql.sum.user
> #569 change timestamp type from long to string

- src/main/java/com/actiontech/dble/backend/ConMap.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
Reason:
  Improve #607
Type:
  Improve
Influences：
  BackendConnection with schema == null can be returned to pool
  When heartbeat need a backendConnection would get connection form pool
> #609 connection with schema == null can be manager by pool

- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
Reason:
  Bug #651
Type:
  Bug
Influences：
  Add ` check before set to the PlanNode
> #651 Complex query with table alias will cause error when has `

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:
  Bug #647
Type:
  Bug
Influences：
  resume Syntax limit to command "resume"
> #647 resume Syntax limit

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #649 
Type:  
  BUG 649
Influences：  
   hint ddl no longer update the table meta
> #649 hint ddl no longer update the table meta

- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQL.java
Incorrect result on `show @@connection.sql`.`EXECUTE_TIME` when the execution time of query<1ms 
Reason:  
  BUG #785
Type:  
  BUG
Influences：  
  fix sql execution time is incorrect when execution time less than 1ms
> `show @@connection.sql`.`EXECUTE_TIME` is incorrect

- src/main/java/com/actiontech/dble/backend/ConMap.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/GetConnectionHandler.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG #822
Type:  
  BUG  
Influences：  
   When the maxCon limit than connection pool initValue max(minCon,(database+1))  
   maxCon would set as initValue and print a warning log   
   maxCon is less than the initSize of dataHost:" + initSize + " change the maxCon into
> Issue 822 some `datanodes` cannot be connectted when `macCon` <= the number of `datanode`

- src/main/java/com/actiontech/dble/config/loader/zkprocess/comm/ZkConfig.java
Reason:  
  BUG #766
Type:  
  BUG  
Influences：  
   ZK config use only ipAddress in myid.properties as connect url
> #766 when use zk ipAddress can be config as url

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/ClusterUcoreSender.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UOffLineListener.java
- src/main/java/com/actiontech/dble/server/status/OnlineLockStatus.java
Reason:  
  BUG #Inner 151
Type:  
  BUG
Influences：  
   Change online key/value into timestamp,only waiting for the same timestamp,when the timestamp changed,the cluster option do not wait for this one
> Inner 151 change online key/value when use ucore cluster

- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG #899 
Type:  
  BUG
Influences：  
   get detail error when explain sql can not be parsed by druid
> #899 get detail error when explain sql can not be parsed by druid

- src/main/java/com/actiontech/dble/meta/table/GetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/meta/table/GetSchemaDefaultNodeTablesHandler.java
- src/main/java/com/actiontech/dble/meta/table/GetSpecialNodeTablesHandler.java
Reason:  
  BUG #984
Type:  
  BUG
Influences：  
   fix logic
If a physical datanode has no tables.
This may happen:
AbstractTablesMetaHandler ->listExistTables
thread 1:
before lock,
switch to thread 2.
thread 2:
GetNodeTablesHandler->onResult
finished = true;
switch to thread 1.
thread 1:
listExistTables return &countdown()
multiTablesMetaHandler.countDownShardTable()
and at the same time,thread 2:
handleFinished->GetSpecialNodeTablesHandler->handleFinished()
handlerTable->multiTablesMetaHandler.checkTableConsistent()
so thread1 and thread2 will may modify a same list
> pr for bug #984

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/NoNameNodeHandlerBuilder.java
Reason:  
  BUG #989
Type:
  BUG
Influences：
   fix when in transaction,global table has use a random node,next select query will use the same node
> #989 global table switch back conn in transaction for complex query

- src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java
Reason:  
  BUG #1001 
Type:  
  BUG 
Influences：  
   fix resetNoShardNode,if parent's first nosharing table is null, the parent nosharing table will same to second child
>  #1001 change resetNoShardNode

- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
Reason:  
  Improve #944
Type:  
  Improve  
Influences：  
  modify prompt when the 'reload @@metadata' statement format is wrong
> modify prompt when the 'reload @@metadata' statement format is wrong

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG #968 
Type:  
  BUG  
Influences：  
   table in multi-schema subquery can be correctly identified
   `select * from schema1.test1 where id <(select id from testtable where id > 5)`
> #968 table in multi-schema subquery can be correctly identified

- src/main/java/com/actiontech/dble/cache/impl/RocksDBPool.java
Reason:  
  BUG.  
Type:  
  BUG 
Influences：  
  miss cache although data has been put in RocksDB cache
> miss cache although data has been put in RocksDB cache

- pom.xml
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/meta/table/DbleCreateTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidLockTableParser.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
   Improve #788 and  Improve lock statement
Type:  
Influences：  
for #788 
* select * from test_shard where R_NAME=B'1000001';
* lock table test_shard write,test_no_shard write;   [limitation doc](https://github.com/actiontech/dble-docs-cn/blob/develop/3.SQL_Syntax/3.4_Transactional_and_Locking_Statements/3.4.1_Lock&unlock.md#3413-%E9%99%90%E5%88%B6)   
* CREATE TABLE aly_test(id int, data1 varchar(10),data2 varchar(10),data3 varchar(20) GENERATED ALWAYS as (concat(data1,' ',data2))) ;（insert still have problem）
* CREATE TABLE aly_test (id int, data varchar(10), FULLTEXT INDEX idn_id (data));
> Issue druid1.1.14

- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
Reason:  
  BUG #1053
Type:  
  Improve  
Influences：  
   when join filter refers to one node and the table‘s left node is not a simple  table, the tip is not correct
> the tip for #1053

- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
Reason:  
  BUG #1057. 
Type:  
  BUG
Influences：  
  explain got different result when "join" between ER tables whether use uppercase as table alias
> explain got different result when "join" between ER tables whether use uppercase as table alias

- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceTimeHandler.java
Reason:  
  BUG #1063.
Type:  
  BUG
Influences：  
  check whether start time is over than dble start time when global sequence is generated by timestamp
> check that start time is over than dble start time when global sequence is generated by timestamp

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG #1070 
Type:  
  BUG  
Influences：  
   Remove connection for queue even the schema is null
> #1070 remove connection for queue even the schema is null

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  Improve error tips when using correlated subquery in the SELECT clause
Type:  
Influences：  
   fix #1087 
Test:
After this commit, 
```
mysql> SELECT COUNT(*) AS TEMP2,
->        (SELECT COUNT(*)
->           FROM TK_TEST s
->          WHERE MONTH(s.SENDING_DATE) = MONTH(t.SENDING_DATE)
->        ) AS TEMP1
-> FROM TK_TEST t;
ERROR 1105 (HY000): Correlated Sub Queries is not supported
```
> fix #1087 Improve error tips when using correlated subquery in the SELECT clause

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/manager/response/ShowTableAlgorithm.java
- src/main/java/com/actiontech/dble/manager/response/ShowTableDataNode.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
  Improve #1086 .
Type:  
  Improve
Influences：  
The affected statement and compatible with no apostrophe:
1. show @@dataNodes where schema='?' and table='?'
2. show @@algorithm where schema='?' and table='?'
3. kill @@ddl_lock where schema='?' and table='?'
> support apostrophe in statement that contains 'where schema=? and table=?'

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #1124. 
Type:  
  BUG
Influences：  
  when buffer is full, dble doesn't set index
> #1124 - when buffer is full, dble doesn't reset buffer

- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
Reason:  
  BUG #1162. 
Type:  
  BUG
Influences：  
  `zk` allow both uppercase and lowercase in the file of sequence_distributed_conf.properties
> #1162 - `zk` allow both uppercase and lowercase in the file of sequence_distributed_conf.properties

- src/main/java/com/actiontech/dble/DbleServer.java
…hing xa logs
Reason:  
  BUG #1192
Type:  
  BUG
Influences：  
   fix #1192
> #1192 Fail to recover XA Transaction on startup when xa log is not flushed and server is down

- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
Reason:  
  BUG #1185.
Type:  
  BUG
Influences：  
  illegal value in sequence_distributed_conf.properties
> #1185 - illegal value in sequence_distributed_conf.properties

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG https://github.com/actiontech/dble/issues/1182  
Type:  
  BUG  
Influences：  
   fix the bug when the character of enclosed by is ''
> #1182 Load data will cause exception when the column content only has one '"' at the begining

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACheckHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
Reason:  
  BUG #1160. 
Type:  
  BUG
Influences：  
  XACheckHandler#checkXid pass wrong parameters to SQLJob's constructor
> #1160 - XACheckHandler#checkXid pass wrong parameters to SQLJob's constructor

- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceTimeHandler.java
Reason:  
  BUG #1190. 
Type:  
  BUG
Influences：  
  avoid clock moved backwards in case of global sequence generated by zk
> #1190 - avoid clock moved backwards in case of global sequence generated by zk

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
Reason:  
  BUG #1204
Type:  
  BUG  
Influences：  
   Response to the handler when the connection is already closed
> #1204 response to the handler when the connection is already closed

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #1144. 
Type:  
  BUG
Influences：  
  packetId thread safety because connectionClose execute before errorResponse
> #1144 - packetId thread safety because connectionClose execute before errorResponse

- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
Reason:  
  BUG #1171
Type:  
  BUG  
Influences：  
   change the buffer QUIT_PACKET check，ByteBuffer in dble is all DirectByteBuffer,so the check function can not use the buffer.array() to get the data
> #1171 change the buffer QUIT_PACKET check

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG #1125. 
Type:  
  BUG  
Influences：  
  DateNode Idle Check Thread failed to fill empty datasource when dataHost's minCon is less than database size
> DateNode Idle Check Thread failed to fill empty datasource when dataHost's minCon is less than database size

- docker-images/quick-start/server.xml
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/FrontendUserManager.java
- src/main/resources/server_template.xml
Reason:  
  Improve #1218.  
Type:  
  Improve  
Influences：  
  dble don't limit the number of user frontend connection by default
> #1218 - dble don't limit the number of user frontend connection by default

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FetchStoreNodeOfChildTableHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/UnLockTablesHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/FetchMySQLSequenceHandler.java
- src/main/java/com/actiontech/dble/sqlengine/MultiSQLJob.java
- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
  BUG .  
Type:  
  BUG
Influences：  
  replace method close to closeWithoutRsp in case of multi statement failure before statement that user need to execute
> replace method close to closeWithoutRsp

- pom.xml
Reason:  
  Improve #1266 
Type:  
  Improve  
Influences：  
  avoid to override last gc log when DBLE restarts
> modify param of gc log

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1250.
Type:  
  BUG
Influences：  
  ignore enclose char when using load data
> #1250 - ignore enclose char when using load data

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  Improve #1264.  
Type:  
  Improve  
Influences：  
  avoid npe when resources is cleared
> in lock tables, avoid npe when resources is cleared

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
- src/main/java/com/actiontech/dble/manager/response/ShowBackendOld.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/manager/response/ShowSession.java
- src/main/java/com/actiontech/dble/manager/response/ShowXASession.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  Improve #1342 .  
Type:  
  Improve  
Influences：  
  unify column name that contains connection id in manager cmd and log
> #1342 - unify column name that contains connection id in manager cmd and log

- src/main/java/com/actiontech/dble/cluster/listener/ClusterOffLineListener.java
log call stack when it catch an exception
Reason:  
It is IMPOSSIBLE to analyze because of the absence of call stack in dble.log .
Type:  
Improve  
Influences：  
If there is an exception, the call stack will be print in dble.log.
> Let ClusterOffLineListener.java log call stack when it meets exception in master

- src/main/java/com/actiontech/dble/cluster/listener/ClusterOffLineListener.java
log call stack when it catch an exception
Reason:  
  It is IMPOSSIBLE to analyze because of the absence of call stack in dble.log .
Type:  
  Improve  
Influences：  
  If there is an exception, the call stack will be print in dble.log.
> Let ClusterOffLineListener.java log call stack when it meets exception in 2.19.03.1/rel

- src/main/java/com/actiontech/dble/cluster/listener/ClusterOffLineListener.java
log call stack when it catch an exception
Reason:  
It is IMPOSSIBLE to analyze because of the absence of call stack in dble.log .
Type:  
Improve  
Influences：  
If there is an exception, the call stack will be print in dble.log.
> Let ClusterOffLineListener.java log call stack when it meets exception in 2.19.05.1/rel

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLConsistencyHelper.java
- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
  BUG #1286. 
Type:  
  BUG
Influences：  
  avoid dead loops in Timer executor when checking global table
> avoid dead loops in Timer executor when checking global table

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1380.
Type:  
  BUG
Influences：  
  can't lock table if user did nothing in transaction
> can't lock table if user did nothing in transaction

- src/main/java/com/actiontech/dble/cluster/AbstractClusterSender.java
- src/main/java/com/actiontech/dble/cluster/listener/ClusterOffLineListener.java
Reason:  
  BUG #Inner 230
Type:  
  BUG
Influences：  
   Use a ConcurrentHashMap to replace HashMap
   Add redundancy safe check for loop
> Inner-230 reload may block because of thread safe problem

- pom.xml
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1456
Type:  
  BUG
Influences：  
  load data terminated char is |||
> upgrade dependency of univocity-parsers, due to load data terminated char

- pom.xml
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1456.
Type:  
  BUG
Influences：  
  load data does't support to terminated String |||,only support char.
> upgrade dependency of univocity-parsers

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
Reason:  
  BUG #1321  
Type:  
  BUG  
Influences：  
   fix bug when the column name already has '` 'in
> #1321  bug fix

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG #1505 . 
Type:  
  BUG 
Influences：  
  fix backquote with or condition
eg：explain select `a`.`id`,`a`.`name` from  `shard1` `a` where a.id  = 3 or
a.id = 4 ORDER BY `a`.`name` ASC;
> fix backquote when use using() in statement

- pom.xml
- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  Brand new projects need LOAD DATA INFILE to improve their data importing,. Port backwards all known and resoloved issues for safety.
  This is a bundle of fixes for reinforce LOAD DATA INFILE, including issues belows from actiontech/dble :
* #1532
* #1198 
* #1182
* #1250 
* #1397 
Type:  
  BUG
Influences：  
* bug(s) fix only
* no new features
* no features modified
* version incremented, taged the version as 2.19.03.3 in pom.xml
> announce 2.19.03.3

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG #1528 
Type:  
  BUG  
Influences：  
   delete a double check of dataHost disable status, let it check at connection create call back
> #1528 disable dataHost may cause connection control error

- pom.xml
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/log/transaction/TxnLogProcessor.java
Reason:  
  security_alert [CVE-2019-17571](https://github.com/advisories/GHSA-2qrg-x229-3v8q)
Type:  
  security_alert
Influences：  
   fix security_alert
> remove security_alert log4j 1.2.17

- src/test/java/com/actiontech/dble/cluster/xmltoKv/XmlServerLoaderTest.java
unifiy package name of com.actiontech.dble.cluster.xmltoKv.
Reason:  
fix #1680  
Type:  
BUG
Influences：  
fix package name inconsistency between com.actiontech.dble.cluster.xmltoKv and com.actiontech.dble.cluster.xmlTokv
> fix #1680 on master

- src/test/java/com/actiontech/dble/cluster/xmltoKv/XmlServerLoaderTest.java
unifiy package name of com.actiontech.dble.cluster.xmltoKv.
Reason:  
fix #1680  
Type:  
BUG
Influences：  
fix package name inconsistency between com.actiontech.dble.cluster.xmltoKv and com.actiontech.dble.cluster.xmlTokv
> fix #1680 on 2.19.03/lts

- pom.xml
Reason:  
  Improve #1672 
Type:  
  Improve  
Influences：  
   Catch Throwable exception would not invalidate HeapDumpOnOutOfMemoryError & OnOutOfMemoryError
   In OpenJDK the HeapDumpOnOutOfMemoryError & OnOutOfMemoryError follow the order that OnOutOfMemoryError would be called after HeapDumpOnOutOfMemoryError finished. But no detailed description with OracleJDK
> #1672 add default JVM OOM config

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinNodeHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/BaseDMLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/DMLResponseHandler.java
Reason:  
  BUG #1706 
Type:  
  BUG  
Influences：  
   NestLoop may cause java.util.ConcurrentModificationException
> #1706 NestLoop may cause java.util.ConcurrentModificationException

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1454.  
Type:  
Influences：  
   dble reports error when columns don't contains sharding column in load data for sharding column.
> #1454 - dble reports error when columns don't contains sharding column in load data for sharding table.

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #1725 .
Type:  
  BUG 
Influences：  
  reuse other datanode conn of global table in singleNodeHandler
> #1725 - reuse other datanode conn of global table in singleNodeHandler

- src/main/java/com/actiontech/dble/server/OfflineStatusListener.java
Reason:  
  BUG inner453. 
Type:  
  BUG 
Influences：  
  if value of binlog pause status in zk is empty, dble report ArrayIndexOutOfBoundsException
> if value of binlog pause status in zk is empty, dble report ArrayIndexOutOfBoundsException

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/savepoint/SavePointHandler.java
Reason:  
  BUG from autotest
Type:  
  BUG 
Influences：  
   ` 
WARN [backendBusinessExecutor1] (com.actiontech.dble.backend.mysql.nio.handler.transaction.savepoint.SavePointHandler.connectionError(SavePointHandler.java:207)) - connection Error in savePointHandler, err:
java.lang.NullPointerException: null
at com.actiontech.dble.backend.mysql.nio.handler.transaction.savepoint.SavePointHandler.addSavePoint(SavePointHandler.java:148) ~[dble-9.9.9.9.jar:?]
at com.actiontech.dble.backend.mysql.nio.handler.transaction.savepoint.SavePointHandler.cleanAndFeedback(SavePointHandler.java:228) ~[dble-9.9.9.9.jar:?]
at com.actiontech.dble.backend.mysql.nio.handler.transaction.savepoint.SavePointHandler.okResponse(SavePointHandler.java:170) [dble-9.9.9.9.jar:?]
at …
> may NPException

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowTablesHandler.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
Reason:  
  BUG #1678 .
Type:  
  BUG 
Influences：  
  show tables from schema like 's%'
> correct column name when statement of show tables contains like clause

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1675
Type:  
  BUG
Influences：  
  last successful xa commit will stop background retry
> last successful xa commit will stop background retry

- pom.xml
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  https://github.com/advisories/GHSA-mvr2-9pj6-7w5j 
Type:  
Influences：  
    1.upgrade guava, so need to  upgrade  curator, [curator 4.2.0 with zk3.4.x](http://curator.apache.org/zk-compatibility-34.html)
2.typo
> 1.CVE-2018-10237 2.typo

- src/main/java/com/actiontech/dble/cache/impl/EnchachePoolFactory.java
- src/main/java/com/actiontech/dble/cache/impl/RocksDBCachePoolFactory.java
- src/main/java/com/actiontech/dble/cache/impl/RocksDBPool.java
- src/main/java/com/actiontech/dble/singleton/CacheService.java
- src/test/java/com/actiontech/dble/cache/DefaultLayedCachePoolTest.java
Reason:  
  BUG #inner 325
Type:  
  BUG
Influences：  
  occur 'No locks available' error when double open rocksdb in reload
> occur 'No locks available' error when double open rocksdb in reload

- docker-images/quick-start/bootstrap.cnf
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG #1701
Type:  
  BUG
Influences：  
   fix:
1.default xalog name
2.cannot generate a path for transactions, view storage, and so on
> #1701 update default xalog name, and fix: cannot generate a path for transactions, view storage, and so on

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterTableParser.java
Reason:  
  BUG #inner370.
Type:  
  BUG
Influences：  
  ddl of rename index in mysql 5.6 isn't online ddl
> ddl of rename index in mysql 5.6 isn't online ddl

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG #inner 448.
Type:  
  BUG 
Influences：  
  reset initial flag when connection pool was stopped
> reset initial flag when connection pool was stopped

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/response/FreshBackendConn.java
handle the rwSplitMode of this dbGroup is 0 scenario，and remove duplicate dbInstanceName
Reason:  
  BUG  
Type:  
  Improve  
Influences：  
   handle the rwSplitMode of this dbGroup is 0 scenario，and remove duplicate dbInstanceName
> handle the rwSplitMode of this dbGroup is 0 scenario，and remove duplicate dbInstanceName

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/sqlengine/SpecialSqlJob.java
Reason:  
Type:  
  Improve  
Influences：  
  use connection out of connection pool to get table meta when dryrun
> use connection out of connection pool to get table meta when dryrun

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG #inner 465. 
Type:  
  BUG
Influences：  
   fix for slave instance keeps a heartbeat connection when rwSplitMode== RW_SPLIT_OFF
> fix for slave instance keeps a heartbeat connection when rwSplitMode== RW_SPLIT_OFF

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #1880  
Type:  
  BUG  
Influences：  
   fix for autotest packetId, packetId should be set before the handler try to send a errorPacket
> fix for autotest packetId

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  Improve #2075.  
Type:  
  Improve  
Influences：  
  dbGroup used by sharding can't be used by rwSplit
> dbGroup used by sharding can't be used by rwSplit

- src/main/java/com/actiontech/dble/route/util/ConditionUtil.java
Reason:  
  BUG #2153 
Type:  
  BUG
Influences：  
   fix when partitionColumn value equal '', forward all nodes
> issue 2153

- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  fix: Remove -DbufferPoolPageNumber from bootstrap_template.cnf
> fix: Remove -DbufferPoolPageNumber from bootstrap_template.cnf

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
Reason:  
  BUG #inner508.
Type:  
  BUG
Influences：  
  remove \n or \t in sql
> remove \n or \t in sql in manager table of backend connections

- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
  Improve #inner708.  
Type:  
  Improve  
Influences：  
  modify tips when there are no rwsplit user or sharding user in dryrun
> modify tips when there are no rwsplit user or sharding user in dryrun

- src/main/java/com/actiontech/dble/services/manager/information/tables/BackendVariables.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/SessionVariables.java
* add primary key for manager table
* modify dryrun tips
(cherry picked from commit 189830a9245ae7dfb6b77e1821b125b92bb55350)
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  add primary key for manager table (#2306)
> add primary key for manager table (#2306)

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  Some special string in the manage SQL parser may cause  StringIndexOutOfBoundsException.
Type:  
  BUG
Influences：  
  Fixed some StringIndexOutOfBoundsException.
> Fixed some StringIndexOutOfBoundsException when sql parse.

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
Reason:  
  BUG inner 789
Type:  
  BUG
Influences：  
  '-javaagent' configuration item is supported in the bootstrap.cnf
> '-javaagent' configuration item is supported in the bootstrap.cnf

- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner 603/605/606
Type:  
  BUG
Influences：  
  fix: problems with set names and set charset
1.Ensure that the input sql character set of dble and mysql is consistent
2.This statement maps all strings sent between the server and the current client with the given mapping. SET CHARACTER SET sets three session system variables: character_set_client and character_set_results are set to the given character set, and character_set_connection to the value of character_set_database.
ref:https://dev.mysql.com/doc/refman/5.7/en/set-character-set.html
> fix: problems with set names and set charset

- src/main/java/com/actiontech/dble/server/parser/RwSplitServerParse.java
- src/main/java/com/actiontech/dble/services/FrontEndService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
  In RwSplit scenarios, when using JDBC with URL param `allowMultiQueries`, send multi-query cause timeout.Error reports:`(2013, 'Lost connection to MySQL server during query')`
Type:  
  BUG inner-711
Influences：  
   fixed.
Reason:  
  In RwSplit scenarios, the `CALL` query causes hang.
Type:  
  BUG inner-631
Influences：  
   fixed.
> Inner 711&631: fixed:multi-query cause timeout and  'CALL' query causes hang.

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
Reason:  
  In RwSplit scenarios, the `create temporary table` query doesn't send to the master. But the 'select from temporary table' query send to slave. So cause `table not found ` error.
Type:  
  BUG  inner 557
Influences：  
- If I create a temporary table, all queries would send to master unless drop all temporary tables afterward. 
  
> inner-557: fixed: temporary table query should send to master

- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
Reason:  
supplement to https://github.com/actiontech/dble/pull/2379 .
  
Used repeat id. Although cause no error yet. But it is a bad practice.
Type:  
  Improve  
Influences：  
   parse sql.
> inner-557-supplement: ServerParse using repeat id

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/helper/KeyVariables.java
- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner 647
Type:  
  BUG
Influences：  
the mysql instance version cannot be lower than the dble version
the charsetutil reference does not work due to the timing of fakeMySQLVersion value assignment
> fix: the mysql instance version cannot be lower than the dble version

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG #2199 
Type:  
  BUG
Influences：  
when parsing where conditions, you need to match according to table name+table alias
deduplication where filter 
#2073 
inner-590
> fix: when parsing where conditions, you need to match according to table name+table alias

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
Reason:
  Improve inner-814
Type:
  Improve
Influences：
   fix: when connecting, the client_found_rows value of the client and dble are inconsistent, the log will prompt
#2413
> fix: when connecting, the client_found_rows value of the client and dble are inconsistent, the log will prompt(cherry pick from master #2413)

- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
Reason:  
  BUG inner-878
Type:  
  BUG
Influences：  
fix: synchronously modify the value of dbGroup_status in the configuration center during reload
sequence persistence increases judgment
> fix: synchronously modify the value of dbGroup_status in the configuration center during reload

- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG #inner-889. 
Type:  
  BUG
Influences：  
  fix that set statement that contains `.` doesn't work, eg: set @.abc_123$=8
> fix that set statement that contains `.` doesn't work, eg: set @.abc_123$=8

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResult.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResultCode.java
- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
- src/main/java/com/actiontech/dble/net/mysql/MySQLPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/ServiceTask.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/util/CompressUtil.java
Reason:  
  BUG inner-836
Type:  
  BUG
Influences：  
   fix xx
> inner-836:big packet support

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner-954
Type:  
  BUG  
Influences：  
  correct 'primary' column in dble_db_instance manager table
> correct 'primary' column in dble_db_instance manager table

- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
   prevent out of memory
> limit size of  slow query log queue.

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleReloadStatus.java
Reason:  
  Improve #inner 965.  
Type:  
  Improve  
Influences：  
  Result of dble_reload_status manager table is empty instead of default row when there is no reload action.
> Result of dble_reload_status manager table is empty instead of default row when there is no reload action.

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix dble crash when load data statement have local field inner 966
> fix dble crash when load data statement have local field inner 966

- pom.xml
Reason:  
  BUG 
Type:  
  BUG
Influences：  
fix: Zookeeper 3.4.13 or higher version causes startup error
> fix: Zookeeper 3.4.13 or higher version causes startup error

- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/test/java/com/actiontech/dble/util/ManagerTableTest.java
Reason:  
  BUG inner 1051
Type:  
  BUG
Influences：  
   fix: table name was not resolved in the hint sql(cherry pick from 3.21.02.99)
> fix: table name was not resolved in the hint sql(cherry pick from 3.21.02.99)

- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
Reason:  
  BUG #inner 1001.
Type:  
  BUG
Influences：  
  allocate n * chunksize heap byte buffer instead of just good size when direct byte buffer isn't enough
> inner-1001 - allocate n * chunksize heap byte buffer instead of just good size when direct byte buffer isn't enough

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG inner-1119
Type:  
  BUG
Influences：  
fix:complex queries including sub-queries do not need to be optimized for single node delivery
eg:select count(*) from sharding_4_t1 where id =(select id from sharding_4_t1 where id=1)
> fix:complex queries including sub-queries do not need to be optimized for single node delivery

- src/main/java/com/actiontech/dble/cluster/logic/AbstractClusterLogic.java
Reason:  
  BUG inner-1154: reload config should succeed if cluster meta is empty
Type:  
  BUG
Influences：  
   cluster waiting
> inner-1154: reload config should succeed if cluster meta is empty

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticDisruptor.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
…s table accidentally loses the transaction
Reason:  
  BUG inner 1186
Type:  
  BUG
Influences：  
   fix: when a connection exits directly in a transaction, the statistics table accidentally loses the transaction
> fix: when a connection exits directly in a transaction, the statistics table accidentally loses the transaction

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner#940.
Type:  
  BUG
Influences：  
  avoid that backend connection is closed before setting ResponseHandler to backend connection
> inner-940:avoid that backend connection is closed before setting ResponseHandler to backend connection

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/groupby/DirectGroupByHandler.java
Reason:  
  BUG #1239.  
Type:  
  BUG
Influences：  
  avoid thread remaining for group by
> inner-1239:avoid thread remaining for group by

- src/main/java/com/actiontech/dble/btrace/provider/ClusterDelayProvider.java
- src/main/java/com/actiontech/dble/cluster/response/DataHostHaResponse.java
- src/main/java/com/actiontech/dble/cluster/xmltoKv/XmltoCluster.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/DataHostStatusTozkLoader.java
Reason:  
  BUG inner-1253: make sure XmlSchemaLoader read the newest data of HA when use reload
Type:  
  BUG
Influences：  
   reload
> inner-1253: make sure XmlSchemaLoader read the newest data of HA when use reload

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FieldListHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MysqlCreateViewHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MysqlDropViewHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/UnLockTablesHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterViewParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateOrReplaceViewParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropViewParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1261
Type:  
  BUG
Influences：  
   1、 'txInterrupted' is not updated when an implicit commit statement is executed in error
2、Adjust the class(LockTablesHandler/MysqlCreateViewHandler/MysqlDropViewHandler ..)
> 'txInterrupted' is not updated when an implicit commit statement is executed in error

- src/main/java/com/actiontech/dble/config/model/sharding/table/ChildTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/GlobalTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/ShardingTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/SingleTableConfig.java
Reason:  
  BUG inner-1280: fix miss id in lower_case_table_name clone
Type:  
  BUG
Influences：  
  id of table config
> inner-1280: fix miss id in lower_case_table_name clone

- src/main/java/com/actiontech/dble/meta/TableMeta.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix checkTableConsistency error when dble metadata is the same as mysql metadata inner 1276

- src/main/java/com/actiontech/dble/meta/TableMeta.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
  fix checkTableConsistency error when dble metadata is the same as mysql metadata
> cherry pick from pr(2809) amd fix checkTableConsistency error when dble metadata is the same as mysql metadata

- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
Reason:  
  BUG //TODO
Type:  
  BUG
Influences：  
   fix :Three (ER) table query results are incorrect
> Three (ER) table query results are incorrect

- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
- src/main/java/com/actiontech/dble/util/SelectorUtil.java
Reason:  
  BUG #11/inner-1304
Type:  
  BUG
Influences：  
fix: avoid the soaring cpu caused by nio-select
jdk-bug：https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6403933
refer to https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/channel/socket/nio/AbstractNioSelector.java
> fix: avoid the soaring cpu caused by nio-select

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:  
  BUG inner-1443-supplement:fix :memory leak when suddenly close
Type:  
  BUG
Influences：  
  write
> inner-1443-supplement: fix :memory leak when suddenly close

- src/main/java/com/actiontech/dble/meta/table/GetTableMetaHandler.java
Reason:  
  BUG inner 1455
Type:  
  BUG
Influences：  
   fix：'ConcurrentModificationException' occurred while loading metadata
> fix[inner-1455]: 'ConcurrentModificationException' occurred while loading metadata

- src/main/java/com/actiontech/dble/meta/table/GetTableMetaHandler.java
Reason:  
  BUG inner 1455
Type:  
  BUG
Influences：  
   fix :'ConcurrentModificationException' occurred while loading metadata
> fix[inner-1455]: 'ConcurrentModificationException' occurred while loading metadata（cherry pick）

- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner1454.  
Type:  
  BUG
Influences：  
  backend connection in use is returned to connection pool
> backend connection in use is returned to connection pool

- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner#1454. 
Type:  
  BUG 
Influences：  
  inner 1454 - release serializable lock when front connection is closed
> inner 1454 - release serializable lock when front connection is closed

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
  BUG: inner-1544: fix LVS/SLB heartbeat cause memory leak
Type:  
  BUG
Influences：  
   connection creation
> inner-1544: fix LVS/SLB heartbeat cause memory leak

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG inner-1587
Type:  
  BUG
Influences：  
fix: processing of space values when parsing csv
> fix: processing of empty values when parsing csv

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1615
Type:  
Influences：  
   fix xx
> [inner-1615] During ddl execution, the creation and release of a table lock must be the same session on the business side

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1615,950; similar pr #3135 #2698 
Type:  
  BUG
Influences：  
   fix xx
> [inner-1615,950] During ddl execution, the creation and release of a table lock must be the same session on the business side (cherry pick)

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG 1615
Type:  
  BUG
Influences：  
   fix xx
> [inner-1615] During ddl execution, the creation and release of a table lock must be the same session on the business side (cherry pick)

- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  BUG.
Type:  
  BUG
Influences：  
  avoid deadlock between backend connection close and backend recycle
> avoid deadlock between backend connection close and backend recycle

- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG #inner 1706.
Type:  
  BUG
Influences：  
  remove schema incorrectly,eg: table name contains schema name
> inner 1706 - remove schema incorrectly

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG inner-1746
Type:  
  BUG
Influences：  
fix: "between and" returns the wrong table name
> fix: "between and" returns the wrong table name

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:
  BUG inner-1886
Type:
  BUG
Influences：
fix: sync is required when sharding.xml is empty
#3346
> fix: sync is required when sharding.xml is empty(cherry-pick)

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeatStatus.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/cluster/logic/HAClusterLogic.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeat.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:
  BUG inner-1847、inner-1874
Type:
  BUG
Influences：
fix: newly added instance needs to create a connection pool immediately #3357
heartbeat status is STOP_STATUS after ha disable
fix: config is synced to ha's memory #3359
fix: use lowercase for status #3366
> fix: newly added instance needs to create a connection pool immediately(cherry-pick)

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
Reason:  
  BUG #inner 1980. 
Type:  
  BUG
Influences：  
  keep respHandler and responseHandler in MySQLConnectionHandler consistent
> inner 1980 - keep respHandler and responseHandler in MySQLConnectionHandler consistent

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:  
  BUG inner-2028
Type:  
  BUG
Influences：  
fix: add the determination of whether ssl is enabled
when the buffer is always full but no new data has been read, an error needs to be reported
> fix: add the determination of whether ssl is enabled

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:
  BUG inner-2028
Type:
  BUG
Influences：
fix: add the determination of whether ssl is enabled
when the buffer is always full but no new data has been read, an error needs to be reported
#3505
> fix: add the determination of whether ssl is enabled（cherry-pick）

- .github/workflows/codeql.yml
Reason:  
  Improve    
Type:  
  Improve  
Influences：  
fix: not display note-level warnings
> fix: not display note-level warnings

- src/main/java/com/actiontech/dble/server/parser/RwSplitServerParse.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:
  In RwSplit scenarios, when using JDBC with URL param allowMultiQueries, send multi-query cause timeout.Error reports:(2013, 'Lost connection to MySQL server during query')
Type:
  BUG inner-711
Influences：
   fixed.
Reason:
  In RwSplit scenarios, the CALL query causes hang.
Type:
  BUG inner-631
Influences：
   fixed.
> Inner 711&631: fixed:multi-query cause timeout and 'CALL' query causes hang(cherry-pick)

- src/main/java/com/actiontech/dble/statistic/stat/UserSqlHighStat.java
Reason:  
  BUG #3238 .
Type:  
  BUG
Influences：  
  fix cpu 100%
> issue 3238 - fix cpu 100%

- pom.xml
Reason:  
  Improve inner 2095
Type:  
Influences：  
   fix xx
> [inner-2095] Log4j upgrade to 2.18.0 version

- pom.xml
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  upgrade log4j2 to 2.18.0
> upgrade log4j2 to 2.18.0

- pom.xml
Reason:  
  BUG inner 2095, similar #3605 
Type:  
Influences：  
   fix xx
> [inner-2095] Log4j upgrade to 2.18.0 version (cherry pick)

- pom.xml
Reason:  
  BUG inner 2095 ,similar #3605 
Type:  
Influences：  
   fix xx
> [inner-2095] Log4j upgrade to 2.18.0 version (#3605)

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/mysql/VersionUtil.java
- src/main/java/com/actiontech/dble/config/model/MysqlVersion.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
Reason:  
  BUG inner-2051
Type:  
  BUG
Influences：  
fix: use rw-split, mysql version and dble fakeMySQLVersion keep the same range
> fix: use rw-split, mysql version and dble fakeMySQLVersion keep the same range

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
- src/main/java/com/actiontech/dble/cluster/ClusterController.java
Reason:
  BUG inner-1867&inner-2089
Type:
  BUG
Influences：
fix: the timing of obtaining the number of waiting threads in the connection pool is wrong
fix: grpcTimeout parameter validation
> fix: the timing of obtaining the number of waiting threads in the connection pool is wrong

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  BUG inner-2221
Type:  
  BUG
Influences：  
fix: peel version check module 
when modifying the rwSplitUser-dbGroup, it is also necessary to check the version
> fix: peel version check module 

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/log/DailyRotateLogStore.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/status/SlowQueryLog.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadSlowQueryFlushPeriod.java
Reason:  
  BUG inner-2227/inner-2230
Type:  
  BUG
Influences：  
fix: after the slow log queue is full, discard the subsequent records that need to be added 
after abnormal disk flush, fileChannel will not close
> fix: after the slow log queue is full, discard the subsequent records that need to be added 

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
Reason:  
  BUG inner-2051
Type:  
  BUG
Influences：  
fix: utf8mb4_0900_ai_c is only supported when the dble version is greater than or equal to 8.0.3
> fix: utf8mb4_0900_ai_c is only supported when the dble version is greater than or equal to 8.0.3

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/RwSplitSelectVariablesHandler.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
cherry-pick https://github.com/actiontech/dble/pull/3686
Reason:  
Type:  
Influences：  
   fix xx
> fix jdbc compatible pre-delivery statements error inner 2212

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/log/DailyRotateLogStore.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/server/status/SlowQueryLog.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadSlowQueryFlushPeriod.java
Reason:
  BUG inner-2227/inner-2230
Type:
  BUG
Influences：
fix: after the slow log queue is full, discard the subsequent records that need to be added
after abnormal disk flush, fileChannel will not close
#3704
> fix: after the slow log queue is full, discard the subsequent records that need to be added(cherry-pick)

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/DailyRotateLogStore.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/server/status/SlowQueryLog.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadSlowQueryFlushPeriod.java
Reason:
  BUG inner-2227/inner-2230
Type:
  BUG
Influences：
fix: after the slow log queue is full, discard the subsequent records that need to be added
after abnormal disk flush, fileChannel will not close
#3704
> fix: after the slow log queue is full, discard the subsequent records that need to be added(cherry-pick) 

- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleApNode.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleSchema.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2220] the management side can view apNode

- src/main/java/com/actiontech/dble/plan/common/time/MyTime.java
Reason:  
  BUG inner-2311
Type:  
  BUG
Influences：  
fix: precision is missing when datetime/timestamp/time are converted to strings
> [inner-2311] fix: precision is missing when datetime/timestamp/time are converted to strings

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/model/user/RwSplitUserConfig.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  BUG inner-2060
Type:  
  BUG
Influences：  
database is not checked during login
#3567
> [inner-2060] fix: database is not checked during login(cherry-pick)

- src/main/java/com/actiontech/dble/services/factorys/ManagerConnectionFactory.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLManagerFrontAuthService.java
- src/main/java/com/actiontech/dble/singleton/ThreadManager.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2358] manager side uses managerFrontHandlerQueue when authenticating

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/singleton/ThreadManager.java
Reason:  
Type:  
Influences：  
   adjust tips
   fix: the results of show trace are incomplete
> [inner-2361&2356] fix: the results of show trace are incomplete

- src/main/java/com/actiontech/dble/singleton/ThreadManager.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2362] disable kill and recover operations on NIOFrontRW threads

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2371] fix: sql execution hang problem caused by the inability to respond to the front side due to unprocessed packets.

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG similar https://github.com/actiontech/dble/pull/3847
Type:  
Influences：  
   fix xx
> [inner-2377] Ensure the orderliness of stop/start operations of dbinstance

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> optimize log display inner 2378

- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/cluster/logic/ConfigClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/logic/HAClusterLogic.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  similar #3755 
Type:  
Influences：  
   fix xx
> [inner-2256] fix: narrow down the scope of syncing dbGroup state

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/PreparedResponseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/MysqlExecuteResponseHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/MysqlPrepareLogicHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
pick from https://github.com/actiontech/dble/issues/2402
Reason:  
Type:  
Influences：  
   fix xx
> support ps protocol inner 349

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/BeginHandler.java
- src/main/java/com/actiontech/dble/server/handler/CommitHandler.java
- src/main/java/com/actiontech/dble/server/handler/RollBackHandler.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2082] fix: the commit time statistics in the slow log are incorrect

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/general/response/ConfigStatusResponse.java
- src/main/java/com/actiontech/dble/cluster/values/ConfStatus.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/listen/ConfigStatusListener.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadContext.java
Reason:  
  BUG inner-2383-supplement:
Type:  
  BUG
Influences：  
  support delete&&support cluster
> inner-2383-supplement:support delete&&support cluster

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  BUG Inner 2388:
Type:  
  BUG
Influences：  
    fix when modify slave instance when update db_instance
> Inner 2388: fix when modify slave instance when update db_instance

- pom.xml
- src/main/java/com/actiontech/dble/cluster/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/impl/ushard/UshardSender.java
Reason:  
  BUG Inner 2389 
Type:  
  BUG
Influences：  
  rollback update jar
> Inner 2389 rollback update jar

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG inner-2407： rwSplit user hang after HA
Type:  
  BUG
Influences：  
    need init connection pool when switch with config rwsplitMode=0
> inner-2407： need init connection pool when switch with config rwsplitMode=0

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAAnalysisHandler.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/net/mysql/SSLRequestPacket.java
- src/main/java/com/actiontech/dble/net/ssl/GMSslWrapper.java
- src/main/java/com/actiontech/dble/net/ssl/IOpenSSLWrapper.java
- src/main/java/com/actiontech/dble/net/ssl/OpenSSLWrapper.java
- src/main/java/com/actiontech/dble/net/ssl/SSLWrapperRegistry.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/test/java/com/actiontech/dble/optimizer/FakeConnection.java
Reason:  
  support backend ssl && support ob
Type:  
  improve  
Influences：  
   fix xx
> support backend ssl && support ob

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/net/ssl/IOpenSSLWrapper.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  Improve
Type:  
Influences：  
   fix xx
> ssl supplyment: fix checkstyle

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  Improve inner-2413: recreate heartbeat connection when timeout
Type:  
  Improve  
Influences：  
   fix xx
> inner-2413: recreate heartbeat connection when timeout

- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG atk-4344 :reorder config && disable useSqlStat
Type:  
  BUG
Influences：  
   fix xx
> atk-4344 :reorder config && disable useSqlStat

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogEntry.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseOnOff.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/status/SlowQueryLog.java
- src/main/java/com/actiontech/dble/server/trace/ITraceResult.java
- src/main/java/com/actiontech/dble/server/trace/RwTraceResult.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
- src/main/java/com/actiontech/dble/services/manager/handler/DisableHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/EnableHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/OnOffAppendTraceId.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/PSHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/singleton/AppendTraceId.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve ATK-4339&ATK-4341 :support slow log  
Type:  
  Improve  
Influences：  
   slow log for rw
> ATK-4339&ATK-4341 :support slow log for rw user

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/server/trace/ITraceResult.java
- src/main/java/com/actiontech/dble/server/trace/RwTraceResult.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
Type:  
Influences：  
   fix xx
> ATK-4339&ATK-4341 :fix ci && disable config by default

- pom.xml
- src/main/java/com/actiontech/dble/memory/unsafe/utils/JavaUtils.java
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
1. update guava version to 32.1.2-jre
2. fix npe warning
> [ATK-4416]: update guava version
