- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowVariablesHandler.java
- src/main/java/com/actiontech/dble/server/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParseShow.java
- src/main/java/com/actiontech/dble/server/response/ShowVariables.java
Reason:
statement 'show [global | session] variables ...' don't show the real values of variables that have been
set by frontend.
Type:
   Improvement
Influences：
the following statements are impacted:
show schemas;
show [global | session] variables ...
> show the real value of variables that have been set

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:
  When try to add limit n in the end of sql there can be cause some sql syntax error
Type:
  Bug fix
Influences：
  Change the way 'limit n' added
> Issue 291 fix add 'limit n' to sql

- src/main/java/com/actiontech/dble/backend/mysql/view/recovery/FileSystemRepository.java
Reason:
  Fixes #303
Type:  
Fixes
Influences：  
Init the view object after viewJson inited
> #303 view support

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/DropViewHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/test/java/com/actiontech/dble/parser/ServerParserTest.java
Reason:
  Improve #303
Type:  
  Improve
Influences：  
  Add support for alter view
>  #303 view support add support of alter view

- src/main/java/com/actiontech/dble/config/Versions.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/ServerSptPrepare.java
- src/main/java/com/actiontech/dble/server/handler/ScriptPrepareHandler.java
- src/main/java/com/actiontech/dble/server/parser/ScriptPrepareParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/server/response/SptDrop.java
- src/main/java/com/actiontech/dble/server/response/SptExecute.java
- src/main/java/com/actiontech/dble/server/response/SptPrepare.java
- version.txt
Reason:
add support for script prepare 
Type:
   Improvement
Influences：
the following statements are impacted:
explain;
drop;
> Ftr prepare

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
Reason:
   Fix #303
Type:
   Fix
Influences：
   Add check of Duplicate column when create the view
> #303  add check to Duplicate column

- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
Reason:
  Fixes #322 
Type:  
  Fix
Influences：  
  Transport sql type to backend handler correctly
> #322 Frontend Connection handling when exec MYSQL PROCEDURE

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/ViewChildListener.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateTableParser.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/CreateViewHandler.java
Reason:
  Fix #303   
Type:  
  Fix
Influences：  
  Add cluster support on view use
  Add lock to avoid conflict of tables and views
> #303 view add cluster support

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
Reason:
  Fix #330 
Type:  
  Fix 
Influences：  
  Change the Long.parseLong into BigDecimal
> #330 'statement.setMaxRows' can make 'dble' client hanged.

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:
  Fixes #341
Type:
  Fixes
Influences：
  Change the alias of the view
> #341 Select view can make dble client hanged Function view

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterTableParser.java
Reason:
the hint is ambiguity, so make corrections
Type:  Improve 
Influences：  
nothing
> #344, improve hints

- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
Reason:
store function not existing must restart.
Type:  bug
Influences：  
global db sequence
> fix, store function not existing must restart

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
Reason:
improve hints to unify
Type:  improve
Influences：  
nothing
> #356, improve hints

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowBackendStat.java
- src/main/java/com/actiontech/dble/manager/response/ShowCommandCount.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnectionCount.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/test/java/com/actiontech/dble/parser/ManagerParserTest.java
Reason: 
add show @@backend.statistics, show @@command.count, show @@connection.count for manager.
Type:  Improve
Influences：  
show @@backend
show @@command
show @@connection
show @@connection.sql
etc.
> add some command for manager

- src/main/java/com/actiontech/dble/manager/response/ShowCommandCount.java
Reason:
coding wrong
Type:  bug
Influences：  
show @@command.count, see issue #384
> fix count wrong

- src/main/java/com/actiontech/dble/server/handler/ScriptPrepareHandler.java
Reason:
hint is obscure
Type:  
Improve 
Influences：  
prepare ...
> #395, change hints info

- src/main/java/com/actiontech/dble/buffer/ByteBufferPage.java
- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
Reason: 
  Bug #445  
Type:  
  Bug fix
Influences： 
  change the way calculate DirectByteBuffer size
> #445 Manager command ‘show @@processor’ has the wrong result

- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/route/function/PartitionByJumpConsistentHash.java
- src/main/resources/rule_template.xml
Reason:
  Improve #447 
Type:  
  Improve 
Influences：  
  Allow to use "jumpStringHash" in rule.xml
> #447 Jump Consistent Hash

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason: 
  Bug #411
Type:  
  Bug fix
Influences：  
  Allow dble to start without schema&dataNode
> #411 Dble can not startup when the schema.xml is almost empty

- src/main/assembly/bin/init_ucore_data.sh
- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UcoreConfig.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/XmltoUcore.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UXmlServerLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/comm/ZkConfig.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/Server.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/server/Alarm.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/parse/entryparse/server/json/AlarmJsonParse.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
Reason:
  Improve ucore  cluster & add init shell
Type:  
  Improve
Influences：  
  add new shell 
  add alarm in server.xml into init
> cluster config concentrated & ucore init shell added

- src/main/assembly/bin/init_ucore_data.sh
Reason:
  Improve the init shell for ucore
Type:  
  Improve
Influences：  
  add new parameter using in shell
> change init shell for ucore

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistrbtLockManager.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistributeLock.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UXmlRuleLoader.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:
  Improve Cluster
Type:  
  Improve
Influences：  
  User lock for ddl when use ucore & save rule detail to ucore
> Cluster improve

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
Reason:
  Improve show @@help
Type:
  Improve #403
Influences：
  Update the lastest help of manage port
> update show @@help

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/btrace/provider/CostTimeProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BTraceCostTime.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/statistic/stat/QueryTimeCost.java
Reason:
  Improve btrace
Type:
  Improve 
Influences：
  Add check point 3.05
> add point 3.05

- src/main/java/com/actiontech/dble/btrace/provider/CostTimeProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BTraceCostTime.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/statistic/stat/QueryTimeCost.java
Reason:
  Improve btrace
Type:
  Improve
Influences：
  Add check point 4L 5L
> add point 4L 5L

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:
  Bug
Type:  
  Bug
Influences：  
  Fix check point 4L&5L
> Fix point 4L 5L

- src/main/assembly/bin/init_ucore_data.sh
Reason:
  Bug machine may don't have java
Type:  
  Bug
Influences： 
  Add $2 into shell
> fix init ucore shell

- src/main/java/com/actiontech/dble/backend/mysql/view/CKVStoreRepository.java
- src/main/java/com/actiontech/dble/backend/mysql/view/Repository.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreSingleKeyListener.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UDdlChildResponse.java
Reason:
  Cluster bug fix
Type:  
  Bug fix
Influences：  
  DDL responser will never response to delete key event
  Change the order of view create notify
> cluster bug fix

- src/main/java/com/actiontech/dble/backend/mysql/view/CKVStoreRepository.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UViewChildResponse.java
Reason:
  Cluster bug fix
Type:
  Bug fix
Influences：
  ViewListener will put the view create sql into right place
> Cluster fix

- src/main/java/com/actiontech/dble/log/AlarmAppender.java
Reason:
  grpc alarm fix
Type:
  Bug fix
Influences：
  Reload grpc alarm with right function
> grpc alarm reload fix

- src/main/java/com/actiontech/dble/log/AlarmAppender.java
- src/main/java/com/actiontech/dble/manager/response/ShowBinlogStatus.java
Reason: 
  Cluster fix
Type:  
  Bug fix
Influences：
> Cluster fix new

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:
  Improve #473    
Type:  
  Improve
Influences：  
  The sql 'select .... order by for update' &'select .... order by lock in share mode' will lock the select table
> for update can be use with order by

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistributeLock.java
Reason:
  Cluster fix
Type:
  Bug fix
Influences：
  When the online flag is gone ,try to recreate the flag
> online lock recreate

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/UnionHandler.java
- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistributeLock.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreClearKeyListener.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreSingleKeyListener.java
Reason:
  Cluster fix
Type:
  Bug fix
Influences：
  When ucore offline the dble will slow polling the grpc waiting for ucore start
> Add delay when ucore offline

- src/main/java/com/actiontech/dble/route/sequence/handler/Counter.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/SequenceVal.java
Reason:
  Bug #489
Type:
  Bug fix
Influences：
  Reconstruction the db sequence
> db sequence fix

- src/main/java/com/actiontech/dble/server/parser/ServerParseShow.java
Reason:
  Bug #497 
Type:
  Bug fix
Influences：
  'Show full fields' will be parse like 'Show fields'
> #497 add SHOW FULL FIELDS support

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:
  Bug XA flag is same in Cluster 
Type:
  Bug fix
Influences：
  When in Cluster  mode use self id for xa id
> ucore xa flag set

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:(Bug #. or Improve #.)   
Type:  
Influences：
> ucore online init when the config is incomplete (#504)

- .gitignore
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/server/response/ShowTableStatus.java
Reason:
  Improve
Type:
  Improve
Influences：
  Code style fix
> Code style fix

- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UcoreConfig.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/XmltoUcore.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
Reason:
  Bug
Type:
  Bug fix
Influences：
  Avoid init shell hang
> ucore init changed

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/ClusterUcoreSender.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistributeLock.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreListenerUtil.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreNodesListener.java
- src/main/java/com/actiontech/dble/log/AlarmAppender.java
Reason:
  Bug fix
Type:
  Bug fix
Influences：
  shutdown grpc channel after the connection is closed
> ucore channel shutdown when the connection closed

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/view/CKVStoreRepository.java
- src/main/java/com/actiontech/dble/backend/mysql/view/FileSystemRepository.java
- src/main/java/com/actiontech/dble/backend/mysql/view/KVStoreRepository.java
- src/main/java/com/actiontech/dble/backend/mysql/view/Repository.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/KVtoXml/UcoreToXml.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistributeLock.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UBinlogPauseStatusResponse.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UDdlChildResponse.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UViewChildResponse.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:
  reload will clause handle leak
Type:  
  Bug
Influences：  
  terminate the handle when reload
  add name for thread listen to ucore
  change code style
> Ucore code style & view rwChannel close

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/KVtoXml/UcoreToXml.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UcorePathUtil.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/XmltoUcore.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UCacheserviceResponse.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UPropertySequenceLoader.java
Reason:
  Improve:change cacheservice.properties ucore path
Type:
  improve
Influences：
  Set the cacheservice.properties in ucore path universe/dble/clusterid/cache/cacheservice
> properties-path-change

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/view/CKVStoreRepository.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/ClusterUcoreSender.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/KVtoXml/UcoreToXml.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UOffLineListener.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UBinlogPauseStatusResponse.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UConfigStatusResponse.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UDdlChildResponse.java
- src/main/java/com/actiontech/dble/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/meta/PauseDatanodeManager.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:
  Improve
Type:
  Improve
Influences：
  Check the concrete response serverkey ,if there is some node online during cluster notify alarm the situation
> Ucore communicate change

- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
Reason:
  Adjustment delay point
Type:
  Bug
Influences：
  Adjustment delay point
> Adjustment delay point

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/test/java/com/actiontech/dble/config/ConfigTest.java
Reason:
  reload lower case not right
Type:  
  Bug
Influences：  
  Reload @@config logic changed
> #565 reload @@config logic change add

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBNode.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:
  reload @@config_all hang when use zk reload
Type:  
  Bug
Influences：  
  Change the zk switch Judge logic
> #541 zk reload fix

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:
  #583 
Type:
  BUG
Influences：
  release lock when get connection failed
> #583 add release lock when the connection get failed

- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/handler/CreateDatabaseHandler.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:
  Manager user can use "create database @@schema" to create database for  schema
Type:
  Improve
Influences：
  Add new command for manager port
> Manager create database

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
Reason:
  #588
Type:
  BUG
Influences：
  Add new flag in Mysqlconnection ,when complex query try to release check the connection data is all collected.if not, start a new thread to wait for 50ms to check the flag & try to release connection cyclly
  If the connection can not be released in 1s,just close the connection
> #588 when doing complex inner join get Error

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/model/ERTable.java
Reason:
  BUG #588
Type:
  BUG
Influences：
  reform the ER relation after change the config info into lowercase
> Reorganize ertable when the mysql instance is case insensitive

- src/main/java/com/actiontech/dble/route/function/AutoPartitionByLong.java
- src/main/java/com/actiontech/dble/route/function/PartitionByDate.java
- src/main/java/com/actiontech/dble/route/function/PartitionByFileMap.java
- src/main/java/com/actiontech/dble/route/function/PartitionByJumpConsistentHash.java
- src/main/java/com/actiontech/dble/route/function/PartitionByLong.java
- src/main/java/com/actiontech/dble/route/function/PartitionByString.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/sql/visitor/ActionSQLEvalVisitorUtils.java
Reason:
  Improve #567
Type:
  Improve
Influences：
  Accept null  as partition key
> Accept null  as partition key

- src/main/assembly/bin/btrace_log.sh
Reason:
  Improve 
Type:
  Improve
Influences：
  Add new bash shell for btrace
> add btrace script

- src/main/java/com/actiontech/dble/backend/datasource/BaseInfoDiff.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBNode.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPoolDiff.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasourceDiff.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseConfig.java
Reason:
  Improve #601
Type:
  Improve
Influences：
  Change the logic of reload @@config command,add new -R option to refresh all the dataHosts
> Reload partly

- src/main/java/com/actiontech/dble/backend/BackendConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/KillConnectionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalAutoRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAAutoRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:
  Improve #607
Type:
  Improve
Influences：
  Send quit packet before close backendConnections
> #607 return mysql quit packet before close TCP connection

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/KillConnectionHandler.java
- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
Reason:
  BUG inner 106
Type:
  BUG
Influences：
  Add alarm in killconnectionHandler
> Change kill alarm

- src/main/java/com/actiontech/dble/backend/mysql/xa/recovery/impl/FileSystemRepository.java
Reason:
  BUG Inner 107
Type:
  BUG
Influences：
  Add more alarm when try to R/W the tmlog
> Alarm place added

- src/main/java/com/actiontech/dble/config/model/TableConfig.java
Reason:
  Improve 587
Type:
  Improve
Influences：
  Add check when get random dataNode for global table read
> add random dataNode available check

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
Reason:
  BUG Inner 104
Type:
  BUG
Influences：
  When init dataNode init one backendConnection without schema
> when init dataNode init one backendConnection without schema

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPoolDiff.java
Reason:
  BUG #601
Type:
  BUG
Influences：
  Index fix
> #601 index BUG fix

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLDataSource.java
Reason:
  BUG #607
Type:
  BUG
Influences：
  Send QUIT_PACKET before close the socket
> #607 Change the interface of BackendConnection

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
Reason:
  BUG #535
Type:
  BUG
Influences：
  Change the limit default form 0 to -1
> issue 535 default limit is -1

- findbugs-exclude.xml
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ErrorInfo.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/model/rule/RuleAlgorithm.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/route/function/AutoPartitionByLong.java
- src/main/java/com/actiontech/dble/route/function/PartitionByDate.java
- src/main/java/com/actiontech/dble/route/function/PartitionByFileMap.java
- src/main/java/com/actiontech/dble/route/function/PartitionByJumpConsistentHash.java
- src/main/java/com/actiontech/dble/route/function/PartitionByLong.java
- src/main/java/com/actiontech/dble/route/function/PartitionByPattern.java
- src/main/java/com/actiontech/dble/route/function/PartitionByString.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:
  Improve #629
Type:
  Improve
Influences：
  Add manager command dryrun
> #629 new command dryrun

- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:
  BUG #632
Type:
  BUG
Influences：
  When -f added close all the previous backendConnection which was put into oldList
> #632 reload wouldn't be blocked by old backendConnections

- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:
  BUG #632
Type:
  BUG
Influences：
  Compare the diff of dataHosts before show variables
> #632 compare the diff of dataHosts before show variables

- src/main/java/com/actiontech/dble/route/function/PartitionByDate.java
- src/main/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnit.java
- src/main/java/com/actiontech/dble/sqlengine/mpp/ColumnRoutePair.java
- src/main/java/com/actiontech/dble/sqlengine/mpp/IsValue.java
Reason:
  Bug #635
Type:
  Bug
Influences：
  Sql with 'IS NULL' should be route properly
> #635 Error when "select" syntax with boolean type in where condition

- src/main/java/com/actiontech/dble/route/impl/DefaultRouteStrategy.java
Reason:
  Bug #126
Type:
  Bug
Influences：
  Throws exception when the sql is not correct
> sql explain may success when sql like 'select * from test wher eid = 1';

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:
  Improve #629
Type:
  Improve
Influences：
  Add user check when dry-run
> #629 add user check

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:
  BUG #629
Type:
  BUG
Influences：
   break change to continue
> #629 break change to continue

- src/main/java/com/actiontech/dble/meta/table/MultiTableMetaHandler.java
Reason:
  BUG #660
Type:
  BUG
Influences：
   fix init meta stuck
> #660 fix init meta stuck

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:  
  BUG #629 
Type:  
  BUG
Influences：  
  Clear the message of dry-run
> Inner clear the message of dryrun

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UViewChildResponse.java
Reason:  
  BUG #573
Type:  
  BUG
Influences：  
   fix when the update sql is the same ,success message should be send out
> when the update sql is the same ,success message should be send out

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #683
Type:  
  BUG
Influences：  
   Return empty OK packet when the input file is a empty file
> load data with empty file get error return

- src/main/java/com/actiontech/dble/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/meta/PauseEndThreadPool.java
Reason:  
  BUG #686  #690 #688
Type:  
  BUG
Influences：  
   Move pause start & resume into complexThreadPool
   Pause regular expression change
> #686 #690 move pause start & resume into complexThreadPool

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/server/parser/DbleOutputVisitor.java
- src/main/java/com/actiontech/dble/util/SqlStringUtil.java
Reason:  
  BUG #702
Type:  
  BUG
Influences：  
   Change the loaddata object to String add character into output
> #702 load data do not send the character to backend

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBNode.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
Reason:  
  BUG #697
Type:  
  BUG
Influences：  
   Change complex query get connections
> #670 #669 #649 hint logic fix

- src/main/assembly/bin/btrace_log.sh
Reason:  
  Improve btrace script  
Type:  
  Improve  
Influences：  
   Btrace script change
> trace script update

- src/main/java/com/actiontech/dble/route/handler/HintSQLHandler.java
Reason:  
  BUG #.698
Type:  
  BUG 
Influences：  
   Add sqlType check when use hint sql
> #698 add hint sql call type set

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/meta/table/DryRunGetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/meta/table/GetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/sqlengine/SpecialSqlJob.java
Reason:  
  Improve #712 
Type:  
  Improve  
Influences：  
   Add table meta check and ucore connect check in dryrun
> #712 Add new check item in Dryrun

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/MergeBuilder.java
- src/main/java/com/actiontech/dble/route/impl/DefaultRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #717 
Type:  
  BUG
Influences：  
   Complex query route null into all the node table involved
> #717 route null to all node when the route is from complex query

- src/main/resources/rule_template.xml
- src/main/resources/schema_template.xml
- src/main/resources/testdb.sql
Reason:  
  Improve for DBLE test or the 1st use
Type:  
  Improve  
Influences：  
  No
> + Provide the TESTDB schema SQL for test convenience

- src/main/java/com/actiontech/dble/meta/DDLChildListener.java
Reason:  
  BUG #732 
Type:  
  BUG
Influences：  
  Out put the result when slave dble update the meta
> zk ddl response lost

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPoolDiff.java
- src/main/java/com/actiontech/dble/server/variables/VarsExtractorHandler.java
Reason:  
  BUG #739 
Type:  
  BUG  
Influences：  
   reload @@config_all will update the connection test result when calculate the difference of old and new dataHost
> update test result when reload the dataHost

- src/main/java/com/actiontech/dble/config/model/SchemaConfig.java
Reason:  
  BUG #754
Type:  
  BUG
Influences：  
   Not change the dataNode name of schemaConfig when the mysql is in lower case table name
> lower case bug fix

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/server/handler/MysqlInformationSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/MysqlProcHandler.java
- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
     Improve #633.  
Type:  
   Improve  
Influences：  
   support to query mysql system schema for navicat premium 12
> support for navicat premium 12 driver

- src/main/java/com/actiontech/dble/net/FrontendConnection.java
Reason:  
  BUG #761  
Type:  
  BUG
Influences：  
   Change frontConnection countDown into synchronized
> #761 change frontConnection countDown into synchronized

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateTableParser.java
support to create table by the way of like
Reason:  
  Improve #757
Type:  
  Improve  
Influences：  
  fix to create tabel by the way of 'CERTE TABLE tb_name LIKE old_tb_name'
> #757 - support to create table by the way of like 

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:  
  BUG #712 
Type:  
  BUG
Influences：  
   Check null when try to close temp MySQL connection
> #712 check null when try to close temp MySQL connection

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
Reason:  
  BUG #680
Type:  
  BUG
Influences：  
  fix JDBC5.1.31 can not connect manager port and fail to execute manage command.
> #680 - fix JDBC5.1.31 can not connect manager port

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #772
Type:  
  BUG
Influences：  
   If a table do not has partition colums,just route it with no RouteCalculateUnit
> dble query [load data...] to global table got npe

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:  
  Bug #712
Type:  
  Bug  
Influences：  
   Delete the duplicate message of dryrun
> #712 dryrun message change

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
load data, fix npe when no default database and ignore empty line
Reason:  
  BUG #776 and BUG #769
Type:  
  BUG
Influences：  
     load data, fix npe when default database isn't selected and ignore empty line in file.
> load data, fix npe when no default database and ignore empty line

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG #779 
Type:  
  BUG
Influences：  
   Fix error when try to join with a constant
> #779 fix error when try to join with a constant

- src/main/java/com/actiontech/dble/sqlengine/SpecialSqlJob.java
Reason:  
  BUG #Inner 141
Type:  
  BUG
Influences：  
   dryRun thread safe
> #Inner 141 dryRun thread safe

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/alarm/AlertUtil.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/handler/DisableHandler.java
- src/main/java/com/actiontech/dble/manager/handler/EnableHandler.java
- src/main/java/com/actiontech/dble/manager/response/OnOffAlert.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseOnOff.java
Reason:  
  Improve to add alert switch 
Type:  
  Improve  
Influences：  
  improve to add alertEnable property in server.xml and command enable/disable @@ALERT in manager mode.
> add alertEnable property in server.xml and command enable/disable @@ALERT

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #800  
Type:  
  BUG  
Influences：  
   Do not save the null route result
> #800 Do not save the null route result

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/loader/xml/FirewallConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/UserConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/function/PartitionByLong.java
Reason:  
  Improve dryrun  
Type:  
  Improve  
Influences：  
  fix to add property check in server.xml when dryrun
> add property check in server.xml when dryrun

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeHandler.java
Reason:  
  BUG #808 
Type:  
  BUG  
Influences：  
   Change running flag change position into MySQLConnectionHandler
> #808 change running flag change position into MySQLConnectionHandler

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/net/handler/BackEndCleaner.java
- src/main/java/com/actiontech/dble/net/handler/BackEndDataCleaner.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #808  
Type:  
  BUG  
Influences：  
   waiting until row data end when the complex join in a transaction
> #808 waiting until row data end when the complex join in a transaction

- src/main/java/com/actiontech/dble/alarm/AlertUtil.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
  Improve to add manager command of show @@alert
Type:  
    Improve  
Influences：  
   Improve to add manager command of show @@alert
> add manager command of show @@alert

- src/main/java/com/actiontech/dble/server/response/ShowColumns.java
- src/main/java/com/actiontech/dble/server/response/ShowIndex.java
Reason:  
  BUG #798
Type:  
  BUG
Influences：  
  fix to  correct schema or table reg in `show columns/index` statement
> bug import from #798

- src/main/java/com/actiontech/dble/meta/table/MetaHelper.java
Reason:  
  BUG #831  
Type:  
  BUG  
Influences：  
   Change meta load column canNull flag default as true
> #831 change meta load default canNull as true

- src/main/java/com/actiontech/dble/server/response/ShowTableStatus.java
Reason:  
  BUG #824  
Type:  
  BUG  
Influences：  
  support like in show table status
> #824 support like in show table status

- src/main/java/com/actiontech/dble/net/handler/FrontendAuthenticator.java
Reason:  
  BUG #838
Type:  
  BUG  
Influences：  
   do not get into success when the connection check fail
> #838 do not get into success when the connection check fail

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG #836 
Type:  
  BUG  
Influences：  
  Delete the schema when send route sql to nosharding tables
> #836 delete the schema when send route sql to nosharding tables

- src/main/java/com/actiontech/dble/server/response/ShowTables.java
- src/main/java/com/actiontech/dble/server/response/ShowTablesStmtInfo.java
Reason:  
  BUG #825, #842
Type:  
  BUG
Influences：  
  include view in 'show full/all tables' statement and fix error about global table show
> include view in 'show full/all tables' statement

- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
Reason:  
  BUG #829 
Type:  
  BUG
Influences：  
   support hint in create view & support create view with schema.view
> #829 support hint in create view & support create view with schema.view

- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG #837 
Type:  
  BUG  
Influences：  
   stop route inner command when try to explain the sql
> #837 stop route inner command when try to explain the sql

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/view/CKVStoreRepository.java
- src/main/java/com/actiontech/dble/backend/mysql/view/FileSystemRepository.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreNodesListener.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG #Inner 154
Type:  
  BUG  
Influences：  
  dble start with cluster config when the ucore is shutdown
> #Inner 154 dble start with cluster config when the ucore is shutdown

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #797 
Type:  
  BUG  
Influences：  
   execute the DDL anyway when the part of DDL executed
> #797 execute the DDL anyway when the part of DDL executed

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
Reason:  
  BUG #838
Type:  
  BUG  
Influences：  
  change the way count db pool init success
> #838 change the way count db pool init success

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
  BUG #807
Type:  
  BUG
Influences：  
  slow log was written when one datanode execute error and rollback
> slow log was written when one datanode execute error and rollback

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/listen/UcoreNodesListener.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/SchemaMeta.java
Reason:  
  BUG #Inner 154
Type:  
  BUG  
Influences：  
   Update view meta when first reconnect to ucore
> #Inner 154 update the view and online status when reconnect to ucore

- src/main/java/com/actiontech/dble/meta/SchemaMeta.java
- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
Reason:  
  BUG #856
Type:  
  BUG
Influences：  
  delete the "`" in viewName when try to create or use a view
> #856 delete the "`" in viewName when try to create or use a view

- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/handler/FrontendCommandHandler.java
Reason:  
  BUG #869 
Type:  
  BUG  
Influences：  
   Collect the blob data when the COM_STMT_EXECUTE not arrive   
   Send all the blob data only when the COM_STMT_EXECUTE arrived
> #869 COM_STMT_SEND_LONG_DATA handle fix

- src/main/java/com/actiontech/dble/statistic/stat/UserStatAnalyzer.java
Reason:  
  BUG #846
Type:  
  BUG
Influences：  
  Due to thread-safety, show @@sql and show @@sql.resultset missing user sql record.
> show @@sql and show @@sql.resultset missing user sql record

- src/main/java/com/actiontech/dble/server/parser/ScriptPrepareParse.java
Reason:  
  BUG #872
Type:  
  BUG
Influences：  
    support escape character in prepare statement
> fix bug that can't support escape character in prepare statement

- dble_checkstyle_suppression.xml
- src/main/java/com/actiontech/dble/meta/table/DbleCreateTableParser.java
- src/main/java/com/actiontech/dble/meta/table/MetaHelper.java
Reason:  
  BUG #867 
Type:  
  BUG  
Influences：  
   Meta data check ignore AUTO_INCREMENT difference
   Show create table result can be changed,AUTO_INCREMENT=? value will be lost
> #867 meta data check ignore AUTO_INCREMENT difference

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ProblemReporter.java
- src/main/java/com/actiontech/dble/config/loader/xml/FirewallConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/UserConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
- src/main/java/com/actiontech/dble/config/model/DataHostConfig.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  optimize to check attribute/property  in config
Type:  
  Improve  
Influences：  
  optimize error/warning output when loading config and add schema.xml dryrun
>  optimize error/warning output when loading config and add schema.xml dryrun

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/CollationInfo.java
- src/main/java/com/actiontech/dble/manager/handler/SelectHandler.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowCollatin.java
- src/main/java/com/actiontech/dble/manager/response/ShowSingleString.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseSelect.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
  BUG #878
Type:  
  BUG
Influences：  
   SHOW COLLATION & SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP()) add to support list
> #878  .Net manager port support

- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  BUG #878
Type:  
  BUG  
Influences：  
   Dryrun/disable command support hint on the front
> #878 dryrun/disable command support hint on the front

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG #881
Type:  
  BUG
Influences：  
  fix missing primary key cache when try route to one node
> missing primary key cache when try route to one node

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UDdlChildResponse.java
- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
- src/main/java/com/actiontech/dble/meta/DDLChildListener.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/ViewChildListener.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/DropViewHandler.java
Reason:  
  Improve #900 
Type:  
  Improve  
Influences：  
   Reload return DDL sql when  error "other session doing DDL" occur
> #900 Reload return DDL detail when Error "other session doing DDL" occur

- src/main/resources/server_template.xml
Reason:  
  Improve: server_template.xml property  is case sensitive now
Type:  
  improve  
Influences：  
   fix xx
> change property node for case sensitive now

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #797
Type:  
  BUG  
Influences：  
   Do not close the myqlConnection when the DDL is partly sent
> #797 do not close the myqlConnection when the DDL is partly sent

- src/main/java/com/actiontech/dble/config/loader/xml/SystemConfigLoader.java
Reason:  
  BUG #905
Type:  
  BUG
Influences：  
  fix dble error when property fakeMySQLVersion in server.xml is invalid.
> dble error when property fakeMySQLVersion in server.xml is invalid

- src/main/java/com/actiontech/dble/config/loader/xml/FirewallConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/util/BooleanUtil.java
Reason:  
  BUG #905
Type:  
  BUG
Influences：  
  strengthen property check in server.xml
> strengthen property check in server.xml

- src/main/java/com/actiontech/dble/backend/mysql/store/DistinctLocalResult.java
- src/main/java/com/actiontech/dble/util/RBTreeList.java
Reason:  
  BUG #889 
Type:  
  BUG  
Influences：  
   Make sorting take effect in select distinct xx ... order by xx
> #889 Make sorting take effect in select distinct xx ... order by xx

- src/main/java/com/actiontech/dble/statistic/stat/SqlResultSet.java
- src/main/java/com/actiontech/dble/statistic/stat/SqlResultSizeRecorder.java
- src/main/java/com/actiontech/dble/statistic/stat/UserStatAnalyzer.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  avoid thread safety when user execute 'show @@sql.resultset'
> avoid thread safety when user execute 'show @@sql.resultset'

- src/main/java/com/actiontech/dble/plan/node/TableNode.java
- src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  optimize global table when there are all nosharding table and global table in sql
> optimize global table when there are all nosharding table and global table in query

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/WhereUnit.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/test/java/com/actiontech/dble/route/RouteWithOrTest.java
Reason:  
  BUG #801
Type:  
  BUG  
Influences：  
   Re-adjusted the handling of OR conditions
> Route with OR optimized

- src/main/java/com/actiontech/dble/server/handler/DropViewHandler.java
Reason:  
  BUG #920 
Type:  
  BUG  
Influences：  
   drop view Ignore the symbol  '`'
> #920 drop view Ignore the symbol  '`'

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowDdlState.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
  Improve #887
Type:  
  Improve  
Influences：  
  add 'show @@ddl' management cmd that show ddl in progress
> add 'show @@ddl' management cmd that show ddl in progress

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeHandler.java
- src/main/java/com/actiontech/dble/btrace/provider/ComplexQueryProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BtraceComplexCostTime.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/statistic/stat/QueryTimeCost.java
Reason:  
  Improve  :add complex query general btrace
Type:  
  Improve  #925 
Influences：  
   add complex query general btrace
> add complex query general btrace

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
Reason:  
  Improve #852
Type:  
    Improve  
Influences：  
  add 'show @@ddl' and 'kill @@ddl_lock' in show @@help
> add 'show @@ddl' and 'kill @@ddl_lock' in show @@help

- pom.xml
Reason:  
  Improve  #853
Type:  
  Improve  
Influences：  
   new log file gc.log create in logs
> add gc log to wrapper.conf

- README.md
update ActionTech keyword hyperlinks to https://github.com/actiontech/dble/issues
> update ActionTech keyword hyperlinks

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
Reason:  
  BUG #933 
Type:  
  BUG  
Influences：  
   Check getIncrementKeyIndex only the table is AutoIncrement
> #933 check getIncrementKeyIndex only the table is AutoIncrement

- docker-images/quick-start/Dockerfile
- docker-images/wait-for-it.sh
Reason:  
  Improve #.444
Type:  
  Improve  
Influences：  
   add wait script for docker-compose
> add wait script for docker-compose

- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/test/java/com/actiontech/dble/route/DruidMysqlRouteStrategyTest.java
Reason:  
  Improve #947 
Type:  
  Improve  
Influences：  
  see #947
> #947 primary key cache

- src/main/java/com/actiontech/dble/plan/common/item/function/ItemFuncKeyWord.java
- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncTrim.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
- src/test/java/demo/test/Testparser.java
Reason:  
  BUG #953  
Type:  
  BUG 
Influences：  
   fix trim bug by druid change
> issue #953

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UDdlChildResponse.java
- src/main/java/com/actiontech/dble/meta/DDLChildListener.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidTruncateTableParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  Improve #936
Type:  
  Improve  
Influences：  
   Change ddl meta change logic
> #936 change ddl meta change logic

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG #942
Type:  
  BUG  
Influences：  
   limit connection count in idle create
> #942 limit connection count in idle create

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG #954
Type:  
  BUG  
Influences：  
   Null check add for loop
> #954 add check idle table null check

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #954 
Type:  
  BUG  
Influences：  
   Add try/catch when asynchronous close mysqlConnection
> #954 add try/catch when asynchronous close mysqlConnection

- src/main/java/com/actiontech/dble/server/response/ShowColumns.java
Reason:  
  Improve #958  
Type:  
  Improve  
Influences：  
   Compatible with "show columns in ..."
> #958 Compatible with "show columns in ..."

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/MysqlVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
  BUG #964 #965
Type:  
Influences：  
   fix bug when where or on contains other schema when using global optimizer
> Issue 964/965

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG #967 #968
Type:  
  BUG  
Influences：  
   change median column into schema.table.column
> #968 #967 change median column into schema.table.column

- src/main/java/com/actiontech/dble/plan/node/MergeNode.java
Reason:  
  BUG #970
Type:  
  BUG 
Influences：  
   fix :union not set ReferTable for item
> item plannode of mergeNode #970

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/manager/handler/ReloadHandler.java
- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/SchemaMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/old/MultiTableMetaHandler.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseReload.java
Reason:  
  Improve #944  
Type:  
  Improve
Influences：  
    reload @@metadata , keep reloading all metadata, and suppert these filter:
where schema=? and table=?
where schema=?
where table in ('schema1.table1','schema2.table2',...)
> add filter for reload @@metadata

- docker-images/docker-compose.yml
Reason:  
  Improve  docker-compose.yml 
Type:  
  BUG 
Influences：  
   docker-compose.yml update
>  docker-compose.yml update

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseReload.java
Reason:  
  Improve #976 
Type:  
    Improve  
Influences：  
  fix 'reload @@metadata'
> fix 'reload @@metadata'

- src/main/java/com/actiontech/dble/plan/common/item/function/ItemFuncKeyWord.java
- src/main/java/com/actiontech/dble/plan/common/item/function/castfunc/ItemFuncConvCharset.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
- src/test/java/demo/test/Testparser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix convert report error
> fix parser convert

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  Improve #946  
Type:  
  Improve  
Influences：  
   Improve reload action，not reload all metadata
>  reload metadata when reload config #946

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG #898
Type:  
  BUG 
Influences：  
   fix when in transaction,global table has use a random node,next select query will use the same node
> #989 global table back conn switch in transaction

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/old/MultiTableMetaHandler.java
Reason:  
  Improve #944.  
Type:  
  Improve  
Influences：  
  fix incorrect 'reload @@metadata' reload time
> fix incorrect 'reload @@metadata' reload time

- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UDistrbtLockManager.java
- src/main/java/com/actiontech/dble/manager/response/KillDdlLock.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  issue #888
Type:  
Issue  
Influences：  
  modify tip of 'kill ddl' cmd
> modify tip of 'kill ddl' cmd

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
Reason:  
  BUG #994 
Type:  
  BUG  
Influences：  
   Add sql syntax check when try to insert
> #994 add sql syntax check when try to insert

- pom.xml
- src/main/java/com/actiontech/dble/config/Versions.java
- src/main/java/com/actiontech/dble/config/Versions.template
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/UcorePathUtil.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UXmlRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UXmlSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/ucoreprocess/loader/UXmlServerLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/Rules.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/Schemas.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/Server.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/schema/schema/Table.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/RulesxmlTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/SchemasxmlTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/ServerxmlTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/RuleszkToxmlLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/SchemaszkToxmlLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/ServerzkToxmlLoader.java
- src/main/java/com/actiontech/dble/util/KVPathUtil.java
- src/main/resources/rule.dtd
- src/main/resources/rule_template.xml
- src/main/resources/schema.dtd
- src/main/resources/schema_template.xml
- src/main/resources/server.dtd
- src/main/resources/server_template.xml
Reason:  
  Improve #986  
Type:  
  Improve  
Influences：  
   Add version attribute for rule/schema/server
   Add incrementColumn for cluster config object
> add version attribute for rule/schema/server

- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
Reason:  
  BUG #986 
Type:  
  BUG  
Influences：  
   Remove duplicate warning log
> #986 remove duplicate warning log

- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/RuleszkToxmlLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/SchemaszkToxmlLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/ServerzkToxmlLoader.java
Reason:  
  BUG #986 
Type:  
  BUG  
Influences：  
  Add null check when try pull from zk
> #986 add null check when try pull from zk

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/handler/ShowProcesslistHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
  Improve #975.  
Type:  
     Improve  
Influences：  
  add manager cmd 'show processlist'
> add manager cmd 'show processlist'

- pom.xml
Reason:  
  Improve #1013 
Type:  
  Improve  
Influences：  
  
> fix #1013  standardized maven-compiler-plugin with JDK 8

- src/main/java/com/actiontech/dble/config/ErrorCode.java
- src/main/java/com/actiontech/dble/manager/handler/ShowProcesslistHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowProcessList.java
Reason:  
  BUG #1018 
Type:  
  BUG
Influences：  
  show @@processlist hang when acquiring backend connection  unsuccessfully！
> show @@processlist hang when acquiring backend connection unsuccessfully

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   Return info when catch the exception in subquery build，no existing case for the issue
> return info when catch the exception in subquery build

- src/main/java/com/actiontech/dble/plan/node/NoNameNode.java
- src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java
Reason:  
  BUG #1023
Type:  
  BUG  
Influences：  
   add null check and set NoNameNode shardingNodes as all dataNodes
> #1023 add null check and set NoNameNode shardingNodes as all dataNodes

- README.md
- docs/dble_quick_start_docker.md
- docs/dble_start_docker_compose.md
Reason:  
  Improve doc 
Type:  
  Improve  
Influences：  
   Improve doc
> quick start

- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/ConfigStatusListener.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
- src/main/java/com/actiontech/dble/meta/DDLChildListener.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/ViewChildListener.java
Reason:  
   Improve:add_btrace_support_for_zk
Type:  
  Improve  
Influences：  
   delayAfterGetNotice
   delayBeforeSlaveRollback
   delayAfterSlaveRollback
   delayBeforeSlaveReload
   delayAfterSlaveReload
   delayAfterReloadLock
   delayAfterMasterLoad
   delayBeforeDeleteReloadLock
   delayAfterMasterRollback
   delayBeforeDeleterollbackLock
   delayAfterGetDdlNotice
   delayBeforeUpdateMeta
   delayBeforeDdlResponse
   delayAfterDdlLockMeta
   delayAfterDdlExecuted
   delayBeforeDdlNotice
   delayBeforeDdlNoticeDeleted
   delayWhenReponseViewNotic
> add_btrace_support

- src/main/java/com/actiontech/dble/manager/response/ShowProcessList.java
Reason:  
  BUG #1041
Type:  
  BUG
Influences：  
  field type doesn't match with filed value in show processlist
> field type doesn't match with filed value in show processlist

- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/RulesxmlTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/SchemasxmlTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/ServerxmlTozkLoader.java
Reason:  
  BUG #986 
Type:  
  BUG  
Influences：  
   fix upload zk version NP exception
> #986  fix upload zk version NP exception

- src/main/java/com/actiontech/dble/net/FrontendConnection.java
Reason:  
  Improve #1045
Type:  
  Improve  
Influences：  
   Change load data into ComplexQueryExecutor
> #1045 change load data into ComplexQueryExecutor

- src/main/java/com/actiontech/dble/server/handler/DropViewHandler.java
Reason:  
  Improve #1032
Type:  
  Improve  
Influences：  
   Refactoring drop view handler
> #1032 Refactoring drop view handler

- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/BinDataPathChildrenCacheListener.java
Reason:  
  Improve #1016  
Type:  
  Improve  
Influences：  
   no need to delete the dnindex file
> #1016 no need to delete the dnindex file

- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/TxState.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XASessionCheck.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/KillXASession.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/manager/response/ShowXASession.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  Improve #1052
Type:  
  Improve  
Influences：  
  improve retry policy when xa commit or rollback failed
> improve retry policy when xa commit or rollback failed

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
- src/main/java/com/actiontech/dble/btrace/provider/XaDelayProvider.java
- src/main/java/com/actiontech/dble/btrace/script/BtraceXaDelay.java
Reason:  
  Improve #1052.  
Type:  
  Improve  
Influences：  
  add btrace script for xa
> add btrace script for xa

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/manager/response/ShowDataSource.java
Reason:  
  BUG #1064 
Type:  
  BUG  
Influences：  
   show @@datasource ACTIVE show real active connections
> #1064 correct active into totalCount in physicalDatasource

- src/main/java/com/actiontech/dble/plan/Order.java
Reason:  
   Improve #1060 
Type:  
  Improve  
Influences：  
   remove useless Order for complex query
> order by add equals function #1160

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
Reason:  
  BUG #1074
Type:  
  BUG
Influences：  
   join out order calc
> Issue #1074

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/plan/optimizer/OrderByPusher.java
Reason:  
   Improve #1074  #1060  
Type:  
  Improve  
Influences：  
   remove useless order
> #1074 join order 3

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlHandler.java
Reason:  
  BUG improt from #1059 #1058
Type:  
  BUG 
Influences：  
   fix ddl query log
> ddl conn may setbackend first

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  BUG #1058 
Type:  
  BUG
Influences：  
   join may lost handler finish time
> issue #1058

- dble_checkstyle_suppression.xml
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/alarm/Alert.java
- src/main/java/com/actiontech/dble/alarm/AlertBlockQueue.java
- src/main/java/com/actiontech/dble/alarm/AlertSender.java
- src/main/java/com/actiontech/dble/alarm/AlertTask.java
- src/main/java/com/actiontech/dble/alarm/AlertUtil.java
- src/main/java/com/actiontech/dble/alarm/NoAlert.java
- src/main/java/com/actiontech/dble/alarm/ToResolveContainer.java
- src/main/java/com/actiontech/dble/alarm/UcoreAlert.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/recovery/impl/FileSystemRepository.java
- src/main/java/com/actiontech/dble/cluster/bean/ClusterAlertBean.java
- src/main/java/com/actiontech/dble/manager/handler/CreateDatabaseHandler.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/AbstractTablesMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/GetNodeTablesHandler.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/TablesMetaCheckHandler.java
- src/main/java/com/actiontech/dble/meta/table/old/AbstractTableMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/old/SchemaDefaultNodeTablesHandler.java
- src/main/java/com/actiontech/dble/meta/table/old/TableMetaCheckHandler.java
- src/main/java/com/actiontech/dble/server/status/AlertManager.java
- src/main/java/com/actiontech/dble/server/util/GlobalTableUtil.java
Reason:  
  Improve #1079.  
Type:  
  Improve  
Influences：  
  set alert info into a blockqueue
>  #1079 set alert info into a blockqueue

- src/main/java/com/actiontech/dble/net/handler/FrontendCommandHandler.java
Reason:  
  BUG #1093  
Type:  
  BUG  
Influences：  
   clear buffer when COM_STMT_RESET
> #1093 clear queue when COM_STMT_RESET

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesCheckMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesInitMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/SchemaMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/SingleNodeTablesMetaInitHandler.java
Reason:  
  BUG #1098  
Type:  
  BUG  
Influences：  
   Refactoring the tableStructureCheckTask
> #1098 Refactoring the tableStructureCheckTask

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACheckHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
Reason:  
  BUG #1084
Type:  
  BUG  
Influences：  
  when retrying to commit xa, kill mysql connection holding xa resource
> #1084 - when retrying to commit xa, kill mysql connection holding xa resource

- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
Reason:  
  Improve #1109.  
Type:  
  Improve  
Influences：  
  add 'default' value for table attribute type in schema.xml
> #1109 - add 'default' value for table attribute type in schema.xml

- src/main/java/com/actiontech/dble/plan/optimizer/FilterPusher.java
Reason:  
  BUG #1103
Type:  
  BUG
Influences：  
   fix push aggregate from  outside of union
> #1103 aggregate outside of union

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/UnLockTablesHandler.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG #1106.
Type:  
  BUG
Influences：  
  mysql backend connection leak
> #1106 - mysql backend connection leak

- src/main/java/com/actiontech/dble/meta/table/MultiTablesCheckMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesInitMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/MultiTablesMetaHandler.java
Reason:  
  BUG #1098
Type:  
Influences：  
   fix when check metadata, memory check should be report
> when check metadata, memory check should be report

- src/main/java/com/actiontech/dble/net/handler/FrontendCommandHandler.java
fix the 'ClosedChannelException' error when the client set useServerPrepStmts=true
> fix the 'ClosedChannelException' error when the client set useServerPrepStmts=true

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
Reason:  
  BUG #1114.
Type:  
  BUG
Influences：  
  add TX_PREPARING_STATE state for mysql connection in xa transaction
> #1114 - add TX_PREPARING_STATE state for mysql connection in xa transaction

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG #1100 
Type:  
  BUG  
Influences：  
   optimize the view initialize message
> #1100 optimize the view initialize message

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG #1120.  
Type:  
Influences：  
   fix push func where filter and add alias
> push filter #1120

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1048
Type:  
  BUG
Influences：  
   when table contains autoincrement column, load data can not generate sequence for column value
> #1048 - when table contains autoincrement column, load data can not generate sequence for column value

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG #1132
Type:  
  BUG  
Influences：  
   Set the time unit to uppercase
> #1132 Set the time unit to uppercase

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  import from #1048
Type:  
  BUG
Influences：  
  avoid NPE for no sharding table
> #1048 - avoid NPE for no sharding table

- src/main/java/com/actiontech/dble/manager/response/ShowBinlogStatus.java
Reason:  
  BUG #1088
Type:  
  BUG
Influences：  
   all physical database are not exists
> all physical database are not exists #1088

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #1155 
Type:  
  BUG  
Influences：  
  add multiStatement check when session in a transaction
> #1155 add multiStatement check when session in a transaction

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XARecoverCallback.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1116
Type:  
  BUG
Influences：  
   xa transaction contains only complex select and complex select contains some datanode for more than one time
> xa tx only contains complex select #1116

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalAutoRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAAutoRollbackNodesHandler.java
Reason:  
  BUG #1166
Type:  
  BUG
Influences：  
   fix #1166
Test:
* With XA
* Without XA
> #1166 fix missing adding adll error connection to  errConnection list

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlHandler.java
Reason:  
  BUG #1168
Type:  
  BUG
Influences：  
   change method usage in MultiNodeDdlHandler to release the ddl lock when session close
> #1168 change method usage

- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
Reason:  
  bug #1118 
Type:  
   Bug  
Influences：  
   fix return msg for closed conn
> return msg #1118

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1158 
Type:  
  BUG
Influences：  
   fix xx
> #1158 fix connection leaking problem

- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  BUG #1177   
Type:  
  BUG  
Influences：  
   SetTestJob now would clear the resource and write out a errorMsg instead of close frontendConnection
> Imporve SetTestJob errorMsg

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
  BUG #1170.  
Type:  
  BUG
Influences：  
  When any xa node fail to prepare, dble auto rollback and show error instead ok
> #1170 - When any xa node fail to prepare, dble auto rollback and show error instead ok

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLDataSource.java
- src/main/java/com/actiontech/dble/util/PasswordAuthPlugin.java
Reason:  
  when dble try to connect mysql/8.0,the code about testConnection is incorrect and imperfect，fix it.
Type:  
  BUG
Influences：  
   fix the contradiction when dble run testConnection.
> #1134 #1187 update Code

- .github/ISSUE_TEMPLATE/bug_report.md
Reason:  
Type:  
Influences：  
   fix xx
> delete useless "/label..."

- src/main/assembly/bin/init_ucore_data.sh
Reason:  
  BUG #1055.  
Type:  
  BUG  
Influences：  
   init script update
> #1055 init script update

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1203 
Type:  
  BUG
Influences：  
   If table is locked, the backend conn should not be released.
> If table is locked, the backend conn should not be released #1203

- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  Improve #1105  
Type:  
  Improve  
Influences：  
   make error message easy to understand
> easy to understand #1105

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG #1197
Type:  
  BUG
Influences：  
   outer join filter can not treat as where filter
> outer join filter can not be treated as where filter #1197

- src/main/java/com/actiontech/dble/net/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/net/mysql/HandshakeV10Packet.java
Reason:  
  Improve #1172
Type:  
  Improve  
Influences：  
   Return message "GET IOException when registerWrite,may be just a heartbeat from SLB :..." when use aliyun SLB. Also adjust to heartbeat like ACK - RST/ACK
> #1172 return less message for SLB heartbeat

- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/sqlengine/MultiSQLJob.java
- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
  BUG #1213
Type:  
  BUG
Influences：  
  check xid when starting dble
> #1213 - check xid when starting dble

- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
  BUG
Type:  
  BUG 
Influences：  
  dble hang when user create table
> dble hang when user create table

- src/main/java/com/actiontech/dble/route/sequence/handler/FetchMySQLSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/SequenceVal.java
Reason:  
  BUG #1227
Type:  
  BUG
Influences：  
  cause NPE when dble generates global sequence by MySQL-offset-step
> cause NPE when dble generates global sequence by MySQL-offset-step

- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
Reason:  
  BUG #1231  
Type:  
  BUG  
Influences：  
   add additional protection for SQLJob.dofinish
> #1231 add additional protection for SQLJob.dofinish

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
  BUG #1084 .
Type:  
  BUG  
Influences：  
  check xid when rollback error
> #1084 - check xid when rollback error

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG Inner210
Type:  
  BUG  
Influences：  
   Change connection test after AlertManager start
> Inner 210 DBLE_TEST_CONN_FAIL alert disappear

- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  BUG #1236 . 
Type:  
  BUG
Influences：  
  implement of prepared statement
> unknown pStmtId error when close one preparedstatement that statement is same with another in one connection

- src/main/java/com/actiontech/dble/manager/handler/SelectHandler.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG #1245 
Type:  
  BUG 
Influences：  
   SQLjob use the conn without any schema
> default conn #1245

- src/main/java/com/actiontech/dble/meta/table/MultiTablesMetaHandler.java
Reason:  
  BUG #1231 
Type:  
  BUG  
Influences：  
   Change the linkedList in Map into synchronized
> add list synchronized

- README.md
Reason:  
  change South-West China Contact
Type:  
  Improve  
Influences：  
   change South-West China Contact
> change South-West China Contact 

- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG #1255
Type:  
  BUG
Influences：  
   join filter is expr
> #1255 order by is expr

- src/main/java/com/actiontech/dble/route/RouteService.java
- src/main/java/com/actiontech/dble/route/RouteStrategy.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/impl/DefaultRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/DruidParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidLockTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateIndexParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropIndexParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidTruncateTableParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG #1251
Type:  
  BUG  
Influences：  
   Add explain support when try to route the sql
> #1251 add explain support when try to route the sql

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG #1256 
Type:  
  BUG
Influences：  
   alias not remove ·
> #1256 about `

- src/main/java/com/actiontech/dble/server/parser/ServerParseSelect.java
- src/test/java/com/actiontech/dble/parser/ServerParserTest.java
Reason:  
  BUG #960
Type:  
  BUG  
Influences：  
   fix inner parse about database()/current_user
> Issue 960 fix

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/DistinctHandler.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG #960
Type:  
  BUG  
Influences：  
   DistinctHandler would use serverConnection.charset when the BackendConnection is NULL
  NoSharding check would treat the Inner-func as a sharding Event
> #960 NPE can be cause by the thread order & isNoSharding 

- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/server/user/privilege/Schema.java
- src/test/java/com/actiontech/dble/cluster/xmlTokv/XmlServerLoaderTest.java
- src/test/resources/server.xml
Reason:  
  inner BUG 221
Type:  
  BUG
Influences：  
  when parsing json to user bean list in cluster, the bean list is always empty
> when parsing json to user bean list in cluster, the bean list is always empty

- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/CreateDatabaseHandler.java
- src/main/java/com/actiontech/dble/server/handler/FlushTableHandler.java
- src/main/java/com/actiontech/dble/server/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParseShow.java
- src/main/java/com/actiontech/dble/server/response/ShowCreateDatabase.java
- src/main/java/com/actiontech/dble/server/response/ShowCreateView.java
- src/test/java/com/actiontech/dble/parser/ServerParseTest.java
Reason:  
  Improve #1264.  
Type:  
  Improve  
Influences：  
  1.SHOW CREATE DATABASE IF NOT EXISTS `schema1`
2.CREATE DATABASE /!32312 IF NOT EXISTS/ `schema1` /*!40100 DEFAULT CHARACTER SET latin1 */
3. FLUSH /*!40101 LOCAL */ TABLES
4. FLUSH TABLES WITH READ LOCK
5. – MysqlDump
> #1264 - support statement of create database, show create database, flush table and '--' comment style

- src/main/java/com/actiontech/dble/backend/mysql/view/FileSystemRepository.java
Reason:  
  BUG #Inner 224
Type:  
  BUG  
Influences：  
   fix json out put for schema has no view
> fix json out put for schema has no view

- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  Improve #1264.  
Type:  
  Improve  
Influences：  
  skip flush statement in explain
> skip flush statement in explain

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/resources/server_template.xml
Reason:  
  BUG #1288
Type:  
  BUG
Influences：  
   fix other join without on
> other join without on #1288

- pom.xml
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ProblemReporter.java
- src/main/java/com/actiontech/dble/config/Versions.java
- src/main/java/com/actiontech/dble/config/Versions.template
- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
- src/main/resources/rule_template.xml
- src/main/resources/schema_template.xml
- src/main/resources/server_template.xml
Reason:  
  Improve #1260 
Type:  
  Improve  
Influences：  
   Change config version from x.xx.x.x into x.y and never block the dble start up
> #1260  Refactoring attribute 'version' in xml config

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG #1280
Type:  
  BUG   
Influences：  
    Check a table is view when the table has a schema name above
> #1280 check a table is view when the table has a schema name above

- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowReloadStatus.java
- src/main/java/com/actiontech/dble/meta/ReloadStatus.java
Reason:  
  BUG #1263 
Type:  
  BUG  
Influences：  
   change message & fix rollback not call reload finish
> #1263 change message & fix rollback not call reload finish

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/savepoint/SavePointHandler.java
Reason:  
  BUG
Type:  
  BUG 
Influences：  
  cause npe when user add savepoint that name is same with the first savepoint
> cause npe when user add savepoint that name is same with the first savepoint

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG #1301.  
Type:  
  BUG  
Influences：  
  schema and table name don't turn into lowercase when lower_case_table_names = 1, so cause npe when dble get schema matadata.
> import from issue #1280

- src/main/java/com/actiontech/dble/cluster/response/ConfigStatusResponse.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/ConfigStatusListener.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
Reason:  
  BUG #1263  
Type:  
  BUG  
Influences：  
   fix rollback config cluster response 
  
>  #1263 fix rollback config cluster response

- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
Reason:  
  Improve #1260 
Type:  
  Improve  
Influences：  
   Change all Xml-version warning to notice to fit the production environment
> #1260 change version notice level to notice

- src/main/java/com/actiontech/dble/manager/response/CheckFullMetaData.java
- src/main/java/com/actiontech/dble/manager/response/KillDdlLock.java
- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
- src/main/java/com/actiontech/dble/manager/response/ShowTableAlgorithm.java
- src/main/java/com/actiontech/dble/manager/response/ShowTableDataNode.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/main/java/com/actiontech/dble/server/response/ShowColumns.java
- src/main/java/com/actiontech/dble/server/response/ShowIndex.java
- src/main/java/com/actiontech/dble/server/response/ShowTableStatus.java
- src/main/java/com/actiontech/dble/server/response/ShowTablesStmtInfo.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG #1241 
Type:  
  BUG  
Influences：  
the special characters be supported in schema name and command below are influenced
+ kill @@ddl_lock
+ check full @@metadata
+ reload @@metadata
+ show @@algorithm
+ show @@dataNodes
+ show columns from ..
+ show index from ...
+  show full tables ...
+ show tables status form
>  #1241 support special characters in schema name

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
Reason:  
  Improve #1300 .  
Type:  
  Improve  
Influences：
> #1300 Incorrect comment in initSource method of class PhysicalDBPool

- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
Reason:  
  BUG #1241   
Type:  
  BUG  
Influences：  
   change reload @@metadata Syntax into 'where table in ('schema.table')'
> #1241 change reload @@metadata Syntax

- src/main/java/com/actiontech/dble/cluster/response/ConfigStatusResponse.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/ConfigStatusListener.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
Reason:  
  BUG #1263 
Type:  
  BUG  
Influences：  
   add a parameter to distinct the call method
> #1263 add a parameter to distinct the call method

- src/main/java/com/actiontech/dble/config/loader/xml/XMLRuleLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLServerLoader.java
Reason:  
  Improve #1260
Type:  
  Improve  
Influences：  
   Only notice message changed
> #1260 change notice for version check

- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/main/java/com/actiontech/dble/server/parser/ServerParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParseStart.java
- src/test/java/com/actiontech/dble/parser/ServerParserTest.java
Reason:  
  Improve #1264 .  
Type:  
  Improve  
Influences：  
  1. --;
2. -- -----------------\n
-- nfadslfadf\n
insert into ...
3. start transaction /#! ****/;
> strength to support -- comment style and start transaction with hint

- src/main/java/com/actiontech/dble/config/model/UserPrivilegesConfig.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/manager/response/ShowUser.java
- src/main/java/com/actiontech/dble/manager/response/ShowUserPrivilege.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/test/java/com/actiontech/dble/parser/ManagerParserTest.java
Reason:  
  Improve #759 .  
Type:  
  Improve  
Influences：  
  1. show @@user
2. show @@user.privilege
> add manager cmd of show @@user and show @@user.privilege

- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/handler/FrontendCommandHandler.java
- src/main/java/com/actiontech/dble/net/mysql/EOFPacket.java
Reason:  
   Improve #1326
Type:  
   Improve  
Influences：  
   support set com_set_option
> com_set_option #1326

- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/test/resources/schema.xml
Reason:  
  BUG #1322 
Type:  
  BUG  
Influences：  
   add dataNodes check for the same database&dataHost
> #1322 add dataNodes check for the same database&dataHost

- copyResources.bat
- src/main/java/com/actiontech/dble/manager/response/ShowUserPrivilege.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
Reason:  
  Improve #759 .  
Type:  
  Improve  
Influences：  
  avoid npe when schema does't exist int privilege
> avoid npe when schema does't exist in privilege

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
Reason:  
  BUG #1241
Type:  
  BUG  
Influences：  
  change reload @@metadata help message
> #1241 change reload @@metadata help message

- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/test/java/com/actiontech/dble/parser/ServerParseTest.java
Reason:  
  BUG #1332  
Type:  
  BUG  
Influences：  
   support CREATE FUNCTION with hint
> #1332 support CREATE FUNCTION with hint

- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG #1327
Type:  
  BUG 
Influences：  
   fix func contains more columns
> complex column #1327

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  Improve #1264 .  
Type:  
  Improve  
Influences：
support the following statement:
  /*
Navicat Premium Data Transfer
Source Server         : mysql
Source Server Type    : MySQL
Source Server Version : 50713
Source Host           : 10.186.60.30:7144
Source Schema         : schema1
Target Server Type    : MySQL
Target Server Version : 50713
File Encoding         : 65001
Date: 08/07/2019 16:01:38
*/
SET NAMES utf8mb4;
> unsupport set statement when there are comments in statement

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidLockTableParser.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG #1221 
Type:  
  BUG  
Influences：  
   Support lock on view in dble，a lock on view would lock all the related table
> #1221 support lock on view in dble

- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG #1351
Type:  
  BUG
Influences：  
   fix nosharding table subquery contains union
> nosharding table subquery contains union #1351

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/sqlengine/HeartbeatSQLJob.java
Reason:  
  BUG #1354 
Type:  
  BUG
Influences：  
   fix heartbeat stop
> #1354 heartbeat stop

- src/main/java/com/actiontech/dble/manager/response/ShowDataSource.java
- src/main/java/com/actiontech/dble/manager/response/ShowDatasourceCluster.java
- src/main/java/com/actiontech/dble/manager/response/ShowDatasourceSyn.java
- src/main/java/com/actiontech/dble/manager/response/ShowDatasourceSynDetail.java
Reason:  
  Improve #759.  
Type:  
  Improve  
Influences：  
  add datahost column in command about datasource
> add datahost column in command about datasource

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/NotInHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/TwoTableComparator.java
- src/main/java/com/actiontech/dble/plan/common/item/function/operator/cmpfunc/util/ArgComparator.java
Reason:  
  BUG #1229 
Type:  
  BUG 1229 
Influences：  
   fix case Insensitive for join
> #1229 case Insensitive for join

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  Improve #890 .  
Type:  
  Improve  
Influences：  
   Make the limit effective condition become consistent
> #890 Make the limit effective condition become consistent

- src/main/java/com/actiontech/dble/cluster/AbstractClusterSender.java
- src/main/java/com/actiontech/dble/cluster/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/impl/ushard/UshardSender.java
Reason:  
  BUG Inner-211  
Type:  
  BUG Inner 211
Influences：  
   reconnect in ushard cluster
> Inner211 reconnect in ushard cluster

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPoolDiff.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:  
  BUG #1341 reload config stop heartbeat
Type:  
  BUG
Influences：  
   reload config
> host_calc_for_heartbeat

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/handler/AuthUtil.java
- src/main/java/com/actiontech/dble/net/handler/FrontendAuthenticator.java
- src/main/java/com/actiontech/dble/net/handler/FrontendCommandHandler.java
- src/main/java/com/actiontech/dble/net/mysql/AuthPacket.java
- src/main/java/com/actiontech/dble/net/mysql/ChangeUserPacket.java
- src/main/java/com/actiontech/dble/net/mysql/MySQLPacket.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  Improve #1356 
Type:  
  Improve  
Influences：  
   support com_change_user,com_reset_connection
> #1356 com_change_user,com_reset_connection

- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FilePath.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysLog.java
- src/main/java/com/actiontech/dble/net/handler/BackendAsyncHandler.java
- src/main/java/com/actiontech/dble/plan/common/MySQLcom.java
- src/main/java/com/actiontech/dble/plan/common/field/num/FieldBit.java
- src/main/java/com/actiontech/dble/plan/common/item/function/timefunc/ItemFuncMaketime.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/response/SptExecute.java
- src/main/java/com/actiontech/dble/server/response/SptPrepare.java
- src/main/java/com/actiontech/dble/util/Security.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   https://lgtm.com/projects/g/actiontech/dble/alerts/?mode=list&severity=warning
> resolve part of lgtm warnning

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG #1322 
Type:  
  BUG  
Influences：  
   limit unknown function check so that NoNameNode would send the unknown function to MySQL
> #1332 limit unknown function check

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidLockTableParser.java
Reason:  
  BUG #1374 . 
Type:  
  BUG
Influences：  
  dble reports that table doesn't exist when current schema is different from lock schema
> dble reports that table doesn't exist when current schema is different from lock schema

- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:  
  BUG #1383
Type:  
  BUG  
Influences：  
   Recycling new dataHost when error in apply new config
> #1383 Recycling new dataHost when error in apply new config

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
Reason:  
  import from #1380
Type:  
  BUG  
Influences：  
  when doing nothing in xa transaction, begin statement hang
> when doing nothing in xa transaction, begin statement hang

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
(cherry picked from commit e54eae5f9077f20bdd485dbb8fabb80efcb1dd93)
> import from 1380 (#1389)

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   fix implicit_dts may lead conns
> issue_implicit_dts_bug

- src/main/java/com/actiontech/dble/backend/BackendConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG   
Type:  
  BUG 
Influences：  
   fix implicit dts bug2
> implicit_dts_bug2

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1400 
Type:  
  BUG
Influences：  
   fix close may leaked
> #1400 close may leaked

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1400
Type:  
  BUG
Influences：  
    close may lead handler return twice
> #1400 close may lead handler return twice

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/UnLockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AbstractCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
  BUG #1400
Type:  
  BUG 
Influences：  
   fix if mysql killed or timeout while sending results
> for close safe

- src/main/java/com/actiontech/dble/config/ServerPrivileges.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/handler/AuthUtil.java
- src/main/java/com/actiontech/dble/net/handler/FrontendAuthenticator.java
- src/main/java/com/actiontech/dble/net/handler/FrontendPrivileges.java
Reason:  
  BUG #1277 #1398 .
Type:  
  BUG
Influences：  
  fix that manager user can login by business port
> fix that manager user can login by business port

- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG #1375.
Type:  
  BUG  
Influences：  
  strength backquote
> strength backquote

- src/main/java/com/actiontech/dble/plan/common/item/function/castfunc/ItemCharTypeCast.java
- src/main/java/com/actiontech/dble/plan/common/item/function/castfunc/ItemNCharTypeCast.java
Reason:  
  BUG #1379
Type:  
  BUG
Influences：  
   cast char,cast nchar
> #1379 cast char without N

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/singleton/OnlineStatus.java
Reason:  
  Improve #1409  
Type:  
  Improve  
Influences：  
  Cluster restart online status check
>  #1409 Cluster restart online status check

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/manager/handler/CreateDatabaseHandler.java
- src/main/java/com/actiontech/dble/plan/common/item/function/operator/cmpfunc/ItemFuncRegex.java
Reason:  
  BUG #1385 #1386 . 
Type:  
  BUG
Influences：  
  create database @@dataNode ='dn......'
use \`dbname\`
> fix that dbname can't contains special character and function regex is invalid

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG #1419 .
Type:  
  BUG
Influences：  
  error : select * from test1 a, test1 b where a.id=1
> import from backquote

- src/main/java/com/actiontech/dble/server/handler/MysqlInformationSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
Reason:  
  BUG #1239 . 
Type:  
  BUG
Influences：  
  avoid error when user use pma to connect dble
> avoid error when user use pma to connect dble

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  import from backquote in subquery
> import from backquote in subquery

- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
Reason:  
  BUG #1429.
Type:  
  BUG  
Influences：  
  can't find column when sql contains subquery
> can't find column when sql contains subquery

- src/main/java/com/actiontech/dble/cluster/response/ConfigStatusResponse.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/ConfigStatusListener.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/ConfStatus.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
- src/test/java/com/actiontech/dble/ConfigInitializerTest.java
Reason:  
  BUG #1267
Type:  
  BUG
Influences：  
   fix reload @@config error
> treat reload @@config as reload @@config_all #1267

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/savepoint/SavePointHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
Reason:  
  BUG #1428 and fix ci.
Type:  
  BUG
Influences：  
  fix savepoint about ci
> fix ci about savepoint

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/DbleStartup.java
- src/main/java/com/actiontech/dble/cluster/AbstractClusterSender.java
- src/main/java/com/actiontech/dble/cluster/bean/InstanceOnline.java
- src/main/java/com/actiontech/dble/cluster/listener/ClusterOffLineListener.java
- src/main/java/com/actiontech/dble/singleton/OnlineStatus.java
Reason:  
  BUG #1409 Inner 235
Type:  
  BUG  
Influences：  
   Change the online cluster init and rebuild
   Add a hook to clean the online status when dble shut down
> Issue 1409

- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/schema/schema/ChildTable.java
- src/main/resources/schema.dtd
- src/test/resources/schema.dtd
Reason:  
  BUG #1364
Type:  
  BUG  
Influences：  
  Add incrementColumn/needAddLimit for clildTable
> Issue 1364

- src/main/java/com/actiontech/dble/net/handler/ConcurrentFrontEndHandlerRunnable.java
- src/main/java/com/actiontech/dble/net/handler/FrontEndHandlerRunnable.java
- src/main/java/com/actiontech/dble/net/handler/WriteToBackendRunnable.java
Reason:  
  Improve #1440 
Type:  
  Improve  
Influences：  
   Let the thread hold the ThreadUsage Object out of the loop
>  #1440 Optimization implements of manager command thread_used

- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
Reason:  
  BUG #1434
Type:  
  BUG 
Influences：  
   fix when datasouce crash ,test will route to other datasource
> #1434 check conn before test set

- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
Reason:  
  Improve #1412
Type:  
  Improve  
Influences：  
   add column used_for_heartbeat for show @@backend
> #1412 add column used_for_heartbeat for show @@backend

- src/main/java/com/actiontech/dble/buffer/BufferPool.java
- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowDirectMemory.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
  BUG #1446
Type:  
  BUG
Influences：  
   change show @@directmemory
> #1446 show @@directmemory

- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/plan/node/QueryNode.java
Reason:  
  BUG #1330
Type:  
  BUG
Influences：  
   Column  in field list is ambiguous
> #1330 Column  in field list is ambiguous

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/mysql/ErrorPacket.java
- src/main/java/com/actiontech/dble/net/mysql/OkPacket.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/singleton/SerializableLock.java
Reason:  
   Improve #1439
Type:  
  Improve  
Influences：  
   add SerializableLock for strict onsistency
> #1439 strict consistency

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/mysql/ErrorPacket.java
- src/main/java/com/actiontech/dble/net/mysql/OkPacket.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/singleton/SerializableLock.java
Reason:  
  Improve #1439 
Type:  
  Improve  
Influences：  
   fix  unlock when auth
> #1439 fix unlock when auth

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
Reason:  
  BUG #1458
Type:  
  BUG
Influences：  
   fix do ddl report error when xa on
> #1458 do ddl when xa on

- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/dump/DumpException.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileConfig.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileContext.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/manager/dump/ErrorMsg.java
- src/main/java/com/actiontech/dble/manager/dump/handler/CreateDatabaseHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/CreateTableHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/DefaultHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/DropHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/StatementHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/StatementHandlerManager.java
- src/main/java/com/actiontech/dble/manager/handler/SplitDumpHandler.java
- src/main/java/com/actiontech/dble/manager/response/DumpFileError.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  Improve #1452.  
Type:  
  Improve  
Influences：  
  split dump file according to datanode
> split dump file according to datanode

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
Reason:  
  BUG #1467  
Type:  
  BUG  
Influences：  
   fix  double lock bug
> #1467 fix  double lock bug

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
Reason:  
  BUG #1321  
Type:  
  BUG  
Influences：  
   add `  for  regroup insert sql
> #1321 add `  for  regroup insert sql

- src/main/java/com/actiontech/dble/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/SchemaHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/StatementHandlerManager.java
Reason:  
  Improve #1452 .  
Type:  
  Improve  
Influences：  
  fix hang when file contains set
> split dump file for review

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #1458
Type:  
  BUG
Influences：  
   fix when autocommit is 0 and release conns after ddl #1458
> do ddl when autocommit is 0 and release conns #1458

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/util/SchemaWriteJob.java
- src/main/java/com/actiontech/dble/manager/response/DataHostDisable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostEnable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostSwitch.java
- src/main/java/com/actiontech/dble/manager/response/ShowDataSource.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  BUG #1467 
Type:  
  BUG  
Influences：  
   re-init the HaConfigManager when reload_all
> Issue 1467

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #1458 
Type:  
  BUG
Influences：  
   fix ddl change not clean session status
> ddl change #1458

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG #1478  
Type:  
  BUG  
Influences：  
   Change the tableName into lowerCase when dble in lowerCaseMode before create TableNode
> #1478 all view to use when cause insensitive

- src/main/java/com/actiontech/dble/backend/BackendConnection.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/net/NIOProcessor.java
- src/main/java/com/actiontech/dble/net/handler/BackEndDataCleaner.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
Reason:  
  BUG #1335  
Type:  
  BUG  
Influences：  
   change sqlExecuteTimeout into what the parameter means(connection would be check timeout only when sql is executing in the connection )
> #1335 change sqlExecuteTimeout into what the parameter means

- src/main/java/com/actiontech/dble/backend/mysql/store/FileCounter.java
- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FileNioMapped.java
- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FilePathDisk.java
- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FileUtils.java
- src/main/java/com/actiontech/dble/memory/environment/Hardware.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
Reason:  
   Improve #.  
Type:  
  Improve  
Influences：  
   add log of tempdb
> add log for tempfile

- src/main/java/com/actiontech/dble/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/singleton/PauseDatanodeManager.java
Reason:  
  BUG #1432   
Type:  
  Improve  
Influences：  
   Add logs for the pause & resume process
> #1432 add log for pause & resume

- src/main/java/com/actiontech/dble/util/ByteUtil.java
Reason:  
  BUG #1491 
Type:  
  BUG
Influences：  
   fix small int with ps protocal error
> small int #1491

- src/main/assembly/conf/log4j2.xml
- src/main/java/com/actiontech/dble/config/util/SchemaWriteJob.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
- src/main/resources/log4j2.xml
Reason:  
  Improve #1467  
Type:  
  BUG  
Influences：  
   add more logs & add null check & change default log4j2 conf
> #1467 add more logs & add null check & change default log4j2 conf

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG #1499   
Type:  
  BUG  
Influences：  
  change dataHostWithoutWH judgment logic
> #1499 change dataHostWithoutWH judgment logic

- src/main/java/com/actiontech/dble/manager/response/ShowDataSource.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix show_datasource lack    standby read host
> show_datasource add standby read host

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  add split in help
> add split in help

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPoolDiff.java
- src/main/java/com/actiontech/dble/manager/response/DataHostDisable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostEnable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostSwitch.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/resources/myid.properties
Reason:  
  BUG #1467 
Type:  
  BUG  
Influences：  
   add show message for useOuterHa
   change notice when the ha mode is wrong
   change reload calculation for standby dataSources
> 2.19.09.0 1467 related bug fix

- src/main/java/com/actiontech/dble/manager/ManagerConnection.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/manager/handler/SplitDumpHandler.java
Reason:  
  Improve #1452.  
Type:  
  Improve  
Influences：  
  dump file can be killed and modify log
> dump file can be killed and modify log

- src/main/java/com/actiontech/dble/manager/dump/DumpFileContext.java
- src/main/java/com/actiontech/dble/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/manager/dump/handler/CreateTableHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/GlobalTableInsertHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/ShardingTableInsertHandler.java
Reason:  
  BUG #1452 .
Type:  
  BUG 
Influences：  
  throw error when increment column doesn't exist and fix additional ;
> throw error when increment column doesn't exist and fix additional ;

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG #1505  
Type:  
  BUG  
Influences：  
   fix bugs input by #1375
> Issue 1505

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
- src/main/java/com/actiontech/dble/config/util/SchemaWriteJob.java
Reason:  
  BUG #1467   
Type:  
  BUG  
Influences：  
   add size check and change disable flag checked
> #1476 add size check and change disable flag checked

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AbstractCommitNodesHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  reset fail state when last xa transaction fail to execute.
> reset fail state when last xa transaction fail to execute.

- docker-images/quick-start/schema.xml
- docker-images/quick-start/server.xml
- src/main/resources/schema_template.xml
- src/main/resources/template_table.sql
Reason:  
  Improve 
Type:  
  BUG  
Influences：  
   correct quick-start
> correct quick-start

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/cluster/AbstractClusterSender.java
- src/main/java/com/actiontech/dble/cluster/bean/InstanceOnline.java
- src/main/java/com/actiontech/dble/cluster/listener/ClusterOffLineListener.java
- src/main/java/com/actiontech/dble/server/status/OnlineLockStatus.java
Reason:  
  BUG Inner 2397 
Type:  
  BUG 
Influences：  
   fix xx
> online status

- src/main/java/com/actiontech/dble/manager/dump/handler/CreateTableHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
Reason:  
  BUG #1519.
Type:  
  BUG 
Influences：  
  fix that dump file treats primary key as increment key
> fix that dump file treats primary key as increment key

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/manager/response/ShowThreadUsed.java
Reason:  
  BUG #1514
Type:  
  BUG 
Influences：  
   fix treemap thread safe
> treemap thread safe #1514

- src/main/java/com/actiontech/dble/manager/dump/handler/CreateTableHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   cherry picked from commit 998c31b99e564201fd9fcc2c1ce4b5ad80350be4
> fix that dump file treats primary key as increment key (#1517)

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
Reason:  
  BUG #1489.
Type:  
  BUG
Influences：  
  alias does not take effect in statement contains union
> alias does not take effect in statement contains union #1489

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG #1528
Type:  
  BUG  
Influences：  
   disable dataHost may cause connection control error
> #1528 disable dataHost may cause connection control error

- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/DataHostStatusListener.java
Reason:  
  Improve #1535
Type:  
  Improve  
Influences：  
  fix issue #1535, make warning information more friendlly to understand
> fix issue #1535

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
Reason:  
  BUG #1532. 
Type:  
  BUG
Influences：  
  charset is set utf8 when charset name is uppercase
> charset is set utf8 when charset name is uppercase

- src/main/java/com/actiontech/dble/plan/common/field/FieldUtil.java
- src/main/java/com/actiontech/dble/plan/common/item/Item.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemDecimal.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG #1417
Type:  
  BUG 
Influences：  
   fix return dataType error
> dataType #1417

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1456.
Type:  
  BUG 
Influences：  
  Last fix doesn‘t fix all place
> fix issue 1456

- src/main/assembly/conf/log4j2.xml
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/DDLTraceInfo.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/singleton/DDLTraceManager.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/main/resources/log4j2.xml
Reason:  
  Improve #1524  
Type:  
  Improve  
Influences：  
  DDL separate from general queries
> Issue 1524

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
- src/main/java/com/actiontech/dble/sqlengine/SpecialSqlJob.java
Reason:  
  BUG import from #1543
Type:  
  BUG 
Influences：  
   fix conn count leak
> create conn leak #1543

- src/main/java/com/actiontech/dble/server/parser/ServerParseShow.java
Reason:  
  BUG #1550  
Type:  
  BUG  
Influences：  
   loosen the check of the "show database " statement
> #1550 loosen the check of the "show database " statement

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
Reason:  
  BUG #1540  
Type:  
  BUG  
Influences：  
   no longer maintain standbyReadSourcesMap in PhysicalDNPoolSingleWH
> #1540 no longer maintain standbyReadSourcesMap in PhysicalDNPoolSingleWH

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   reload and ha enable must start heartbeat
> reload and ha enable must start heartbeat

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/manager/response/ShowDatasourceCluster.java
- src/main/java/com/actiontech/dble/manager/response/ShowDatasourceSyn.java
- src/main/java/com/actiontech/dble/manager/response/ShowDatasourceSynDetail.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix heartbeat and other
> pool disabled

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
- src/main/java/com/actiontech/dble/sqlengine/SpecialSqlJob.java
Reason:  
  BUG from #1543 
Type:  
  BUG 
Influences：  
  no other Influences
> no need must write#1543

- docker-images/quick-start/schema.xml
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/cache/DefaultLayedCachePool.java
- src/main/java/com/actiontech/dble/cache/LayerCachePool.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/schema/schema/ChildTable.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/schema/schema/Table.java
- src/main/java/com/actiontech/dble/config/model/TableConfig.java
- src/main/java/com/actiontech/dble/manager/dump/handler/CreateTableHandler.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/resources/schema.dtd
- src/main/resources/schema_template.xml
- src/test/java/com/actiontech/dble/config/ConfigTest.java
- src/test/resources/config/schema.xml
- src/test/resources/route/schema.xml
- src/test/resources/schema.dtd
- src/test/resources/schema.xml
Reason:  
  Improve #1526  
Type:  
  Improve  
Influences：  
   primaryKey nolonger available & change into cacheKey
> #1526 Change primaryKey into cacheKey

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/manager/response/ShowQuestions.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/CommitHandler.java
- src/main/java/com/actiontech/dble/server/handler/RollBackHandler.java
- src/main/java/com/actiontech/dble/singleton/TsQueriesCounter.java
Reason:  
  Improve #1527  
Type:  
  Improve  
Influences：  
   Add new command show @@Questions
> #1527 Add new command show @@Questions

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowDataDistribution.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
    Improve #1566  
Type:  
  Improve  
Influences：  
   add show data_distribution
> show data_distribution #1566

- src/main/java/com/actiontech/dble/manager/handler/SplitDumpHandler.java
Reason:  
  Improve #1521 .  
Type:  
  Improve  
Influences：  
  fix when default schema isn't set
> #1521 - fix when default schema isn't set

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/resources/server_template.xml
Reason:  
  BUG for sync key variables
Type:  
  BUG
Influences：  
   fix : set autocommit befrore select @@autocommit
> bug_set_autocommit

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:
     Improve #1525 
Type:
  BUG
Influences：
   fix : select * from (select * from test) b limit 0; select * from (select * from test) b limit -1;
> issues-1525 synax 'limit 0' will return all rows

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/resources/template_table.sql
Reason:  
  Improve #1539.  
Type:  
  Improve  
Influences：  
  fix view that contains alias
> import from #1539

- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  BUG import #1564
Type:  
  Improve  
Influences：  
   big select result may not correct #1564
> #1564 big_result may not correct

- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/singleton/TsQueriesCounter.java
Reason:  
  BUG #1527  
Type:  
  BUG  
Influences：  
   Do not cout closed session for twice
   Do not cout commit/rollback into single transation
> #1527 bug fix of QPS/TPS

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AbstractCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/CommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/ImplicitCommitHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  Improve #1527  
Type:  
  Improve  
Influences：  
   Spelling correction
> #1527 Spelling correction

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/DDLTraceInfo.java
- src/main/java/com/actiontech/dble/singleton/DDLTraceManager.java
Reason:  
  Improve #1524   
Type:  
  Improve  
Influences：  
   Improve DDL log
> #1524 Improve DDL log

- src/main/java/com/actiontech/dble/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/manager/dump/handler/InsertHandler.java
Reason:  
  Improve #1521 .  
Type:  
  Improve  
Influences：  
  fix dump when containing nosharding table
> #1521 - fix dump when containing nosharding table

- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/test/java/com/actiontech/dble/parser/ManagerParserTest.java
Reason:  
  Improve #1585 .  
Type:  
  Improve  
Influences：  
   show @@connection and show @@backend
> #1585 - add where condition for show @@connection and show @@backend

- src/main/java/com/actiontech/dble/backend/datasource/AbstractPhysicalDBPool.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/schema/datahost/DataHost.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/entity/schema/datahost/HeartBeat.java
Reason:  
  BUG #1582
Type:  
  BUG
Influences：  
   fix #1582
>  #1582 heartbet_bug

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
Reason:  
  Improve #1362 .  
Type:  
  Improve  
Influences：  
  support for kill query
> support for kill query

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/cluster/kVtoXml/ClusterToXml.java
- src/main/java/com/actiontech/dble/cluster/response/DataHostHaResponse.java
- src/main/java/com/actiontech/dble/cluster/response/XmlSchemaLoader.java
- src/main/java/com/actiontech/dble/cluster/xmltoKv/XmltoCluster.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/DataHostStatusTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/DataHostResponseListener.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/DataHostStatusListener.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/SchemaszkToxmlLoader.java
- src/main/java/com/actiontech/dble/manager/response/DataHostDisable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostEnable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostSwitch.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG #1535  
Type:  
  BUG
Influences：  
   do not influences other instance when the useOuterHa flag is false
> do not influences other instance when the useOuterHa flag is false

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG #1577
Type:  
  BUG
Influences：  
   fix testConn
> #1577 import from #1541

- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  BUG improt from #1543
Type:  
  BUG
Influences：  
   front session default autocommit
>  front session default autocommit #1543

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG #1403  
Type:  
  BUG  
Influences：  
   fix packetId when in multiQueries
> #1403 fix packetId when in multiQueries

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
Reason:  
  BUG #1524  
Type:  
  BUG  
Influences：  
   fix DDL slow log bug
> #1524 fix DDL slow log bug

- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnection.java
Reason:  
  Improve #1585 .  
Type:  
  Improve  
Influences：  
  import from #1585
> import from #1585

- src/main/java/com/actiontech/dble/backend/BackendConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/route/sequence/handler/FetchMySQLSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
- src/main/resources/dbseq.sql
Reason:  
  BUG import from #1543
Type:  
  BUG 
Influences：  
   global sequence
>  import from #1543 dble_seq_nextval must need  autocommit =1

- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
   Improve slow log performance
Type:  
  Improve  
Influences：  
   remove synchronized
> remove synchronized

- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
Reason:  
     Improve #1362 .  
Type:  
  Improve  
Influences：  
  import from kill query
> import from kill query

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/SessionStage.java
Reason:  
  BUG #1564
Type:  
  BUG
Influences：  
   if select not autocommit ,the second query lost end time
> if select not autocommit ,the second query lost end time #1564

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
  BUG #1451
Type:  
  BUG  
Influences：  
   TableNode group by push down do not change to alias
> #1451 TableNode group by push down do not change to alias

- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/alarm/ToResolveContainer.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDataSourceKeyVariables.java
Reason:  
   Improve #1543
Type:  
  Improve  
Influences：  
   alert if mysql lower_case error
> #1543 if mysql lower_case error

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
  BUG #1513.
Type:  
  BUG  
Influences：  
  result in lost connection due to inconsistent handler when connection was closed
> #1513 - result in lost connection due to inconsistent handler when connection was closed

- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
Reason:  
  Improve #1585 .  
Type:  
  Improve  
Influences：  
  mysql_id -> mysqlid in condition of show @@backend
> mysql_id -> mysqlid in condition of show @@backend

- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  avoid overflow of int and add log when dble can't allocate direct ByteBuffer
> avoid overflow of int and add log when dble can't allocate direct ByteBuffer

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowTablesHandler.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemAllAnySubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemExistsSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemInSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemMultiRowSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemScalarSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemSingleRowSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemSubQuery.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
- src/test/java/com/actiontech/dble/plan/visitor/TestMySQLItemVisitor.java
- src/test/java/com/actiontech/dble/plan/visitor/TestMySQLPlanNodeVisitor.java
Reason:  
  BUG #1453 #1455
Type:  
  BUG
Influences：  
   fix uservariables problem
> user variables #1453 #1455

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG #1602  
Type:  
  BUG
Influences：  
   change alias to lowerCase when try to check alias exists
> #1602 change alias to lowerCase when try to check alias exists

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
Reason:  
  Improve  #1543
Type:  
  Improve  
Influences：  
   ddl no need sync context
> ddl no need sync context #1543

- src/main/java/com/actiontech/dble/plan/common/item/function/primary/ItemFuncNumhybrid.java
Reason:  
  BUG #1466
Type:  
  BUG 
Influences：  
   ItemFuncNumhybrid return error
> #1466 ItemFuncNumhybrid return error

- src/main/java/com/actiontech/dble/config/loader/xml/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  Improve #1607
Type:  
  Improve
Influences：  
  change default value of pagebuffernumber
> #1607 change default value of pagebuffernumber

- src/main/java/com/actiontech/dble/singleton/DDLTraceManager.java
Reason:  
  BUG #1524  
Type:  
  BUG  
Influences：  
   change log message to make it more clear
> #1524 change log message to make it more clear

- src/main/java/com/actiontech/dble/backend/datasource/check/AbstractConsistencyChecker.java
- src/main/java/com/actiontech/dble/backend/datasource/check/CheckSumChecker.java
- src/main/java/com/actiontech/dble/backend/datasource/check/CountChecker.java
- src/main/java/com/actiontech/dble/sqlengine/MultiTablesMetaJob.java
- src/main/java/com/actiontech/dble/sqlengine/SQLJob.java
- src/main/java/com/actiontech/dble/sqlengine/SpecialSqlJob.java
Reason:  
  BUG #1558  
Type:  
  BUG  
Influences：  
   check default checkSum & CountCheck to avoid NPE
  Change some sqlJob into autocommit
> #1558 check default checkSum & CountCheck to avoid NPE

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
Reason:  
   Improve
Type:  
  Improve  
Influences：  
   switch_alive_mysql， check read only status
> switch_alive_mysql

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix kill query in ddl
> fix kill query in ddl

- src/main/java/com/actiontech/dble/backend/datasource/check/CheckSumChecker.java
- src/main/java/com/actiontech/dble/backend/datasource/check/CountChecker.java
- src/main/java/com/actiontech/dble/manager/response/CheckGlobalConsistency.java
Reason:  
   Improve #1558  
Type:  
  Improve  
Influences：  
   global check  result log change in default implements
>  #1558  global check  result log change in default implements

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix kill query for xa
> fix kill query for xa

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG #1403  
Type:  
  BUG  
Influences：  
   change set session after rowEof packetId added
> #1403 multiNodeQueryHandler packetId error

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
Reason:  
  BUG #1513.
Type:  
  BUG  
Influences：  
   friendly tips
> #1513 - friendly tips

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOReactor.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/response/ShowVariables.java
Reason:  
  BUG  #1622
Type:  
  BUG
Influences：  
   memory_leak
> memory_leak #1622

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG import from #1622
Type:  
  BUG  
Influences：  
   when use show warning may NPE
> #1622 other not select sql #1634

- src/main/java/com/actiontech/dble/manager/response/ShowDataDistribution.java
Reason:  
  Improve #1566
Type:  
  Improve  
Influences：  
   tips and not send to readhost
> #1566 improve

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
Reason:  
  BUG #1638
Type:  
  BUG 
Influences：  
   heartbeat conn closed by other， need recover
> #1638 heartbeat conn closed by other

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
Reason:  
  BUG
Type:  
Influences：  
  heartbeat reach maxcon， if it has idle, close it
> heartbeat reach maxcon

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  heartbeat status 
Type:  
  Improve  
Influences：  
   fix xx
> heartbeat status

- src/main/java/com/actiontech/dble/meta/table/ConfigTableMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/GetConfigTablesHandler.java
Reason:  
   Improve #1539 .  
Type:  
  Improve  
Influences：  
  import from 1539
> import from 1539

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   NPE
> can't get conn and remove,it will NPE

- docker-images/quick-start/rule.xml
- docker-images/quick-start/schema.xml
- docker-images/quick-start/server.xml
- src/main/java/com/actiontech/dble/cluster/response/ConfigStatusResponse.java
- src/main/resources/rule_template.xml
- src/main/resources/schema_template.xml
- src/main/resources/server_template.xml
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   config xml version change into 2.0
> config xml version change into 2.0

- src/main/java/com/actiontech/dble/cluster/response/ConfigStatusResponse.java
Reason:  
  Inner ATK-667
Type:  
  Improve  
Influences：  
   add log to watch the result
> Inner ATK-667 add log to watch the result

- pom.xml
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBNode.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBPool.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
Reason:  
  BUG #1649 
Type:  
  BUG
Influences：  
  select column order
> #1649 select column order

- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/singleton/CronScheduler.java
Reason:  
  BUG #1558   
Type:  
  BUG
Influences：  
   fix bug of global table check customization
> fix bug of global table check customization

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG :create conn when Heartbeat init
Type:  
  BUG
Influences：  
   fix xx
> heartbeat_init_for_create_conn

- src/main/java/com/actiontech/dble/manager/handler/DataHostHandler.java
Reason:  
  BUG #1661   
Type:  
  BUG
Influences：  
   Broadening the scope of datasource names to support '.' in datasource name
> #1661 Broadening the scope of datasource names

- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceTimeHandler.java
Reason:  
  BUG #1665.
Type:  
  BUG
Influences：  
  fix negative in timestamp sequence
> #1665 - fix negative in timestamp sequence

- pom.xml
Reason:  
  fastjson version problem
Type:  
  Improve  
Influences：  
   update fastjson version from 1.2.60 to 1.2.62
> fastjson version

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDBNode.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/helper/TestSchemasTask.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/handler/DatabaseHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowDataNode.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
Reason:  
  Improve #1671.  
Type:  
  Improve  
Influences：  
1. add manager command of drop database
2.add column of schema_exists for show @@datanode
> #1671 - add manager command of drop database

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAAutoRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
Reason:  
Type:  
Influences：  
   if conn return ok and then closed, status should not change
> Auto xa bug

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
Reason:  
  BUG  #inner 314
Type:  
  BUG
Influences：  
   autoxa rollback ,init closed conn
> autoxa rollback ,init closed conn

- pom.xml
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/log/transaction/TxnLogProcessor.java
Reason:  
   Improve
Type:  
  Improve  
Influences：  
1. upgrade log4j version from 2.7 to 2.13.1
2. upgrade fastjson
3. https://github.com/actiontech/dble/pull/1631
> 2.19.07.3/rel

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
  Improve #1670  
Type:  
  Improve  
Influences：  
   Olny when the complex 'group by' pushdown changed into group by order by
> #1670 Standardize 'group by' pushdown to MySQL

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:  
   Improve #1697 
Type:  
  Improve  
Influences：  
  drydun test mysql lower_case
> #1697 dryrun test lower_case

- pom.xml
Reason:  
  Improve #1672  
Type:  
  Improve  
Influences：  
  Change the policy according to the inner discussion
> #1672 remove oom kill to let the JVM running

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/AbstractRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalRollbackNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACheckHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XACommitNodesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XARollbackNodesHandler.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/singleton/SerializableLock.java
Reason:  
  Improve  #1675 
Type:  
  Improve  
Influences：  
    #1675 before refactor, some bugs
>  #1675 before refactor, some bugs

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG #1650
Type:  
  BUG
Influences：  
   unknown user variable treat as null
> #1650 unknown user variable

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG #1705
Type:  
  BUG  
Influences：  
    avoid error when try to pushDown or condition
> #1705 avoid error when try to pushDown or condition

- src/main/java/com/actiontech/dble/server/variables/VarsExtractorHandler.java
Reason:  
  BUG #1542 
Type:  
  BUG
Influences：  
  show variables need not sync context
> #1542 show variables need not sync context

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDNPoolSingleWH.java
- src/main/java/com/actiontech/dble/config/util/SchemaWriteJob.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  BUG #1648   #1659 
Type:  
  BUG  
Influences：  
   change the log flag & change finishNext into finally
> #1648 #1659 change the log flag & change finishNext into finally

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
Reason:  
  BUG #1682
Type:  
  BUG
Influences：  
  heartbeat deadlock
> #1682 heartbeat deadlock

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
Reason:  
  BUG #1543
Type:  
  BUG
Influences：  
   conn pool may has contexted
> #1543 conn pool may has contexted

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/plan/common/item/function/ItemCreate.java
- src/main/java/com/actiontech/dble/plan/node/JoinInnerNode.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/SelectHandler.java
- src/main/java/com/actiontech/dble/server/parser/ServerParseSelect.java
- src/main/java/com/actiontech/dble/server/response/SelectRowCount.java
Reason:  
  BUG #1287  
Type:  
  BUG  
Influences：  
   Add new support inner function ROW_COUNT()
   fix issue when the inner function used with '*' may cause repeated result
> Issue 1287

- src/main/java/com/actiontech/dble/server/response/SelectVariables.java
Reason:  
  BUG #1625  
Type:  
  BUG  
Influences：  
   change the show in server port to return the real session config #1625
> change the show in server port to return the real session config #1625

- src/main/java/com/actiontech/dble/manager/handler/DatabaseHandler.java
Reason:  
  Improve #1721.  
Type:  
  Improve  
Influences：  
  import from #1671, add friendly tip when error occurs
> import from #1671, add friendly tip when error occurs

- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
Reason:  
  BUG #1735
Type:  
  BUG
Influences：  
   fix manage command
> object conversion exception repair

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #1709
Type:  
  BUG
Influences：  
   fix big package
> cache packetId not ++

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/CommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/RollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/XAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAStage.java
Reason:  
  BUG #1676. 
Type:  
  BUG
Influences：  
  fix packetId when the sql contains implicit commit or rollback
> #1676 - fix packetId when the sql contains implicit commit or rollback

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG #1682 and inner180
Type:  
  BUG
Influences：  
   #1682 and inner180
> #1682 inner #180

- src/main/java/com/actiontech/dble/backend/mysql/ByteUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/ResultDiskBuffer.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
Reason:  
   Improve #1709 
Type:  
  Improve  
Influences：  
   big package for tmpfile
> #1709 big package for tmpfile

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
Reason:  
  BUG #1287   
Type:  
  BUG  
Influences：  
   The success DDL should make the row_count() function return result 0
> #1287 add DDL row_count support

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHostDiff.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/server/variables/VarsExtractorHandler.java
Reason:  
  BUG import from #1710 inner194
Type:  
  BUG
Influences：  
   readhost need show all readhost
> import from #1710

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG #1749. 
Type:  
  BUG  
Influences：  
  turn table name to lowercase when backend mysql is case sensitive.
> #1749 - turn table name to lowercase when backend mysql is case sensitive.

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
Reason:  
  BUG #1676 
Type:  
  BUG  
Influences：  
    Implicit commit should change the flag first
> #1676 Implicit commit should change the flag first

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/CommitStage.java
Reason:  
  BUG #1675 
Type:  
  BUG  
Influences：  
   change implicitCommit ok packet creation
> #1675 change implicitCommit ok packet creation

- docker-images/quick-start/server.xml
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/transaction/TxnLogProcessor.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/resources/server_template.xml
Reason:  
  Improve #1755
Type:  
  Improve  
Influences：  
   typo
> #1755 spell

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FetchStoreNodeOfChildTableHandler.java
Reason:  
  BUG #1655
Type:  
  BUG
Influences：  
   child table fetch error not meaningful
> #1655 child table fetch error

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDataSourceKeyVariables.java
- src/main/java/com/actiontech/dble/config/helper/KeyVariables.java
- src/main/java/com/actiontech/dble/config/helper/SyncDataSourceKeyVariables.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/server/variables/SystemVariables.java
Reason:  
  BUG from #1709 
Type:  
  BUG
Influences：  
    start will try to sync max_allowed_packet and dryrun should not sync anything
> #1709 start will try to sync max_allowed_packet and dryrun should not sync anything

- src/main/java/com/actiontech/dble/config/loader/zkprocess/parse/XmlProcessBase.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/parse/entryparse/schema/xml/SchemasParseXmlImpl.java
Reason:  
  BUG #1729  
Type:  
  BUG  
Influences：  
   write file into two stages & throw expection when either stage not success
> #1729 schema file write change missing part

- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:  
  BUG import from  #1710
Type:  
  BUG
Influences：  
   inner 204
> import from #1710, may no need reinit datahost

- src/main/java/com/actiontech/dble/backend/BackendConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/net/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOProcessor.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/resources/server_template.xml
Reason:  
  Improve #1753.  
Type:  
  Improve  
Influences：  
   Add flow control feature to avoid OOM
> Add flow control feature to avoid OOM

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/RollbackStage.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
   Improve #1675.  
Type:  
  Improve  
Influences：  
  disable xa when locking table
> disable xa when locking table

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
Reason:  
  BUG tempReadHostAvailable lost， inner  203
Type:  
  BUG
Influences：  
    tempReadHostAvailable lost
> tempReadHostAvailable lost

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
Reason:  
  Improve #1755
Type:  
  Improve  
Influences：  
   typo
> #1755 SqL->SQL

- src/main/java/com/actiontech/dble/net/handler/FrontendCommandHandler.java
Reason:  
   Improve #1709
Type:  
  Improve  
Influences：  
  max_allowed_packet not contains header
> #1709 max_allowed_packet not contains header

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataNode.java
Reason:  
  BUG inner205
Type:  
  BUG
Influences：  
   inner205
> hint to slave but no alive slave will report error inner 205

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG inner209
Type:  
  BUG
Influences：  
  fix increment column as partition column
> fix increment column as partition column

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/XAHandler.java
Reason:  
  BUG inner211. 
Type:  
  BUG
Influences：  
  fix dble hang when session target is empty in commit/rollback stage
> fix dble hang when session target is empty in commit/rollback stage

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG #1782  
Type:  
  BUG  
Influences：  
   when select from dual without database, just choose a random one
> #1782 when select from dual without database, just choose a random one

- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDataSourceKeyVariables.java
- src/main/java/com/actiontech/dble/config/helper/KeyVariables.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  Improve  #1709  
Type:  
  Improve  
Influences：  
   fix set global max packet size
>  #1709 max packet size

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  Improve #1755  
Type:  
  Improve  
Influences：  
   dryrun & use new spell
>  #1755 dryrun & use new spell

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataNode.java
- src/test/java/com/actiontech/dble/config/ConfigTest.java
Reason:  
  BUG inner 216
Type:  
  BUG
Influences：  
   select random readhost
> select random readhost

- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
- src/main/java/com/actiontech/dble/net/mysql/WriteToBackendTask.java
Reason:  
  BUG inner215. 
Type:  
  BUG
Influences：  
  fix big packet
> fix big packet

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
Reason:  
  BUG #1729  
Type:  
  BUG  
Influences：  
   ha schema.xml file write logic change
> #1729 ha schema.xml file write logic change

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/LoadDataUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/config/FlowCotrollerConfig.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/ManagerConnection.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/handler/FlowControlHandler.java
- src/main/java/com/actiontech/dble/manager/response/FlowControlList.java
- src/main/java/com/actiontech/dble/manager/response/FlowControlSet.java
- src/main/java/com/actiontech/dble/manager/response/FlowControlShow.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOProcessor.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/singleton/WriteQueueFlowController.java
Reason:  
  Improve #1753  
Type:  
  Improve  
Influences：  
   Move flowControlledBackendConnections into Session to fit the logic
   Change flowControllStop into writePacket
   Add three manager command to help use the flow controll
   Add flowControllStop when connection release from target
> Issue 1753 code style & part logic change

- custom_mysql_ha.py
- dbledatahostcheck.py
- logging.conf
Customize dble switching using the python3 script.
Reason:  
Type:  
Influences：  
   fix xx
> Customize dble switching using the python3 script.new

- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/server/handler/UseHandler.java
Reason:  
  BUG #1287  
Type:  
  BUG  
Influences：  
   when use database the row_count should be set 0
> #1287 when use database the row_count should be set 0

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataSource.java
- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
Reason:  
  Improve #1733.  
Type:  
  Improve  
Influences：  
  refactor code for inner 220,221,224
> #1733 - refactor code

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/manager/response/ShowBackend.java
- src/main/java/com/actiontech/dble/sqlengine/HeartbeatSQLJob.java
Reason:  
  Improve #1733.  
Type:  
  Improve  
Influences：  
  revert location of HeartbeatSQLJob
> revert location of HeartbeatSQLJob

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
   log and typo change
> log and typo change

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  Improve #1733.  
Type:  
  Improve  
Influences：  
  when heartbeat is ok or timeout, clear message
> when heartbeat is ok or timeout, clear message

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/net/AIOReadHandler.java
Reason:  
  BUG inner 228
Type:  
  BUG
Influences：  
   change lowercase and reload
> inner 228 & aio connect count

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataNode.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataSource.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLSchemaLoader.java
- src/main/java/com/actiontech/dble/config/util/AuthUtil.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/ReloadMetaData.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/server/variables/SystemVariables.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
Reason:  
  BUG #1801  
Type:  
  BUG  
Influences：  
   Add support dble can start/reload when not fully configed
> Add support dble can start/reload when not fully configed

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
Reason:  
  BUG #1808.  
Type:  
  BUG  
Influences：  
   reset before commit/rollback start
> #1808 reset before commit/rollback start

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:  
  BUG #1801 
Type:  
  BUG  
Influences：  
   Not checked config when the config is incomplete for now
> #1801 Not checked for now

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:  
  BUG #1801  
Type:  
  BUG  
Influences：  
   Not checked config when the config is not fully configured
> #1801 Not checked config when the config is not fully configured

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/XAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAStage.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/SetInnerHandler.java
Reason:  
  Improve #1675.  
Type:  
  Improve  
Influences：  
  bug for failing to background retry
> import from xa refactor

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #1725 
Type:  
  BUG  
Influences：  
  change the global node logic
> #1725 change the global node logic

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackFailStage.java
Reason:  
   Improve #1675 .  
Type:  
  Improve  
Influences：  
   bug about background rollback retry
> import from xa refactor about rollback

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
  BUG #1670  
Type:  
  BUG  
Influences：  
   fix the impact on GROUP_CONCAT& FUNCTION DISTINCT
> #1670 fix the impact on GROUP_CONCAT& FUNCTION DISTINCT

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackFailStage.java
Reason:  
  Improve #1675 .  
Type:  
  Improve  
Influences：  
  incorrect background retry count when xa
> incorrect background retry count when xa

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDataHost.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
   Improve #1542
Type:  
  improve  
Influences：  
   all type heartbeat recover,need check status
> all type heartbeat recover,need check status #1542

- src/main/java/com/actiontech/dble/manager/response/PauseEnd.java
Reason:  
  BUG #1823.  
Type:  
  BUG  
Influences：  
   change the resume error message in cluster mod
   Need be fix in all the lts branch
> #1823 change the resume error message in cluster mod

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1753  
Type:  
  BUG  
Influences：  
  Log convergence
> #1753 Log convergence

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
Reason:  
  bug.  
Type:  
  bug  
Influences：  
  xa hang when connections were closed in gap of two stage
> xa hang when connections were closed in gap of two stage

- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
Reason:  
  BUG #1823  
Type:  
  BUG  
Influences：  
   correct help message
> #1823 correct help message

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG #1805 
Type:  
  BUG  
Influences：  
   change the error message to avoid NPE
> #1805 change the error message to avoid NPE

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/manager/response/ShowHelp.java
> 2.20.04.99/lts new

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
Reason:  
  BUG #1542  
Type:  
  BUG  
Influences：  
   when hreatbeat stop do not sync the status
> #1542 when hreatbeat stop do not sync the status

- src/main/assembly/bin/dble_datahosts_check.py
Reason:  
   Improve #1710
Type:  
  Improve  
Influences：  
   support 5.7 mgr
>  support 5.7 mgr

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
(cherry picked from commit f34ec4c43f0cc39b92af1b67882321b1c636c116)
Reason:  
  Improve #1675 .  
Type:  
  Improve  
Influences：  
   xa hang when connections were closed in gap of two stage
> xa hang when connections were closed in gap of two stage (#1826)

- src/main/java/com/actiontech/dble/statistic/stat/QueryResult.java
- src/main/java/com/actiontech/dble/statistic/stat/SqlResultSizeRecorder.java
- src/main/java/com/actiontech/dble/statistic/stat/StatSqlParser.java
- src/main/java/com/actiontech/dble/statistic/stat/UserSqlHighStat.java
- src/main/java/com/actiontech/dble/statistic/stat/UserSqlLargeStat.java
- src/main/java/com/actiontech/dble/statistic/stat/UserSqlLastStat.java
- src/main/java/com/actiontech/dble/statistic/stat/UserStat.java
Reason:  
  BUG #1844
Type:  
  BUG 
Influences：  
   cut sql course druid error
> #1844 cut sql course druid error

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
Reason:  
  Improve #1846.  
Type:  
  Improve  
Influences：  
  complex query
> #1846 - send query by WriteToBackendExecutor in complex query

- src/main/java/com/actiontech/dble/meta/TableMeta.java
- src/main/java/com/actiontech/dble/meta/table/SchemaCheckMetaHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  Improve #1848.  
Type:  
  Improve  
Influences：  
  Fix bug import from online ddl
> Fix bug import from online ddl

- docker-images/Dockerfile
Reason:  
  Use python scripts to make back-end MySQL highly available
Type:  
  Improve  
Influences：  
   no
> refactor Dockerfile

- docker-images/Dockerfile
Reason:  
1、Reduce the size  
2、“raw.githubusercontent.com” url 404
Type:  
  Improve
> Reduce the size

- src/main/java/com/actiontech/dble/meta/table/old/AbstractTableMetaHandler.java
Reason:  
  Fix thread safety issues of linkedlist usage
Type:  
  BUG  
Influences：  
   Fix thread safety issues of linkedlist usage
> Fix thread safety issues of linkedlist usage

- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
Reason:  
  BUG inner 257 
Type:  
  BUG
Influences：  
   single route trace
> inner issue 257 single route trace

- src/main/java/com/actiontech/dble/cluster/response/DdlChildResponse.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/DDLInfo.java
Reason:  
  BUG ATK-1039
Type:  
  BUG
Influences：  
   fix DDL cluster response
> 2.19.11.99

- src/main/java/com/actiontech/dble/cluster/response/DdlChildResponse.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/DDLInfo.java
Reason:
  BUG ATK-1039
Type:
  BUG
Influences：
   fix DDL cluster response
> 2.19.09.99

- src/main/java/com/actiontech/dble/cluster/response/DdlChildResponse.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zookeeper/process/DDLInfo.java
Reason:
  BUG ATK-1039
Type:
  BUG
Influences：
   fix DDL cluster response
> 2.20.04.99

- docker-images/Dockerfile
- docker-images/docker-compose.yml
- docker-images/quick-start/db.xml
- docker-images/quick-start/docker_init_start.sh
- docker-images/quick-start/start_mgr.sh
Reason:  
  Improve
Type:  
  Improve  
Influences：  
   quick start
> Realize the quick start of two groups MGR and DBLE

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  add log for xa transaction
> add log for xa transaction

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
Reason:
  Improve #1846.
Type:
  Improve
Influences：
  check system param of writeToBackendExecutor
> check system param of writeToBackendExecutor

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  BUG  inner 306
Type:  
Influences：  
  add log
> #1849 inner 306 system add to log

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG #1863 
Type:  
  BUG  
Influences：  
   fix nosharding update bug input by #1863
> fix nosharding update bug input by #1863

- src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java
Reason:  
  BUG ATK-1049  
Type:  
  BUG 
Influences：  
   fix when left join can not merge with global table
> fix when left join can not merge with global table

- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG ATK-1004 
Type:  
  BUG  
Influences：  
   Update the read time during the LOAD DATA operation
> Update the read time during the LOAD DATA operation

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG #1814 .
Type:  
  BUG 
Influences：  
  clear resource when failing to execute load data
> #1814 - clear resource when failing to execute load data

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  Improve #1848 .  
Type:  
  Improve  
Influences：  
  online ddl shouldn't contains META_UPDATE log
> online ddl shouldn't contains META_UPDATE log

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/DbXmlWriteJob.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/config/util/StartProblemReporter.java
- src/main/java/com/actiontech/dble/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/manager/response/KillDdlLock.java
- src/main/java/com/actiontech/dble/manager/response/PauseEnd.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/manager/response/ha/DbGroupHaSwitch.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceTimeHandler.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
- src/main/java/com/actiontech/dble/singleton/SequenceManager.java
- src/main/java/com/actiontech/dble/util/SystemProperty.java
Reason:  
   Improve #1849 313 
Type:  
  Improve  
Influences：  
  if config of bootstrap and cluster error，can not start
> #1849 bootstrap

- src/main/java/com/actiontech/dble/plan/node/TableNode.java
Reason:  
  BUG #1863   
Type:  
  BUG  
Influences：  
   check the table type & column type when insert .. select
> #1863 bug fix

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/backend/pool/PoolBase.java
- src/main/java/com/actiontech/dble/backend/pool/PoolConfig.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/ManagerConnection.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/NIOProcessor.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
Type:  
  Improve  
Influences：  
  check config of connection pool and fix bug when disabling datahost
> check config of connection pool and fix bug when disabling datahost

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
Reason:  
  Improve bootstrap.dynamic.cnf
Type:  
  Improve  
Influences：  
   fix xx
> Improve bootstrap.dynamic.cnf

- pom.xml
- src/main/java/com/actiontech/dble/DbleStartup.java
- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/cluster/ClusterGeneralConfig.java
- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/config/util/StartProblemReporter.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  #1849 inner 320
Type:  
  Improve  
Influences：  
  show all bootstart error
> #1849 inner 320

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
  manger cmd of reload config_all -r kill conn in use
> manger cmd of reload config_all -r kill conn in use

- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  Failed to start if there is a problem with the sequencestarttime configuration
> inner issue 327 Failed to start if there is a problem with the sequencestarttime configuration

- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix inner issue 327 check the ID generated by zk and retry on collision
> inner issue 327 check the ID generated by zk and retry on collision

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAEndStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAStage.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLDbLoader.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
Reason:  
  BUG inner233
Type:  
  BUG 
Influences：  
  set default value of errorRetryCount to 1
> set default value of errorRetryCount to 1

- src/main/java/com/actiontech/dble/backend/mysql/BindValue.java
- src/main/java/com/actiontech/dble/backend/mysql/BindValueUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/PreparedStatement.java
- src/main/java/com/actiontech/dble/net/mysql/ExecutePacket.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  PS PROTOCAL BUG  from #1906 
Type:  
  BUG 
Influences：   
see
```
sql\sql_prepare.cc
void mysqld_stmt_execute(THD *thd, ulong stmt_id, ulong flags, uchar *params, ulong params_length)
bool Prepared_statement::execute_loop(String *expanded_query, bool open_cursor, uchar *packet, uchar *packet_end)
bool Prepared_statement::set_parameters(String *expanded_query, uchar *packet, uchar *packet_end)
static bool setup_conversion_functions(Prepared_statement *stmt, uchar **data, uchar *data_end)
static void setup_one_conversion_function(THD *thd, Item_param *param, uchar param_type)
```
> #1906 ps bug

- src/main/java/com/actiontech/dble/plan/common/item/function/timefunc/ItemFuncCurdateUtc.java
- src/main/java/com/actiontech/dble/plan/common/time/MySQLTime.java
- src/main/java/com/actiontech/dble/util/DateUtil.java
- src/test/java/com/actiontech/dble/util/DateUtilTest.java
Reason:  
  BUG #1913 #1914 
Type:  
  BUG
Influences：  
  fix: datediff calculation error and two cases
> #1913 #1914  datediff calculation error and two cases

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG #1863 
Type:  
  BUG  
Influences：  
   fix for SubQueryIn when route with the update/delete statment
  fix for error message type of update/delete
> Inner 331 337 fix for #1863

- src/main/java/com/actiontech/dble/sqlengine/MultiTablesMetaJob.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  add log of show create table xxx when dble reloads metadata
> add log of show create table xxx when dble reloads config

- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/util/DateUtil.java
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  ParseDate remove ParseException
> perf: remove excess exception

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
Type:  
  Improve  
Influences：  
   need fresh connection pool if maxCon or minCon was changed in db.xml when reloading config
> need fresh connection pool if maxCon or minCon was changed in db.xml when reloading config

- src/main/java/com/actiontech/dble/manager/response/CheckFullMetaData.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnection.java
- src/main/java/com/actiontech/dble/net/handler/ShardingUserCommandHandler.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/FieldListHandler.java
- src/main/java/com/actiontech/dble/server/handler/MysqlInformationSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/SelectInformationSchemaColumnsHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  Improve #1906
Type:  
  Improve  
Influences：  
   supports some sql pushed by OGG
> supports some sql pushed by OGG

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner 339 fix for #1863
> Inner 339 fix for #1863

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner 340 fix for #1863
> Inner 340 fix for #1863

- src/main/java/com/actiontech/dble/backend/pool/PoolConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowHeartbeat.java
Reason:  
  BUG #inner 299. 
Type:  
  BUG 
Influences：  
  column of stop is true in recover time set by stop heartbeat
> column of stop is true in recover time set by stop heartbeat

- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/SelectInformationSchemaColumnsHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix query information_schema.columns
> fix: query information_schema.columns

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG #inner 336. 
Type:  
Influences：  
  can't fill connection pool to minCon
> can't fill connection pool to minCon

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
Reason:  
  BUG #inner 324.
Type:  
Influences：  
  can't stop previous active connection when reload @@config_all -f
> can't stop previous active connection when reload @@config_all -f

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #1760 . 
Type:  
  BUG
Influences：  
  ddl is not allowed to be executed in xa transaction
> ddl is not allowed to be executed in xa transaction

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
Reason:  
     Improve #1879 .  
Type:  
  Improve  
Influences：  
  Fix some bug about connection pool
> Fix some bug about connection pool

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner 343 fix for #1863
> Inner 343 fix for #1863

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/manager/handler/ShowHandler.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnectionPoolProperty.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
Reason:  
Type:  
  Improve  
Influences：  
  add show @@connection_pool
> add show @@connection_pool

- docker-images/quick-start/bootstrap.cnf
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG #1701
Type:  
  BUG
Influences：  
   fix Improve log generation path description such as view
> #1701 Improve log generation path description such as view

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner 341 342 fix for #1863
> Inner 341 342 fix for #1863

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
Reason:  
  BUG #inner233. 
Type:  
  BUG
Influences：  
  fix bug when connection is closed in check
> fix bug when connection for heartbeat is closed in check

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  BUG #1701 
Type:  
  BUG
Influences：  
   fix : trim log paths ,remove redundant '/'
> trim log paths ,remove redundant '/'

- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterTableParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropIndexParser.java
Reason:  
  Improve #1848.  
Type:  
  Improve  
Influences：  
  add extra online ddl
> add extra online ddl

- src/main/java/com/actiontech/dble/server/ServerConnection.java
- src/main/java/com/actiontech/dble/server/handler/FieldListHandler.java
- src/main/java/com/actiontech/dble/server/handler/SelectInformationSchemaColumnsHandler.java
- src/main/java/com/actiontech/dble/server/handler/ServerPrepareHandler.java
Reason:  
  BUG #1939
Type:  
  BUG
Influences：  
   fix 
1.#1939 value accumulation occurs when adding/modifying long data
2. support for ogg to synchronize data，when the vertical table
3. in the construction of field_list, perfecting data types
> #1939 value accumulation occurs when adding/modifying long data 、other repair

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner 359 361 fix for #1863
> Inner 359 361 fix for #1863

- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
Reason:  
  BUG ucore alert  
Type:  
  BUG  
Influences：  
   fix for alert resolve timestamp
> Inner fix for alter resolve timestamp

- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
- src/main/java/com/actiontech/dble/plan/node/TableNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner fix 363 364 for #1863
> Inner fix 363 364 for #1863

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   Inner fix 367 368 for #1863
> Inner fix 367 368 for #1863

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLDbLoader.java
Reason:  
  Improve   
Type:  
  Improve  
Influences：  
  improve log about delayThreshold and check readWeight
> improve log about delayThreshold and check readWeight

- src/main/java/com/actiontech/dble/plan/node/JoinInnerNode.java
- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
Reason:  
  BUG #1863
Type:  
  BUG  
Influences：  
  Inner fix 369 for #1863
> Inner fix 369 for #1863

- src/main/java/com/actiontech/dble/plan/node/JoinInnerNode.java
- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
  Inner fix 371 for #1863
> Inner fix 371 for #1863

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG #inner 336
Type:  
  BUG
Influences：  
  retry to do heartbeat when connection for heartbeat is closed
> retry to do heartbeat when connection for heartbeat is closed

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/manager/response/RollbackConfig.java
Reason:  
  BUG #inner374. 
Type:  
  BUG
Influences：  
  avoid recycleGroup == newGroup, can't stop recycleGroup
> fix bug when rollback config

- src/main/java/com/actiontech/dble/cluster/values/DDLInfo.java
Reason:  
  BUG #1871   
Type:  
  BUG  
Influences：  
   fix for #1871 cherry-pick from 4e3ad4905f5b4ea10b22c0921e996712d3dea9b1
> fix for #1871 cherry-pick from 4e3ad4905f5b4ea10b22c0921e996712d3dea9b1

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/AIOAcceptor.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/NIOAcceptor.java
- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  BUG #inner 393. 
Type:  
  BUG
Influences：  
  add idleTimeout in bootstrap.cnf and field list bug
> add idleTimeout in bootstrap.cnf and field list bug

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG from autotest
Type:  
  BUG 
Influences：  
   buffer safe
> buffer safe bug

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FieldListHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/UnionHandler.java
- src/main/java/com/actiontech/dble/meta/TableMeta.java
- src/main/java/com/actiontech/dble/net/mysql/FieldPacket.java
Reason:  
  BUG
Type:  
  BUG  
Influences：  
  fix: perfect fieldPacket  and assignment default
> Inner 360 for FIELD_LIST Response

- src/main/java/com/actiontech/dble/meta/TableMeta.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  fix: rollback to upper
> fix: rollback to upper

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FieldListHandler.java
- src/main/java/com/actiontech/dble/server/response/FieldList.java
- version.txt
Reason:  
  BUG #inner 360.
Type:  
  BUG  
Influences：  
  fix bug in connection close about field list
> fix bug in connection close about field list

- src/main/java/com/actiontech/dble/cluster/zkprocess/xmltozk/listen/OtherMsgTozkLoader.java
Reason:  
  BUG Inner 412
Type:  
  BUG
Influences：  
  fix: NPE caused by create view operation in cluster state
> fix: NPE caused by create view operation in cluster state

- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG #inner396.
Type:  
  BUG 
Influences：  
  fix bug on ddl in cluster
> fix bug on ddl in cluster

- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/net/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/NIOSocketWR.java
Reason:  
  BUG inner 276 
Type:  
  BUG
Influences：  
  fix when load data,update the readTime of the frontend connection
> fix：when load data, update the readTime of the frontend connection (inner bug276)

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863  
Type:  
  BUG  
Influences：  
   change the equals order to avoid NullPointerException
> inner 417 fix for #1863

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/FieldListHandler.java
Reason:  
  BUG Inner 360
Type:  
  BUG
Influences：  
  fix: NPE appearing in show tables
> fix: NPE appearing in show tables

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/util/ConditionUtil.java
Reason:  
  BUG #1863.  
Type:  
  BUG  
Influences：  
   Add schemaConfig null check when visite the sql
> inner 424 fix for #1863

- src/main/java/com/actiontech/dble/backend/mysql/view/KVStoreRepository.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   view hang ,inner-420
> view hang ,inner-420

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/cluster/general/response/BinlogPauseStatusResponse.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/zktoxml/listen/BinlogPauseStatusListener.java
- src/main/java/com/actiontech/dble/manager/response/ShowBinlogStatus.java
Reason:  
  BUG cluster_binlog_pasue
Type:  
  BUG
Influences：  
   fix xx
> cluster_binlog_pasue

- docker-images/quick-start/cluster.cnf
- docker-images/quick-start/start_mgr.sh
- src/main/assembly/bin/dble_datahosts_check.py
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix test the problems encountered during inner 311
> to solve test the problems encountered during inner 311

- src/main/java/com/actiontech/dble/backend/mysql/view/KVStoreRepository.java
- src/main/java/com/actiontech/dble/cluster/ClusterPathUtil.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
Reason:  
  BUG inner 428
Type:  
  BUG
Influences：  
  syncMeta lock
> inner 428 syncMeta lock

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
   Improve inner333.  
Type:  
  Improve  
Influences：  
  add log or alert for connection pool
> add log or alert for connection pool

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  add log in MultiNodeQueryHandler
> add log in MultiNodeQueryHandler

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG #1863
Type:  
  BUG  
Influences：  
   #1863 fix for inner 424 to avoid NullPointerException
> #1863 fix for inner
