- src/main/java/com/actiontech/dble/cluster/logic/ConfigClusterLogic.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  fix  dble need write file in cluster operations inner 1409
> fix  dble need write file in cluster operations inner 1409

- src/main/java/com/actiontech/dble/net/SocketWR.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOWriteHandler.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
  BUG  fix flow control doesn't work when close suddenly
Type:  
  BUG
Influences：  
   flowcontrol
> inner-1294: fix flow control doesn't work when close suddenly

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:  
  BUG inner-1308:fix cleanup operations trigger simultaneously.
Type:  
  BUG
Influences：  
    cleanup  when close
> inner-1308:fix cleanup operations  trigger simultaneously.

- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
  BUG inner-1443::fix :memory leak when suddenly close
Type:  
  BUG
Influences：  
   write logic
> inner-1443:fix :memory leak when suddenly close

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix READ_LOAD and WRITE_LOAD are always displayed as 0 inner 1445

- src/main/java/com/actiontech/dble/cluster/AbstractGeneralListener.java
- src/main/java/com/actiontech/dble/cluster/general/response/PauseShardingNodeResponse.java
Reason:  
  BUG inner-1446: pause doesn't work in ucore
Type:  
  BUG  
Influences：  
  pause in ucore
> inner-1446: pause doesn't work in ucore

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
  BUG cherry-pick: inner-1443:fix :memory leak when suddenly close 
Type:  
  BUG
Influences：  
   fix xx
> cherry-pick: inner-1443:fix :memory leak when suddenly close 

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
Reason:  
  BUG #inner 1430.
Type:  
  BUG
Influences：  
  inner 1430 - fix deadlock between close and backend cleaner
> inner 1430 - fix deadlock between close and backend cleaner

- src/main/java/com/actiontech/dble/cluster/AbstractClusterSender.java
- src/main/java/com/actiontech/dble/cluster/impl/UcoreSender.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix distributed locks not release inner 1456

- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG #inner 1454.
Type:  
  BUG 
Influences：  
  inner 1454 - release serializable lock when front connection is closed
> inner 1454 - release serializable lock when front connection is closed

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/ResultDiskBuffer.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/SortedResultDiskBuffer.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/UnSortedResultDiskBuffer.java
Reason:  
  BUG fix memory leaks on  inner-1461/inner-1462/inner-1457/inner-1463
Type:  
  BUG
Influences：  
   memory recycle
>  fix memory leaks on inner-1461/inner-1462/inner-1457/inner-1463

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLDataSource.java
- src/main/java/com/actiontech/dble/config/loader/xml/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSingleUnitSelectParser.java
- src/main/java/com/actiontech/dble/util/PasswordAuthPlugin.java
Reason:  
Type:  
Influences：  
   fix xx
> 2.19.03/lts

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix READ_LOAD and WRITE_LOAD are always displayed as 0 inner 1445 (#2938)

- src/main/java/com/actiontech/dble/btrace/provider/SplitFileProvider.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileConfig.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileContext.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/DefaultValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/ShardingValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertLexer.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertParser.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertQueryPos.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitDumpHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/DumpFileError.java
- src/test/java/com/actiontech/dble/manager/SplitCSVTest.java
Reason:  
  Improve inner-1444
Type:  
  Improve  
Influences：  
fix: optimize split
> improve: optimize split

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
Reason:  
  Improve: inner-1461:remove-duplicate-code
Type:  
  Improve  
Influences：  
   fix xx
> inner-1461:remove-duplicate-code

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/ResultDiskBuffer.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/SortedResultDiskBuffer.java
- src/main/java/com/actiontech/dble/backend/mysql/store/diskbuffer/UnSortedResultDiskBuffer.java
- src/main/java/com/actiontech/dble/services/factorys/FinalHandlerFactory.java
Reason:  
  BUG cherry pick :fix memory leaks on inner-1461/inner-1462/inner-1457
Type:  
  BUG  
Influences：  
   direct memory
> cherry pick :fix memory leaks on inner-1461/inner-1462/inner-1457

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
Type:  
Influences：  
   fix xx
> Standardize 'group by' pushdown to MySQL and fix #1451 TableNode group by push down do not change to alias

- src/main/java/com/actiontech/dble/meta/table/AbstractTableMetaHandler.java
Reason:  
  BUG inner-1481: ddl response cause hang and NPE
Type:  
  BUG
Influences：  
   ddl
> inner-1481: ddl response cause hang and NPE

- src/main/java/com/actiontech/dble/meta/table/AbstractTableMetaHandler.java
Reason:  
  BUG inner-1481: ddl response cause hang and NPE (#2964)
Type:  
  BUG inner-1481
Influences：  
   fix xx
> cherry-pick:inner-1481: ddl response cause hang and NPE (#2964)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
  fix case  : on a.id = b.id and (a.name = 'aa' or a.name= 'bb')  -> on a.id = b.id and a.name = 'aa' or a.name= 'bb'  error
> fix or condition in on join filter

- src/main/java/com/actiontech/dble/net/NIOProcessor.java
- src/main/java/com/actiontech/dble/plan/common/field/Field.java
- src/main/java/com/actiontech/dble/plan/common/field/FieldNull.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
  fix : select null as aaa from sharding_a union select null as bbb from sharding_b
> fix bug that dble can't find null constant column in select list

- src/main/java/com/actiontech/dble/plan/optimizer/FilterJoinColumnPusher.java
- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG.
Type:  
  BUG
Influences：  
  fix ClassCastException when splitting or condition
> fix ClassCastException when splitting or condition

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinProcessor.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG inner-1471: modify join order use hint
Type:  
  BUG
Influences：  
   join order
> inner-1471: modify join order use hint

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  inner 1494
Type:  
  BUG 
Influences：  
   abort optimize when Cartesian with relation
> abort optimize when Cartesian with relation

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/plan/optimizer/HintNode.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinProcessor.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/test/java/com/actiontech/dble/optimizer/BaseSqlHintTest.java
- src/test/java/com/actiontech/dble/optimizer/FakeConnection.java
- src/test/java/com/actiontech/dble/optimizer/JoinUseHintTest.java
- src/test/resources/sharding.xml
- src/test/resources/user.xml
Reason:  
  BUG inner-1471-supplement: fix bug&structure adjust& add unit test
Type:  
  BUG
Influences：  
   optimize join order use hints.
> inner-1471-supplement: fix bug&structure adjust& add unit test

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileConfig.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/SchemaHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/ShardingValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/TableHandler.java
Reason:  
  BUG inner-1496
Type:  
  BUG
Influences：  
fix: exception handling
queue default value modification
dos newline handling 
for druid does not support the processing of \r
> fix: exception handling & dos newline(\r) handling

- docker-images/dble-image/rwSplit/bootstrap.cnf
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner 1305
Type:  
  Improve  
Influences：  
  
> Support stickiness for read and write instances

- src/main/java/com/actiontech/dble/route/parser/util/ParseUtil.java
- src/test/java/com/actiontech/dble/parser/ServerParseTest.java
Reason:  
  BUG #2981.
Type:  
  BUG
Influences：  
  parse multi sql error
> issue 2981 - parse multi sql error

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
Reason:  
  BUG inner-1510
Type:  
  BUG
Influences：  
fix: the split command will not be controlled by idleTime
> fix: the split command will not be controlled by idleTime

- src/main/java/com/actiontech/dble/services/manager/handler/ClusterManageHandler.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG inner-1415: pause return two error message
Type:  
  BUG
Influences：  
   pause
> inner-1415: pause return two error message

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner 1517/1518
Type:  
  BUG 
Influences：  
   join other on
> inner 1517 no need add other on

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitDumpHandler.java
Reason:  
  BUG inner-1496
Type:  
  BUG
Influences：  
fix: handle error
> fix: handle error

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner 1512 
Type:  
  BUG 
Influences：  
   join order will not change
> inner 1512 keep order

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
   Improve 1519
Type:  
   Improve  
Influences：  
  single subquery
> inner-1519

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
Reason:
  BUG inner-1510
Type:
  BUG
Influences：
fix: the split command will not be controlled by idleTime
fix: connection skipIdleCheck status reset
> fix: the split command will not be controlled by idleTime(cherry-pick & merge from 3.21.02.99) 

- src/main/java/com/actiontech/dble/manager/ManagerQueryHandler.java
Reason:  
  BUG inner-1510
Type:  
  BUG
Influences：  
fix: connection skipIdleCheck status reset
> fix: connection skipIdleCheck status reset

- src/main/java/com/actiontech/dble/btrace/provider/SplitFileProvider.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileConfig.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileContext.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileExecutor.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileReader.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileWriter.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/DefaultValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/SchemaHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/ShardingValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/TableHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertLexer.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertParser.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertQueryPos.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitDumpHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/DumpFileError.java
- src/test/java/com/actiontech/dble/manager/SplitCSVTest.java
Reason:
  BUG inner-1444
Type:
  BUG
Influences：
fix: optimize split(#2960)
DBLE0REQ-1444
fix: exception handling & dos newline(\r) handling (#2979)
fix: handle error (#2989)
> fix: optimize split(cherry-pick & merge from 3.21.02.99)

- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
Reason:
  BUG inner-1510
Type:
  BUG
Influences：
fix: the split command will not be controlled by idleTime
fix: connection skipIdleCheck status reset
> fix: the split command will not be controlled by idleTime(cherry-pick & merge from 3.21.02.99)

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG topo order
Type:  
  BUG
Influences：  
   all topo order
> inner 1530 reorder topo

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner 1528 
Type:  
  BUG 
Influences：  
   support non left-deep join trees, eg:right->left
> support non left-deep join trees, eg:right->left

- src/main/java/com/actiontech/dble/memory/unsafe/utils/JavaUtils.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDirectMemory.java
Reason:  
  BUG inner-1548: fix rounding problem in show @@directmemory
Type:  
  BUG
Influences：  
   show @@directmemory
> inner-1548: fix rounding problem in show @@directmemory

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDbInstanceSyn.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDbInstanceSynDetail.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeatDetail.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/statistic/DbInstanceSyncRecorder.java
- src/main/java/com/actiontech/dble/statistic/HeartbeatRecorder.java
Reason:  
   Improve to avoid big records 
Type:  
   Improve  
Influences：  
   manager cmd
> add close conf for record heartbeat

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1543
Type:  
  BUG
Influences：  
   fix: the ddl execution results are pushed twice in the cluster
> fix: the ddl execution results are pushed twice in the cluster

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/manager/response/ShowSysParam.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  Improve inner-1374:  RoutePenetration support
Type:  
  Improve  
Influences：  
   fix xx
> inner-1374:  RoutePenetration support

- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertParser.java
Reason:  
  BUG inner-1549
Type:  
  BUG
Influences：  
fix:column name parsing error
> fix:column name parsing error

- src/main/java/com/actiontech/dble/route/parser/DbleHintParser.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/test/java/com/actiontech/dble/parser/DbleHintParserTest.java
Reason:  
  BUG inner#1541.
Type:  
  BUG  
Influences：  
  execute sql that contains comment hang,eg: /* xxx*/ select * from test
> inner 1541 - execute sql that contains comment hang

- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
   Improve inner 1508
Type:  
   Improve  
Influences：  
   1. fix which import from [3 table union order](https://github.com/actiontech/dble/commit/5a1275fd79b69e4033b92e318e1b8763069be97f#diff-ca61a3fd07652b1b6d9d7f49d49c01bbac574cea17e4160737db5d7bbb160eb2)
   2. if  table-node's function is not an aggregate function,  it will be pushed down
> Select item optimizer

- src/main/java/com/actiontech/dble/net/ConnectionException.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG inner-1531: show detail error message when auth failed.
Type:  
  BUG 
Influences：  
   fix xx
> inner-1531: show detail error message when auth failed.

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
     Improve inner-1374:  Improve readability
Type:  
  Improve  
Influences：  
   fix xx
> inner-1374:  Improve readability

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/test/java/com/actiontech/dble/optimizer/JoinUseHintTest.java
Reason:  
  BUG inner-1471-bug:fix for explain doesn't work
Type:  
  BUG
Influences：  
   fix xx
> inner-1471-bug:fix for explain doesn't work

- src/main/java/com/actiontech/dble/services/manager/dump/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/parse/InsertParser.java
Reason:
  BUG inner-1549
Type:
  BUG
Influences：
fix:column name parsing error
#3022
> fix:column name parsing error(cherry pick from 3.21.02.99)

- src/main/java/com/actiontech/dble/memory/unsafe/utils/JavaUtils.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDirectMemory.java
Reason:  
  BUG inner-1544: fix LVS/SLB heartbeat cause memory leak 
inner-1548: fix rounding problem in show @@directmemory 
Type:  
  BUG
Influences：  
   directmemory
> cherrypick:inner-1544: fix LVS/SLB heartbeat cause memory leak & inner-1548: fix rounding problem in show @@directmemory 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG inner 1560 or Improve inner 1562
Type:  
Influences：  
   1508
> Inner 1508

- pom.xml
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/log/transaction/TxnLogProcessor.java
- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
Type:  
Influences：  
   fix xx
> update log4j version and merge #1631,#1705,#2208

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/plan/common/item/Item.java
Reason:  
  BUG Chinese column  name/alias
Type:  
  BUG
Influences：  
   fix xx
> 1508 chinese col name

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
Reason:  
  Improve inner-1535: modify tip of show slave status.
Type:  
  Improve  
Influences：  
   fix xx
> inner-1535: modify tip of show slave status.

- src/main/java/com/actiontech/dble/net/Session.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/response/ShowDbleProcessList.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerSession.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
Reason:  
    Improve flowcontrol_rw_split
Type:  
    Improve  
Influences：  
   add flowcontrol_rw_split
> flowcontrol_rw_split

- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix failed to release the distributed lock inner 1515

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
Reason:  
  Improve optimize writeToBuffer
Type:  
  Improve
Influences：  
   fix xx
> optimize writeToBuffer

- src/main/java/com/actiontech/dble/plan/common/item/function/ItemCreate.java
- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncUuid.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG #2914 
Type:  
  BUG
Influences：  
fix: add function uuid
> fix: add function uuid

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/subquery/SingleRowSubQueryHandler.java
- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/util/PlanUtil.java
Reason:  
  BUG inner-1569 /inner-1570
Type:  
  BUG 
Influences：  
  inner-1569 /inner-1570
> Optimizer bug

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowFieldsHandler.java
- src/main/java/com/actiontech/dble/net/response/FieldListResponseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
   Improve #inner 1580.  
Type:  
  Improve  
Influences：  
  support com_field_list protocol for rw
> inner-1580:support com_field_list protocol for rw

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
Reason:  
  BUG inner 1583
Type:  
  BUG
Influences：  
   fix xx
> [inner-1583] remove multiple errors

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/MultiNodeDdlPrepareHandler.java
Reason:  
  BUG inner 1584
Type:  
  BUG
Influences：  
   fix: Unreleased lock occurred during the ddl'test-phase when sharding table exception occurred
> [inner-1584] Unreleased lock occurred during the ddl'test-phase when sharding table exception occurred

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/meta/table/DDLNotifyTableMetaHandler.java
Reason:  
  BUG inner 1585
Type:  
  BUG
Influences：  
   fix xx
> [inner-1585] fix NPE

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/route/handler/HintMasterDBHandler.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/response/FreshBackendConn.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/test/java/com/actiontech/dble/config/ConfigTest.java
Reason:  
  BUG inner-1572
Type:  
  BUG
Influences：  
fix: reselect when dbGroup fails
> fix: reselect when dbGroup fails

- src/main/java/com/actiontech/dble/backend/mysql/view/FileSystemRepository.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
Reason:  
  BUG inner-1478
Type:  
  BUG
Influences：  
   fix xx
> [inner-1478] create vertical view without falling disk

- src/main/java/com/actiontech/dble/net/response/FieldListResponseHandler.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/SetHandler.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/ShowFieldsHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/ScriptPrepareHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  support com_field_list protocol for rw
> support com_field_list protocol for rw

- dble_checkstyle_suppression.xml
- src/main/java/com/actiontech/dble/cluster/general/impl/MetaDataClientInterceptor.java
- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
Reason:  
  Improve #inner 1563.  
Type:  
  Improve  
Influences：  
  add header metadata for grpc
> inner 1563 - add header metadata for grpc

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
- src/main/java/com/actiontech/dble/plan/common/field/Field.java
- src/main/java/com/actiontech/dble/plan/common/field/FieldNull.java
Reason:  
  BUG.
Type:  
  BUG
Influences：  
   fix xx
> cherry pick from huaxia

- src/main/java/com/actiontech/dble/backend/mysql/ByteUtil.java
- src/main/java/com/actiontech/dble/net/mysql/PreparedClosePacket.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/Callback.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PSHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PreparedStatementHolder.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/ScriptPrepareHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
Reason:  
  BUG #inner 1475.  
Type:  
  BUG  
Influences：  
  strength prepare statement protocol
> strength prepare statement protocol

- src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/PacketResult.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  
> fix Distributed lock release and data return timing

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/MultiNodeDdlPrepareHandler.java
Reason:  
Type:  
Influences：  
   fix xx
> ddl's prepare-stage must send the master instance

- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
Reason:  
   Improve inner 1474
Type:  
  improve  
Influences：  
   fix xx
> [inner-1474]specify 'in' in Hint to transform to 'join'

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
Reason:  
  Bug inner 1591
Type:  
  BUG
Influences：  
   fix xx
> [inner-1591] fix hang

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDbInstanceSyn.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowDbInstanceSynDetail.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeatDetail.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/statistic/DbInstanceSyncRecorder.java
- src/main/java/com/actiontech/dble/statistic/HeartbeatRecorder.java
Reason:  
  BUG inner-1552:add close conf for record heartbeat 
Type:  
  BUG
Influences：  
   heartbeat
> inner-1552:add close conf for record heartbeat (#3020)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ShowTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemAllAnySubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemExistsSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemInSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemMultiRowSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemScalarSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemSingleRowSubQuery.java
- src/main/java/com/actiontech/dble/plan/common/item/subquery/ItemSubQuery.java
- src/main/java/com/actiontech/dble/plan/optimizer/HintPlanInfo.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
- src/main/java/com/actiontech/dble/route/handler/HintPlanHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/main/java/com/actiontech/dble/server/response/ShowTables.java
- src/main/java/com/actiontech/dble/services/manager/ManagerSession.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerBaseView.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/test/java/com/actiontech/dble/optimizer/BaseSqlHintTest.java
- src/test/java/com/actiontech/dble/plan/visitor/TestMySQLItemVisitor.java
- src/test/java/com/actiontech/dble/plan/visitor/TestMySQLPlanNodeVisitor.java
Reason:  
  Improve inner 1473 
Type:  
  Improve  
Influences：  
   fix xx
> [inner-1473]Hint specifies left/right inner replaced by inner join

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/MultiNodeDdlPrepareHandler.java
Reason:  
  BUG inner 1598
Type:  
  BUG
Influences：  
   fix xx
> [inner-1598] fix ddl logs's npe

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1556:report error too long
Type:  
  BUG
Influences：  
   fix xx
> inner-1556:report error too long

- src/main/java/com/actiontech/dble/net/impl/nio/NIOReactor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/service/AuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  Improve: inner-1554: optimize log for heartbeat of SLB/LVS
Type:  
   Improve  
Influences：  
  log
> inner-1554: optimize log for heartbeat of SLB/LVS

- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
Reason:  
  BUG inner-1374-bugfix: config file name error
Type:  
  BUG
Influences：
> inner-1374-bugfix: config file name error

- src/main/java/com/actiontech/dble/util/SelectorUtil.java
Reason:  
  BUG inner-1579
Type:  
  BUG
Influences：  
fix:only cancel if the connection is not pending
> fix:only cancel if the connection is not pending

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/MultiNodeDdlPrepareHandler.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1604] fix: not need to bring 'set autocommit = 0' before executing DDL

- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
Reason:  
  BUG innert-1594
Type:  
  BUG
Influences：  
fix: adjust rw checkSchema to select instance mode
> fix: adjust rw checkSchema to select instance mode

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:
  BUG inner-1595
Type:
  BUG
Influences：
fix: judging string is empty
> fix: judging string is empty

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG inner-1543/1498
Type:  
Influences：  
   fix xx
> [inner-1543/1498] fix：second push and ddl's hang

- src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/PacketResult.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix distributed lock release timing inner 1590

- src/main/java/com/actiontech/dble/singleton/RouteService.java
Reason:  
  BUG innert-1484
Type:  
  BUG
Influences：  
fix: rwSplit hint error
> fix: rwSplit hint error

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix read_load and write_load  displayed error inner 1445

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG inner 1602
Type:  
  BUG 
Influences：  
   fix xx
> [inner-1602] fix: where condition missing in single node sql

- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
Reason:  
  BUG inner-1581-supplement:fix for checkstyle
Type:  
  BUG
Influences：  
   checkstyle
> inner-1581-supplement:fix for checkstyle

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG inner-1427:fix table with alias will route all.
Type:  
  BUG
Influences：  
   fix xx
> inner-1427:fix table with alias will route all.

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
Reason:  
  BUG inner-1484
Type:  
  BUG
Influences：  
fix: hint does not use sticky connections
> fix: hint does not use sticky connections

- src/main/java/com/actiontech/dble/DbleServer.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix init tmManager inner  1603

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/DDLHandlerBuilder.java
- src/main/java/com/actiontech/dble/cluster/logic/DDLClusterLogic.java
- src/main/java/com/actiontech/dble/meta/DDLProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/DDLNotifyTableMetaHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/singleton/DDLTraceHelper.java
Reason:  
  BUG inner 1612 
Type:  
  BUG 
Influences：  
   fix xx
> [inner-1612] add release_table_lock stage

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOReactor.java
Reason:  
  Improve inner-1554-supplement: optimize log for heartbeat of SLB/LVS
Type:  
  Improve  
Influences：  
   log
> inner-1554-supplement: optimize log for heartbeat of SLB/LVS

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  Improve inner/1581-supplement: optimize writeToBuffer
Type:  
  Improve  
Influences：  
  
> inner-1581-supplement: optimize writeToBuffer

- src/main/java/com/actiontech/dble/net/Session.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/response/ShowDbleProcessList.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerSession.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/response/FlowControlList.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
Reason:  
  Improve inner-1581:flowcontrol_rw_split 
Type:  
     Improve
Influences：  
   fix xx
> inner-1581:flowcontrol_rw_split 

- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
- src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/PacketResult.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix failed to release the distributed lock inner 1515 & 1590

- src/main/java/com/actiontech/dble/meta/DDLProxyMetaManager.java
- src/main/java/com/actiontech/dble/meta/table/DDLNotifyTableMetaHandler.java
Reason:  
  BUG inner 1619
Type:  
Influences：  
   fix xx
> [inner-1619] fix：illegal symbol '’'

- src/main/java/com/actiontech/dble/backend/mysql/ByteUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/net/mysql/PreparedClosePacket.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidImplicitCommitParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidLockTableParser.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/Callback.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PSHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PreparedStatementHolder.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/ScriptPrepareHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
Reason:  
  BUG #inner 1475. 
Type:  
  BUG
Influences：  
     strength prepare statement protocol
> inner 1475 - strength prepare statement protocol

- src/main/java/com/actiontech/dble/plan/optimizer/HintPlanInfo.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/test/java/com/actiontech/dble/optimizer/JoinUseHintTest.java
Reason:  
  BUG inner-1471-bugfix: report error message on some conditions
Type:  
  BUG
Influences：  
   fix xx
> inner-1471-bugfix: report error message on some conditions

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG inner-1613: fix select may send without limit
Type:  
  BUG
Influences：  
   select with singleTable
> inner-1613: fix select may send without limit

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
Reason:  
  BUG inner 1543、1498 , similar pr ：#3075 
Type:  
  BUG
Influences：  
   fix xx
> [inner-1543/1498] fix：second push and ddl's hang (cherry pick)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 1543 , similar pr ：#3075
Type:  
Influences：  
   fix xx
> [inner-1543] fix：second push and ddl's hang (cherry pick)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
Reason:  
  BUG 
Type:  
Influences：  
   fix xx
> [inner-1543/1498] ddl hang

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
- src/main/java/com/actiontech/dble/plan/node/ManagerTableNode.java
- src/main/java/com/actiontech/dble/plan/node/MergeNode.java
Reason:  
  BUG inner 1560/1565
Type:  
  BUG 
Influences：  
   fix field charset
> field charset

- docker-images/mgr/docker-compose.yml
- docker-images/quick-start/docker-compose.yml
- docker-images/rwSplit/docker-compose.yml
Reason:  
Type:  
Influences：  
   fix xx
> correct image name

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
Reason:  
  BUG .  
Type:  
  BUG  
Influences：  
    reset flag when transaction commit error
> reset flag when transaction commit error

- src/main/java/com/actiontech/dble/cluster/logic/PauseResumeClusterLogic.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFlowControl.java
- src/main/java/com/actiontech/dble/services/manager/response/FlowControlList.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQLStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowSession.java
Reason:  
  BUG
Type:  
  BUG
 
> fix service conversion error inner 1600

- src/main/java/com/actiontech/dble/plan/node/MergeNode.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
Reason:  
  BUG inner-1630:charset issue in union
Type:  
  BUG
Influences：  
   fix xx
> inner-1630:charset issue in union

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  BUG 
Type:  
  BUG
> fix thread name matching rules inner 1627

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/manager/response/ShowThreadUsed.java
- src/main/java/com/actiontech/dble/util/ByteUtil.java
Reason:  
Type:  
Influences：  
   fix xx
> fix treemap thread safe #1514 (#1518)  and small int #1491

- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG inner 1508
Type:  
Influences：  
   fix xx
> [inner-1508] remove redundant fields

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/NormalCommitNodesHandler.java
Reason:  
  BUG.  
Type:  
  BUG
Influences：  
  avoid extreme cases
> avoid extreme cases

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeat.java
Reason:  
  BUG inner 1558
Type:  
Influences：  
   fix xx
> [inner-1558] adjust the contents of heartbeat error alarms

- src/main/java/com/actiontech/dble/plan/optimizer/OrderByPusher.java
Reason:  
  BUG inner 1610
Type:  
Influences：  
   fix when the subquery is right Join, the result is incorrect
> [inner-1610] fix：when the subquery is right Join, the result is incorrect

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
Reason:  
  Improve 
Type:  
  Improve
> the alarm optimization inner 1628

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PSHandler.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
Reason:  
  Improve #inner 1622.  
Type:  
  Improve  
Influences：  
   fix xx
> improve rwsplit

- src/main/java/com/actiontech/dble/server/ServerConnection.java
Reason:  
  BUG inner 950；similar pr #2698 
Type:  
Influences：  
   fix xx
> [inner-950] adjust the sequence of locks (cherry pick)

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/UnionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/net/mysql/FieldPacket.java
- src/main/java/com/actiontech/dble/plan/common/field/Field.java
- src/main/java/com/actiontech/dble/plan/common/field/FieldUtil.java
- src/main/java/com/actiontech/dble/plan/common/item/Item.java
- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG： related pr：#2991 、#3029 、#3030     #3131 、
Type:  
Influences：  
   fix xx
> [inner-1647] cherry pick from inner-1508

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/TableNodeHandlerBuilder.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix where condition miss when try nest loop  inner 1644

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
   Improve inner-1648: report The ER relation limit
Type:  
  Improve  
Influences：  
   hint
> inner-1648: report The ER relation limit

- src/main/java/com/actiontech/dble/backend/mysql/store/fs/FileUtils.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/SplitLoadDataHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/split/loaddata/DumpFileReader.java
- src/main/java/com/actiontech/dble/services/manager/split/loaddata/ShardingNodeWriter.java
Reason:
  Improve inner-1426
Type:
  Improve
Influences：
fix: add split_loaddata
> fix: add split_loaddata

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  Improve : inner-1654:optimize report for hint
Type:  
  Improve  
Influences：  
   hint
> inner-1654:optimize report for hint

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HintNestLoopHelper.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix nestloop sql hang inner 1651

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
   Improve inner-1648-supplement: syntax error when report  The ER relation limit
Type:  
  Improve  
Influences：  
   report syntax
> inner-1648-supplement: syntax error when report  The ER relation limit

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG inner-1650
Type:  
  BUG
Influences：  
fix: support BIN/SUBSTRING function
BIN:https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bin
SUBSTRING:https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring
> fix: support BIN/SUBSTRING function

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
   Improve .  
Type:  
  Improve  
Influences：  
  improve heartbeat log
> improve heartbeat and add log

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:
  BUG inner-1650
Type:
  BUG
Influences：
#3161 
fix: support BIN/SUBSTRING function
BIN:https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bin
SUBSTRING:https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring
> fix: support BIN/SUBSTRING function(conflict)

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  cherry pick from 3.21.02
> improve heartbeat log

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinProcessor.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
Reason:  
  BUG inner-1669: no need to optimize join if the hint order same as the execution plan tree
Type:  
  BUG
Influences：  
  hint order
> inner-1669: no need to optimize join if the hint order same as execution plan tree

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinProcessor.java
- src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
Reason:  
  BUG Revert "inner-1669: no need to optimize join if the hint order same as execution plan tree (#3162)"
Type:  
  BUG
Influences：  
   join order
> Revert "inner-1669: no need to optimize join if the hint order same as execution plan tree (#3162)"

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
Reason:  
  BUG inner-1672: column around with `` can't be route
Type:  
  BUG
Influences：  
   route
> inner-1672: column around with `` can't be route

- src/main/java/com/actiontech/dble/net/Session.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/response/ShowDbleProcessList.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerSession.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/ProcessList.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowProcessList.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowSession.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/ScriptPrepareHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/TempTableHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/XaHandler.java
- src/main/java/com/actiontech/dble/sqlengine/SetTestJob.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticListener.java
Reason:  
  Improve inner-1581:flowcontrol_rw_split  (#3082)]
Type:  
  Improve
Influences：  
   flow control
> inner-1581:flowcontrol_rw_split  (#3082)]

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeAndOrderHandler.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
Reason:  
  BUG  
Type:  
  BUG
Influences：  
   fix xx
> fix nest loop in er condition error inner 1655

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1666: discard left join when both left join and inner join exists
Type:  
  BUG
Influences：  
   join with hint
> inner-1666: discard left join when both left join and inner join exists

- src/main/java/com/actiontech/dble/util/ByteUtil.java
Reason:  
  BUG #3175. 
Type:  
  BUG
Influences：  
  short value of row data protocol fails to convert to  binary protocol
> #3175 - short value of row data protocol fails to convert to  binary protocol

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG inner 1674
Type:  
  BUG
Influences：  
   fix: nestloop scenarios's bug
> [inner-1674] fix: nestloop scenarios's bug

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  Improve inner-1374:  RoutePenetration support (#2997)
Type:  
  Improve  
Influences：  
  RoutePenetration
> inner-1374:  RoutePenetration support (#2997)

- src/main/java/com/actiontech/dble/cluster/logic/PauseResumeClusterLogic.java
- src/main/java/com/actiontech/dble/server/handler/KillHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQLStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowSession.java
* fix service conversion error inner 1600
Reason:  
  BUG 
Type:  
Influences：  
   fix xx
> fix service conversion error inner 1600 (#3125)

- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/singleton/XASessionCheck.java
Reason:  
  BUG inner 1586
Type:  
Influences：  
   fix xx
> [inner-1586] during the period of the XA, front and back side accidentally disconnect does not affect the XA retry mechanism

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/Users.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBInstance.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/user/AnalysisUser.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/user/User.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/config/converter/UserConverter.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
- src/main/java/com/actiontech/dble/config/model/db/DbInstanceConfig.java
- src/main/java/com/actiontech/dble/config/model/db/type/DataBaseType.java
- src/main/java/com/actiontech/dble/config/model/user/AnalysisUserConfig.java
- src/main/java/com/actiontech/dble/config/model/user/SingleDbGroupUserConfig.java
- src/main/java/com/actiontech/dble/route/handler/HintDbInstanceHandler.java
- src/main/java/com/actiontech/dble/route/handler/HintMasterDBHandler.java
- src/main/java/com/actiontech/dble/server/variables/VarsExtractorHandler.java
- src/main/java/com/actiontech/dble/services/factorys/BusinessServiceFactory.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBlacklist.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntry.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntryDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowUser.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/resources/db_detail.xsd
- src/main/resources/db_template.xml
- src/main/resources/user.xsd
- src/main/resources/user_detail.xsd
- src/main/resources/user_template.xml
- version.txt
Reason:  
   Improve 
Type:  
  Improve
> support clickhouse inner 1676

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
Reason:  
  BUG inner 1681
Type:  
Influences：  
   fix xx
> [inner-1681] when rwSplitMode="0", don't participate in stickiness

- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileWriter.java
Reason:  
   Improve  
Type:  
  Improve  
Influences：  
   fix xx
> unified format inner 1384

- src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
>  hint transitivity is support  inner 1684

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1667: report an error when using hint with "cartesian with relation"
Type:  
  BUG
Influences：  
   cartesian with relation
> inner-1667: report an error when using hint with "cartesian with relation"

- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
- src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/PacketResult.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/PauseStart.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowBinlogStatus.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Conflicts:
src/main/java/com/actiontech/dble/services/manager/handler/DbGroupHAHandler.java
src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix failed to release the distributed lock inner 1515 & 1590 (#3106)

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1688:refactor the implementation of inner-1666
Type:  
  BUG
Influences：  
   hint route
> inner-1688:refactor the implementation of inner-1666

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/impl/AbstractRouteStrategy.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
- src/main/java/com/actiontech/dble/singleton/RoutePenetrationManager.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  Improve inner-1374: RoutePenetration support (#2997) 
Type:  
  Improve  
Influences：  
   route
> inner-1374: RoutePenetration support (#2997) 

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix rwsplit user sqlExecuteTimeout do not take effects  inner 1696

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  Improve inner-1622.  
Type:  
  Improve  
Influences：  
  cherry pick
> inner 1622 - improve rwSplit

- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/test/java/com/actiontech/dble/route/util/RouterUtilTest.java
Reason:  
  BUG inner-1706
Type:  
  BUG
Influences：  
fix: add backtracking checks
> fix: add backtracking checks

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1705:fix for otherJoinFilter
Type:  
  BUG
Influences：  
   fix xx
> inner-1705:fix for otherJoinFilter

- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBInstance.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQL.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionSQLStatus.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix xx
>  fix clickhouse Incompatible error inner 1697 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
fix
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix sql route error inner 1699

- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
Reason:  
  BUG inner 1661
Type:  
Influences：  
   fix xx
> [inner-1661] fix: when multiple ER filtering conditions in the join on, query result error

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
  improve heartbeat log and avoid the case that heartbeat connection is null
> improve heartbeat log and avoid the case that heartbeat connection is null

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
  add heartbeat tips
> add heartbeat tips

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  fix findbug
> fix findbug

- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
Reason:  
  BUG inner 1712、1713
Type:  
Influences：  
   fix xx
> [inner-1712&1713] fix：can't find column

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix login failure  inner 1698

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
- src/main/java/com/actiontech/dble/sqlengine/OneTimeConnJob.java
Reason:  
  BUG
Type:  
  BUG 
Influences:
cherry pick from 3.21.10.99
  
> fix heartbeat timeout and dryrun bug

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
Reason:  
  BUG inner 1678, similar: #3172 
Type:  
Influences：  
   fix xx
> [inner-1678] fix: nestloop scenarios's bug

- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
Reason:  
  BUG inner-1702
Type:  
  BUG
Influences：  
fix: remove redundant code
> fix: remove redundant code

- src/main/java/com/actiontech/dble/plan/optimizer/SelectedProcessor.java
Reason:  
  BUG inner 1718.
Type:  
  BUG
Influences：  
  no need to push down in func
> inner 1718 - no need to push down in func

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
Reason:  
  BUG #inner 1721.
Type:  
  BUG
Influences：  
   fix missing filed attribute
> inner 1721 - fix missing filed attribute

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix  blacklist of rwuser becomes invalid  issue 3213

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
Reason:  
  BUG inner-1581:fix npe for flow control
Type:  
  BUG
Influences：  
   fix xx
> inner-1581:fix npe for flow control

- src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix add nestloop in er relation inner 1728

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1666:report error instead of merge left join relations
Type:  
  BUG
Influences：  
   join with hint
> inner-1666:report error instead of merge left join relations

- docs/dble_start_docker_compose.md
Reason:  
Type:  
Influences：  
   fix xx
> Fix 404 link

- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
Reason:  
  BUG inner-1730:fix join hint NPE
Type:  
  BUG
Influences：  
   join hint
> inner-1730:fix join hint NPE

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPoolTask.java
Reason:  
  BUG inner-1731: fix dble_thread_pool_task NPE when no config
Type:  
  BUG 
Influences：  
  dble_thread_pool_task
> inner-1731: fix dble_thread_pool_task NPE when no config

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinNodeHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/SendMakeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix xx
> fix hint sql  hang  inner 1733

- src/main/java/com/actiontech/dble/plan/optimizer/ERJoinChooser.java
Reason:  
  BUG similar #3169. #3207 
Type:  
Influences：  
   fix xx
> [inner-1661] fix: when multiple ER filtering conditions in the join on, query result error（cherry pick）

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/SSLProtoHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResult.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResultCode.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/net/factory/SSLEngineFactory.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/mysql/AuthPacket.java
- src/main/java/com/actiontech/dble/net/service/SSLProtoServerTask.java
- src/main/java/com/actiontech/dble/net/service/ServiceTaskType.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/util/SystemProperty.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner 1720
Type:  
  Improve  
Influences：  
   fix xx
> Support SSL

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
Type:  
Influences：  
   fix xx
> SSL code adjust

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-1744
Type:  
  BUG
Influences：  
fix: adjust conditions for associated joins in transactions
* not contains duplicate nodes: shardingNode-MySQLConnection
* contains duplicate nodes: shardingNode+schema.table-MySQLConnection
> fix: adjust conditions for associated joins in transactions

- src/main/java/com/actiontech/dble/server/handler/SelectInformationSchemaColumnsHandler.java
Reason:  
  BUG inner 1747
Type:  
  BUG
Influences：  
   fix xx
> [inner-1747] upper case processing

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAEndStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/CoordinatorLogEntry.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/Deserializer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/ParticipantLogEntry.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/Serializer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XaCheckHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG inner-1744
Type:  
  BUG
Influences：  
fix: xa-id removes shema+table
> fix: xa-id removes shema+table

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAEndStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XAPrepareStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/CoordinatorLogEntry.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/Deserializer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/ParticipantLogEntry.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/Serializer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XAStateLog.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XaCheckHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:
  BUG inner-1744
Type:
  BUG
Influences：
fix: adjust conditions for associated joins in transactions
* not contains duplicate nodes: shardingNode-MySQLConnection
* contains duplicate nodes: shardingNode+schema.table-MySQLConnection
> fix: adjust conditions for associated joins in transactions(cherry-pick)

- src/main/java/com/actiontech/dble/server/handler/MysqlSystemSchemaHandler.java
- src/main/java/com/actiontech/dble/server/handler/SelectInformationSchemaColumnsHandler.java
Reason:  
  BUG similar #3241 
Type:  
Influences：  
   fix xx
> [inner-1747] upper case processing (cherry pick)

- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  Improve 
Type:  
Improve  
Influences：  
   fix xx
> connection closed error optimization inner 1756

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnectionsActiveRatio.java
- src/main/java/com/actiontech/dble/statistic/stat/FrontActiveRatioStat.java
Reason:  
  Improve inner 1106
Type:  
  Improve  
Influences：  
   fix xx
> [inner-1106] Support for viewing frontend connection activity

- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/FetchResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
Reason:  
  BUG inner 1762
Type:  
Influences：  
   fix xx
> [inner-1762] fix：no handler

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix heartbeat timeout inner 1371

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix different types of databases have different check policies inner  1767

- src/main/java/com/actiontech/dble/backend/datasource/LocalReadLoadBalancer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBInstance.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/model/db/DbInstanceConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
- src/main/resources/db_detail.xsd
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> local read support inner 1752

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/statistic/stat/FrontActiveRatioStat.java
Reason:  
  BUG inner 1764、1765
Type:  
Influences：  
   fix xx
> [inner-1764&1765] fix concurrency problems

- pom.xml
Reason:  
  BUG #3265
Type:  
  BUG 
Influences：  
  update fastjson to 1.2.83
> update fastjson to 1.2.83

- pom.xml
Reason:  
  BUG inner-1773:update fastjson version
Type:  
  BUG
Influences：  
   fix xx
> inner-1773:update fastjson version

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix heartbeat timeout inner 1371 (#3248)

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG inner-1751
Type:  
  BUG
Influences：  
fix: adjust the connection acquisition mechanism of the queued threads in the connection pool
> fix: adjust the connection acquisition mechanism of the queued threads in the connection pool

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/executor/BackendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendBlockRunnable.java
- src/main/java/com/actiontech/dble/net/executor/FrontendCurrentRunnable.java
- src/main/java/com/actiontech/dble/net/executor/WriteToBackendRunnable.java
- src/main/java/com/actiontech/dble/net/impl/nio/RW.java
- src/main/java/com/actiontech/dble/net/mysql/WriteToBackendTask.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnectionsAssociateThread.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnectionsAssociateThread.java
- src/main/java/com/actiontech/dble/singleton/ConnectionAssociateThreadManager.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  BUG inner 1106
Type:  
Influences：  
   fix xx
> [inner-1106] view the frontend and backend connections associated with threads

- src/main/java/com/actiontech/dble/backend/datasource/LocalReadLoadBalancer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix local read error  inner 1780 & 1775

- src/main/java/com/actiontech/dble/cluster/ClusterGeneralConfig.java
- src/main/java/com/actiontech/dble/cluster/general/AbstractConsulSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleClusterRenewThread.java
- src/main/java/com/actiontech/dble/services/manager/response/KillClusterRenewThread.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
Reason:  
  Improve inner 1555
Type:  
Influences：  
   fix xx
> [inner-1555] manual kill cluster renew thread

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix  Insert and delete statements error inner 1787

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  BUG inner-1751
Type:  
  BUG
Influences：  
fix specify a queued thread when creating a new connection
> fix specify a queued thread when creating a new connection

- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
Reason:  
  BUG similar: #3256 
Type:  
  BUG
Influences：  
   fix xx
> fix heartbeat timeout inner 1596 (#3256)

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/SSLProtoHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResult.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResultCode.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/net/factory/TrustAllManager.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/net/mysql/AuthPacket.java
- src/main/java/com/actiontech/dble/net/service/SSLProtoServerTask.java
- src/main/java/com/actiontech/dble/net/service/ServiceTaskType.java
- src/main/java/com/actiontech/dble/net/ssl/GMSslWrapper.java
- src/main/java/com/actiontech/dble/net/ssl/OpenSSLWrapper.java
- src/main/java/com/actiontech/dble/net/ssl/SSLWrapperRegistry.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/util/SystemProperty.java
- src/main/resources/bootstrap_template.cnf
Reason:
  Improve inner-1720/1750
Type:
  Improve
Influences：
feat: support SSL and gmssl
> feat: support SSL and gmssl(cherry-pick)

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix  com_field_list unbind the connection inner 1776

- src/main/java/com/actiontech/dble/statistic/stat/FrontActiveRatioStat.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1764] optimal

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix xx
> fix  com_field_list unbind the connection inner 1776 （cherry-pick ）

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> optimize  com_field_list unbind the connection inner 1776

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1646] adjust the prompt

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix timer thread  hang inner 1790

- src/main/java/com/actiontech/dble/services/manager/response/KillClusterRenewThread.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1555] cluster 'online' renew thread is not allowed to be killed

- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/FetchResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
Reason:  
  BUG similar #3257 
Type:  
Influences：  
   fix xx
> [inner-1762] fix：no handler (cherry pick)

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/singleton/TraceManager.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1007] add trace sampler config

- src/main/java/com/actiontech/dble/backend/mysql/VersionUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/SendMakeHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 1335 、1788、1792
Type:  
Influences：  
   fix xx
> [inner-1335&1788&1792] optimizer group by

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinNodeHandlerBuilder.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinStrategyChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinStrategyProcessor.java
- src/main/java/com/actiontech/dble/plan/util/ComplexQueryPlanUtil.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix xx
> fix when joinStrategyType is 2, an sql execution error occurs inner 1736

- src/main/java/com/actiontech/dble/backend/datasource/LocalReadLoadBalancer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBInstance.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/model/db/DbInstanceConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
- src/main/resources/db_detail.xsd
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> local read support inner 1752 (#3263)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/plan/util/ComplexQueryPlanUtil.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> add  nest loop check  inner 1804

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix statement insertion errors inner 1787

- src/main/java/com/actiontech/dble/config/helper/ShowDatabaseHandler.java
- src/main/java/com/actiontech/dble/config/model/user/AnalysisUserConfig.java
- src/main/java/com/actiontech/dble/config/model/user/RwSplitUserConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix analysisUser login with the database name inner 1703

- src/main/java/com/actiontech/dble/backend/mysql/CharsetUtil.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/sharding/schema/ChildTable.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/sharding/schema/Table.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/BaseTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/ChildTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/GlobalTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/ShardingTableConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/ShardingTableFakeConfig.java
- src/main/java/com/actiontech/dble/config/model/sharding/table/SingleTableConfig.java
- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
- src/main/resources/sharding_detail.xsd
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix sql error caused by encoding error inner 1411

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
Reason:  
  BUG inner-1820
Type:  
  BUG
Influences：  
fix: error getting shard type
> fix: error getting shard type

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix xx
> fix query backend_connections for npe   inner 1740

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/helper/KeyVariables.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner-1834
Type:  
  BUG
Influences：  
fix: set lowerCase at startup
> fix: set lowerCase at startup

- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix automated ci encode format conversion inner 1411

- src/test/java/com/actiontech/dble/config/AnalysisUserConfig.java
- src/test/java/com/actiontech/dble/config/ConfigDiff.java
- src/test/java/com/actiontech/dble/config/DataBaseType.java
- src/test/java/com/actiontech/dble/config/DbGroupConfig.java
- src/test/java/com/actiontech/dble/config/DbInstanceConfig.java
- src/test/java/com/actiontech/dble/config/ManagerUserConfig.java
- src/test/java/com/actiontech/dble/config/PhysicalDbGroup.java
- src/test/java/com/actiontech/dble/config/PhysicalDbInstance.java
- src/test/java/com/actiontech/dble/config/PoolConfig.java
- src/test/java/com/actiontech/dble/config/RwSplitUserConfig.java
- src/test/java/com/actiontech/dble/config/ServerUserConfig.java
- src/test/java/com/actiontech/dble/config/ShardingNode.java
- src/test/java/com/actiontech/dble/config/ShardingUserConfig.java
- src/test/java/com/actiontech/dble/config/SingleDbGroupUserConfig.java
- src/test/java/com/actiontech/dble/config/UserConfig.java
- src/test/java/com/actiontech/dble/config/UserName.java
Reason:  
  Improve  #3298
Type:  
  Improve  
Influences：  
test: add unit tests
> test: add unit tests

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/DelayTableHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/TempTableHandler.java
Reason:  
   Improve 
Type:  
     Improve  
Influences：  
   fix xx
> fix  error modification inner 1805

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix query backend_connections for npe inner 1740

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
fix
Reason:  
  Improve
Type:  
  Improve  
Influences：  
   fix xx
> the groupConcatMaxLen parameter is omitted  inner 1738

- src/main/java/com/actiontech/dble/config/DbleTempConfig.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner-1858
Type:  
  BUG 
Influences：  
fix: lowerCase initialization should be empty
> fix: lowerCase initialization should be empty

- src/main/java/com/actiontech/dble/backend/mysql/VersionUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/SendMakeHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 1335&1792     similar #3292 
Type:  
Influences：  
   fix xx
> [inner-1335&1792] optimizer group by（cherry pick）

- src/main/resources/bootstrap_template.cnf
Reason:  
    Improve inner 1660/1798
Type:  
   Improve  
Influences：  
   fix xx
> Boot template

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
Reason:
  BUG inner-1820
Type:
  BUG
Influences：
fix: error getting shard type
> fix: error getting shard type（cherry-pick）

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner-1859:fix slow log npe&fix read buffer NPE (#3307)
Type:  
  BUG
Influences：  
   async-release
> inner-1859:fix slow log npe&fix read buffer NPE (#3307)

- src/main/java/com/actiontech/dble/plan/common/item/function/mathsfunc/ItemFuncRoundOrTruncate.java
Reason:  
  BUG inner 1844
Type:  
Influences：  
   fix xx
> [inner-1844] Fix the round/truncate function problem

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/MysqlVisitor.java
Reason:  
Type:  
Influences：  
   fix xx
> [rollback] remove brackets

- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
Reason:  
  BUG inner-1857:load data NPE
Type:  
  BUG
Influences：  
   load data
> inner-1857:load data NPE

- src/main/java/com/actiontech/dble/backend/mysql/VersionUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/SendMakeHandler.java
- src/main/java/com/actiontech/dble/route/RouteResultset.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 1335&1792 similar #3292 
Type:  
Influences：  
   fix xx
> [inner-1335&1788&1792] optimizer group by (cherry pick)

- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogEntry.java
Reason:  
Type:  
Influences：  
   fix xx
> correct the format of slow log

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/DelayTableHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/TempTableHandler.java
Reason:  
  Improve  
Type:  
  Improve  
Influences：  
   fix xx
> optimized error information inner 1805

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG inner-1847
Type:  
  BUG
Influences：  
fix: newly added instance needs to create a connection pool immediately
> fix: newly added instance needs to create a connection pool immediately

- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1741] fix 'true is not true' exception

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/cluster/logic/HAClusterLogic.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  BUG inner-1871&1874
Type:  
  BUG
Influences：  
fix: config is synced to ha's memory
> fix: config is synced to ha's memory

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeatStatus.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeat.java
Reason:  
  BUG inner-1847
Type:  
  BUG
Influences：  
fix: heartbeat status is STOP_STATUS after ha disable
> fix: heartbeat status is STOP_STATUS after ha disable

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG inner-1881/1871
Type:  
  BUG
Influences：  
perf: reduce the number of test connections
> perf: reduce the number of test connections

- src/main/java/com/actiontech/dble/plan/optimizer/HintPlanInfo.java
- src/main/java/com/actiontech/dble/route/handler/HintPlanHandler.java
- src/main/java/com/actiontech/dble/route/parser/util/DruidUtil.java
- src/test/java/com/actiontech/dble/optimizer/JoinUseHintTest.java
Reason:  
  Improve # inner 1501.  
Type:  
  Improve  
Influences：  
  can use table index in complex query hint
> inner 1501 - can use table index in complex query hint

- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  BUG inner 1872
Type:  
Influences：  
   fix xx
> [inner-1872] fix show trace bug

- src/main/java/com/actiontech/dble/statistic/stat/FrontActiveRatioStat.java
Reason:  
  BUG inner 1873
Type:  
Influences：  
   fix xx
> [inner-1873] scene of the concurrent, FrontActiveRatioStat's error

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
Reason:  
  BUG inner-1886
Type:  
  BUG
Influences：  
fix: sync is required when sharding.xml is empty
> fix: sync is required when sharding.xml is empty

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
  BUG inner-1859:fix read buffer NPE (#3307)
Type:  
  BUG
Influences：  
   fix xx
> inner-1859:fix read buffer NPE (#3307)

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/HeartBeat.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/resources/bootstrap_template.cnf
- src/main/resources/db_detail.xsd
- src/main/resources/db_template.xml
- src/test/java/com/actiontech/dble/config/DbGroupConfig.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> fix  mysql heartbeat fails to recover for a long time due to VIP drift inner 1495

- src/main/java/com/actiontech/dble/plan/common/item/function/mathsfunc/ItemFuncRoundOrTruncate.java
Reason:  
  BUG similar #3330 
Type:  
Influences：  
   fix xx
> [inner-1844] Fix the round/truncate function problem（cherry pick）

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
Reason:  
  BUG inner 1839
Type:  
Influences：  
   fix xx
> [inner-1839] strengthen judgment

- src/main/resources/bootstrap_template.cnf
Reason:  
Type:  
Influences：  
   fix xx
> remove space inner 1888

- src/main/java/com/actiontech/dble/plan/common/item/function/mathsfunc/ItemFuncRoundOrTruncate.java
Reason:  
  BUG similar #3330 
Type:  
Influences：  
   fix xx
> [inner-1844] Fix the round/truncate function problem (cherry pick)

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG inner-1887
Type:  
  BUG
Influences：  
fix: the connection pool must be recycled when deleting dbInstance
> fix: the connection pool must be recycled when deleting dbInstance

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HintNestLoopHelper.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinNodeHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/DelayTableHandler.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
- src/main/java/com/actiontech/dble/server/parser/HintPlanParse.java
Reason:  
  inner 1831 & 1843
Type:  
  BUG
Influences：  
   fix xx
> fix hint parse error inner 1831 

- src/main/java/com/actiontech/dble/route/handler/HintPlanHandler.java
Reason:  
  BUG #inner-1501.  
Type:  
  BUG
Influences：  
  fix NullPointException
> inner-1501: fix NullPointException

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  Improve inner-1859: switch default async release to sync release.
Type:  
  Improve  
Influences：  
   release
> inner-1859: switch default async release to sync release.

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeatStatus.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHeartbeat.java
Reason:  
  BUG inner-1847
Type:  
  BUG 
Influences：  
fix: newly added instance needs to create a connection pool immediately
heartbeat status is STOP_STATUS after ha disable
> fix: newly added instance needs to create a connection pool immediately(cherry-pick)

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/cluster/logic/HAClusterLogic.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:
  BUG inner-1874， similar #3341 
Type:
  BUG
Influences：
fix: config is synced to ha's memory
> fix: config is synced to ha's memory(cherry-pick)

- src/main/java/com/actiontech/dble/manager/response/DryRun.java
Reason:  
  BUG inner-1880
Type:  
  BUG
Influences：  
fix: use thread-safe collections
#2261
> fix: use thread-safe collections(cherry-pick from 2261)

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeatStatus.java
Reason:  
  BUG #3357
Type:  
  BUG
Influences：  
fix: use lowercase for status
> fix: use lowercase for status

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix heartbeat timeout inner 1371 （cherry pick）

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG 
Type:  
Influences：  
   fix xx
> optimize  com_field_list unbind the connection inner 1776 （cherry pick）

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
Reason:  
  BUG #inner 1307. 
Type:  
  BUG
Influences：  
  cherry pick
> inner-1307: fix heartbeat timeout and improve heartbeat log

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG inner 1855
Type:  
Influences：  
   fix xx
> [inner-1855] fix: in 'join on subquery', subquery is executed repeatedly

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
Reason:  
  BUG #inner 1904. 
Type:  
  BUG
Influences：  
  fix direct memory leak
> inner-1904: fix direct memory leak

- src/main/java/com/actiontech/dble/route/handler/HintPlanHandler.java
Reason:  
  BUG 
Type:  
  BUG
   fix xx
> fix hint parse npe inner 1902

- src/main/java/com/actiontech/dble/route/parser/util/DruidUtil.java
- src/main/java/com/actiontech/dble/server/parser/TableAliasVisitor.java
Reason:  
  BUG #inner 1900.
Type:  
  BUG  
Influences：  
  inner-1900: use table alias to replace table index
> inner-1900: use table alias to replace table index

- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/net/response/CustomDataResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/StatisticsResponseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG inner-1896&1897
Type:  
  BUG
Influences：  
   inner-1896&1897 sync release hang when receive error package
> inner-1896&1897 sync release hang when receive error package

- src/main/java/com/actiontech/dble/plan/NamedField.java
- src/main/java/com/actiontech/dble/plan/common/item/ItemField.java
- src/main/java/com/actiontech/dble/plan/node/JoinNode.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
Reason:  
  BUG inner 1812、1811
Type:  
Influences：  
   fix xx
> [inner-1812&1811&1810]  fix : when natural join,  fix 'could not find the column' and 'duplicate column' and adjust columns order

- src/main/java/com/actiontech/dble/config/helper/ShowDatabaseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
Reason:  
  BUG  inner-1892
Type:  
  BUG\
Influences：  
   inner-1892:fix login operation consume thread pool
> inner-1892:fix login operation consume thread pool

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix  heartbeat  is miss inner 1371

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/MysqlVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix sql where condition is miss inner 1829

- src/main/java/com/actiontech/dble/net/response/StatisticsResponseHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/StatisticsHandler.java
Reason:  
  BUG inner 1753;  similar #3312 
Type:  
Influences：  
   fix xx
> [inner-1753] support STATISTICS protocol (cherry pick)

- src/main/java/com/actiontech/dble/plan/common/item/function/sumfunc/ItemFuncGroupConcat.java
Reason:  
  BUG inner 1830
Type:  
Influences：  
   fix xx
> [inner-1830] fix：result of the a group_concat() is incorrect

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OutputHandler.java
Reason:  
  BUG #inner-1904.
Type:  
  BUG
Influences：  
  inner-1904: fix direct memory leak (#3378)
> inner-1904: fix direct memory leak (#3378)

- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  inner-1897
Type:  
  Improve  
Influences：  
   [fix xx](inner-1897:optimize recycle logic)
> inner-1897:optimize recycle logic

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix  heartbeat  is miss inner 1371 （cherry pick）

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/route/handler/HintPlanHandler.java
Reason:  
  BUG #inner 1908 and inner 1891 .  
Type:  
  BUG
Influences：  
   inner-1908: remove hint plan space
> inner-1908 and inner 1891 : remove hint plan space and fix delay judgement

- src/main/java/com/actiontech/dble/net/response/CustomDataResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/StatisticsResponseHandler.java
Reason:  
  BUG inner-1897
Type:  
  BUG
Influences：  
  sync release timeout when receive error package (#3368)
> inner-1897 sync release timeout when receive error package (#3368)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/BaseHandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/JoinNodeHandlerBuilder.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinStrategyChooser.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinStrategyProcessor.java
- src/main/java/com/actiontech/dble/plan/util/ComplexQueryPlanUtil.java
Reason:  
  BUG 
Type:  
Influences：  
   fix xx
> fix when joinStrategyType is 2 inner 1772 & 1804 & 1816 (cherry pick)

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MysqlDatabaseHandler.java
(cherry picked from commit 993df28f9495550558138bf6a4ee59ff2d031deb)
Reason:  
  BUG (inner-1892:fix login operation consume thread pool (#3370))
Type:  
  BUG
Influences：  
   fix xx
> inner-1892:fix login operation consume thread pool (#3370)

- src/main/java/com/actiontech/dble/plan/common/item/function/sumfunc/ItemFuncGroupConcat.java
- src/main/java/com/actiontech/dble/plan/node/PlanNode.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG 1841
Type:  
Influences：  
   fix xx
> [inner-1841] fix: group_concat()'s sort problem

- src/main/java/com/actiontech/dble/net/connection/WriteAbleService.java
- src/main/java/com/actiontech/dble/net/mysql/MySQLPacket.java
- src/main/java/com/actiontech/dble/net/mysql/OkPacket.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/singleton/ConnectionSerializableLock.java
Reason:  
  BUG (inner-1912: prevent multi statement hang.)
Type:  
  BUG
Influences：  
   fix xx
> inner-1912: prevent multi statement hang.

- src/main/java/com/actiontech/dble/net/mysql/ChangeUserPacket.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/FrontEndService.java
- src/main/java/com/actiontech/dble/services/factorys/BusinessServiceFactory.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLChangeUserService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/util/AuthUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:
  BUG inner-1894
Type:
  BUG
Influences：
fix: change user protocol
> fix: change user protocol

- src/main/java/com/actiontech/dble/config/model/sharding/SchemaConfig.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx
> fix performance optimization inner 1917

- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve 
Type:  
      Improve  
Influences：  
   fix xx
> update Xss jvm param inner 1791

- docker-images/dble-image/mgr/bootstrap.cnf
- docker-images/dble-image/quick-start/bootstrap.cnf
- docker-images/dble-image/rwSplit/bootstrap.cnf
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  add PrintGCApplicationStoppedTime jvm param
> add PrintGCApplicationStoppedTime jvm param

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XaCheckHandler.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseReload.java
- src/main/java/com/actiontech/dble/services/manager/handler/ReloadHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/XaidCheck.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner-1614
Type:  
  Improve  
Influences：  
   fix xx
> [inner-1614] add a detection switch for 'xa recover'

- src/main/java/com/actiontech/dble/plan/common/item/function/ItemCreate.java
- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncJsonExtract.java
- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncJsonUnQuote.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
    Improve :inner-1516:json decode function support
Type:  
  Improve  
Influences：  
  json
> inner-1516:json decode function support

- src/main/java/com/actiontech/dble/plan/util/PlanUtil.java
Reason:  
  BUG inner 1833
Type:  
Influences：  
   fix xx
> [inner-1833] support for 'group/order by' columns's refer table size > 1

- src/main/java/com/actiontech/dble/backend/mysql/BindValueUtil.java
- src/main/java/com/actiontech/dble/backend/mysql/MySQLMessage.java
Reason:  
  BUG #3420. 
Type:  
  BUG
Influences：  
  dble parse date parameter error in com_execute packet
> issue 3420: dble parse date parameter error in com_execute packet

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
Reason:  
    Improve #inner 1489.  
Type:  
Influences：  
  inner 1489: readonly transaction can push to slave
> inner 1489: readonly transaction can push to slave

- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncJsonExtract.java
- src/main/java/com/actiontech/dble/plan/common/item/function/strfunc/ItemFuncJsonUnQuote.java
Reason:  
  BUG inner-1937
Type:  
  BUG
Influences：  
  fix json return 0 when unmatched && optimize json unquote
> inner-1937：fix json return 0 when unmatched && optimize json unquote

- docker-images/dble-image/mgr/db.xml
- src/main/resources/db_template.xml
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  turn on testWhileIdle in db_template.xml
> turn on testWhileIdle in db_template.xml

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/DbleStartup.java
- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/general/GeneralLogEntry.java
- src/main/java/com/actiontech/dble/log/general/GeneralLogHandler.java
- src/main/java/com/actiontech/dble/log/sqldump/SqlDumpLogHelper.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseOnOff.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/status/SqlDumpLog.java
- src/main/java/com/actiontech/dble/services/manager/handler/DisableHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/EnableHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/SqlDumpLog.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner 1769
Type:  
  Improve  
Influences：  
   fix xx
> [inner-1769] support sql_dump log

- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/sharding/schema/Schema.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/config/model/sharding/SchemaConfig.java
- src/main/java/com/actiontech/dble/route/parser/druid/DruidParserFactory.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidDropDatabaseParser.java
- src/main/resources/sharding_detail.xsd
Reason:  
  Improve inner-1852
Type:  
  Improve 
Influences：  
feat: supports logical create and drop of virtual schema
> feat: supports logical create and drop of virtual schema

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
Reason:  
     Improve #inner 1489.  
Type:  
  Improve  
Influences：  
  push readonly transaction to slave
> inner 1489 - push readonly transaction to slave in rw

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix loaddata Memory overflow  inner 1936

- src/main/java/com/actiontech/dble/plan/common/item/function/ItemCreate.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/CustomJsonWriter.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/ItemFuncJsonExtract.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/ItemFuncJsonUnQuote.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/JsonScope.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/JsonWriterAdaptor.java
- src/main/java/com/actiontech/dble/plan/visitor/MySQLItemVisitor.java
Reason:  
  BUG inner-1940:
Type:  
  BUG
Influences：  
   [json]add space for special situation
> inner-1940:[json]add space for special situation 

- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetectionSqlJob.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetectionStatus.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetectionTask.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBGroup.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerSchemaInfo.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDelayDetection.java
- src/main/java/com/actiontech/dble/services/manager/response/ChangeItem.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/resources/db_detail.xsd
Reason:  
   Improve 
Type:  
Improve  
Influences：  
   fix xx
> add delay detection inner 1846

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/backend/pool/PoolBase.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
  Improve inner-1867&1933
Type:  
  Improve  
Influences：  
fix:  improve the connection pool to supplement the connection logic
> fix:  improve the connection pool to supplement the connection logic

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/sqldump/SqlDumpLogHelper.java
- src/main/java/com/actiontech/dble/server/status/SqlDumpLog.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1948] adjust sqldump's param

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/ShardingNode.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PSHandler.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
  
> RW for sharding User supports local read inner 1951

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
Reason:  
  BUG #inner 1927. 
Type:  
  BUG
Influences：  
  avoid timeout heartbeat connection remaining
> inner 1927 - avoid timeout heartbeat connection remaining

- src/main/java/com/actiontech/dble/net/ssl/GMSslWrapper.java
Reason:  
  BUG inner-1817
Type:  
  BUG
Influences：  
fix: adjust the loading timing of gmssl
> fix: adjust the loading timing of gmssl

- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/ItemFuncJsonExtract.java
Reason:  
  BUG inner-1937
Type:  
  BUG
Influences：  
  json fix: arr[0] return self
> inner-1937:json fix: arr[0] return self

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleSchema.java
Reason:  
  BUG inner-1852
Type:  
  BUG
Influences：  
fix: dble_schema display fields
> fix: dble_schema display fields

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
Reason:  
  BUG #inner 1927.
Type:  
  BUG
Influences：  
  fix initial status  to quit status
> inner 1927 - fix initial status  to quit status

- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
Reason:  
  BUG inner-1945
Type:  
  BUG
Influences：  
   print error if no handler
> inner-1945: print error if no handler

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/SingleNodeDDLHandler.java
Reason:  
  BUG #inner 1970. 
Type:  
  BUG
Influences：  
  handle multi-statement error when sql contains ddl
> inner 1970 - handle multi-statement error when sql contains ddl

- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
Reason:  
  BUG inner-1423
Type:  
  BUG
Influences：  
fix: alert when xa retry stop
> fix: alert when xa retry stop

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetectionSqlJob.java
- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/sharding/schema/Table.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/meta/DDLProxyMetaManager.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/ItemFuncJsonExtract.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/status/GeneralLog.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix  read instance send create statement  inner 1962

- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseReload.java
- src/main/java/com/actiontech/dble/server/status/SlowQueryLog.java
- src/main/java/com/actiontech/dble/services/manager/handler/ReloadHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadSlowQueuePolicy.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:
  Improve inner-1763
Type:
  Improve
Influences：
pref: strategies to increase slow query blocking
> fix: strategies to increase slow query blocking

- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
- src/main/java/com/actiontech/dble/services/BackendService.java
fix npe when connection concurrency is closed
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix memory leak inner 1860

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XACommitFailStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/stage/XARollbackStage.java
Reason:  
  BUG #inner 1497.
Type:  
  BUG
Influences：  
  avoid concurrency between close and xa prepare
> inner 1497 - avoid concurrency between close and xa prepare

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/net/impl/aio/AIOSocketWR.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleFrontConnections.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowConnection.java
Reason:  
  BUG inner-1972
Type:  
  BUG
Influences：  
   fix gmssl login
> inner-1972:fix gmssl login

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG inner-1898 && inner-1897
Type:  
Influences：  
   release switch
> inner-1898: release switch & inner-1897:prevent sync release hang 

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/net/response/DefaultResponseHandler.java
- src/main/java/com/actiontech/dble/net/response/LoadDataResponseHandler.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> inner-1898: release switch & inner-1897:prevent sync release hang

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix npe  when innerRelease and close are concurrent inner 1883

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLShardingSQLHandler.java
- src/main/java/com/actiontech/dble/singleton/RouteService.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix hint sql hang inner 1981

- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/helper/KeyVariables.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> fix   check back_log inner 1931

- src/main/java/com/actiontech/dble/services/TransactionService.java
Reason:  
  BUG inner 1992
Type:  
Influences：  
   fix xx
> [inner-1992] fix bug

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
Reason:  
  BUG inner-1933
Type:  
  BUG
Influences：  
fix: use the state value before restoration to judge
> fix: use the state value before restoration to judge

- src/main/java/com/actiontech/dble/buffer/BufferPoolRecord.java
- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
- src/main/java/com/actiontech/dble/buffer/MemoryBufferMonitor.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleMemoryResident.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  Improve inner-1492-supplement
Type:  
  Improve  
Influences：  
   inner-1492-supplement: modify buffer-monitor logic
> inner-1492-supplement: modify buffer-monitor logic 

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLShardingSQLHandler.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix  lost connection inner 1996

- src/main/java/com/actiontech/dble/services/rwsplit/CallbackFactory.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitMultiHandler.java
- src/main/java/com/actiontech/dble/statistic/sql/RwSplitStatisticRecord.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
Reason:  
  BUG inner 1993
Type:  
Influences：  
   fix xx
> [inner-1993] in rwsplit, filter 1064 syntax errors

- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  BUG inner-1976/inner-1995
Type:  
  BUG
Influences：  
fix: exposed errors during dryrun
dble_variables display queryForUpdateMaxRowsSize field
> fix: exposed errors during dryrun

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
Reason:  
  BUG inner-1956-supplement: change executor for old version
Type:  
  BUG 
Influences：  
   change executor for old version
> inner-1956-supplement: change executor name for old version

- src/main/java/com/actiontech/dble/net/impl/nio/NIOSocketWR.java
Reason:  
   Improve  
Type:  
  Improve  
Influences：  
   fix xx
> optimize channel log inner 1895

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/subquery/UpdateSubQueryHandler.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/plan/util/ComplexQueryPlanUtil.java
Reason:  
  BUG inner-1995&inner-1997
Type:  
  BUG
Influences：  
fix: explain result is wrong
check the validity of queryForUpdateMaxRowsSize value
> fix: explain result is wrong

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
- src/main/java/com/actiontech/dble/config/model/db/DbGroupConfig.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix detection fail inner 1958 & 1973

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/util/CharsetContext.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx
> fix  performance optimization inner 1922

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
Reason:  
  BUG #inner 2022.
Type:  
  BUG
Influences：  
  promise that add unResponseRrns is atomic
> inner 2022 - promise that add unResponseRrns is atomic

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/KillConnectionHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix Infinite recursion inner 2005

- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx
> fix description of dryrun inner 1915

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner-2025
Type:  
  BUG
Influences：  
fix: type conversion error
> fix: type conversion error

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/UpdateVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/subquery/UpdateSubQueryHandler.java
- src/main/java/com/actiontech/dble/plan/visitor/UpdatePlanNodeVisitor.java
- src/main/java/com/actiontech/dble/statistic/stat/TableStatAnalyzer.java
Reason:  
  BUG inner-1995/inner-2024/inner-2027
Type:  
  BUG
Influences：  
fix: join on converts to where syntax
explain removes extra spaces
> fix: join on converts to where syntax

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/util/SystemProperty.java
Reason:  
  BUG #3450 、inner 2021
Type:  
Influences：  
   fix xx
> [inner-2021] support the JDK parameters

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 2026
Type:  
Influences：  
   fix xx
> [inner-2026] fix bug with table aliases

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:
  BUG inner-2025
Type:
  BUG
Influences：
fix: type conversion error
#3501
> fix: type conversion error(cherry-pick)

- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/ItemFuncJsonExtract.java
- src/main/java/com/actiontech/dble/plan/common/item/function/jsonfunc/ItemFuncJsonUnQuote.java
Reason:  
  BUG  inner-2020
Type:  
  BUG
Influences：  
  prevent repeat json function call.
> inner-2020: prevent repeat json function call.

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/GlobalVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/PushDownVisitor.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/sqlvisitor/UpdateVisitor.java
- src/main/java/com/actiontech/dble/plan/visitor/UpdatePlanNodeVisitor.java
Reason:  
  BUG inner-2031/inner-2024
Type:  
  BUG
Influences：  
fix: group by to remove duplicate fields
Subquery fields are not allowed to be updated
> fix: group by to remove duplicate fields

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MysqlBackendLogicHandler.java
Reason:  
  BUG [cherry-pick]inner-1956:fix MultiNodeSelectHandler hang &inner-1945: print error if no handler 
Type:  
  BUG
Influences：  
   fix xx
> [cherry-pick]inner-1956:fix MultiNodeSelectHandler hang &inner-1945: print error if no handler 

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/DefaultMultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/UnLockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/handler/NormalTransactionHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
Reason:  
  BUG #inner 1959.
Type:  
  BUG
Influences：
> inner 1959 - avoid the case that connectionClose thread is updating flag but other thread had finished

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG inner-2027
Type:  
  BUG
Influences：  
fix:try splitting and sending when transparent transmission is not supported
> fix:try splitting and sending when transparent transmission is not supported

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleMemoryResident.java
Reason:  
  Improve  inner-1492-supplement
Type:  
  Improve  
Influences：  
  add allocate time field for dble_memory_resident
> inner-1492-supplement: add allocate time field for dble_memory_resident

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
> optimize message inner 1931

- .github/workflows/codeql.yml
Reason:  
  Improve 
Type:  
  Improve 
Influences：  
fix: remove python check
> fix: remove python check

- .github/workflows/codeql.yml
- README.md
Reason:  
  Improve 
Type:  
  Improve 
Influences：  
fix: codeQL trigger mechanism adds update code and draft to review
remove lgtm
> fix: codeQL trigger mechanism adds update code and draft to review

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/DefaultMultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/handler/AbstractXAHandler.java
Reason:  
  BUG #inner 2040. 
Type:  
  BUG
Influences：  
  fix remaining bug
> inner 2040 - fix refactor code bug

- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
Reason:  
  BUG inner 2042
Type:  
Influences：  
   fix xx
> [inner-2042] adjust statistic_queue_monitor

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOReactor.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
   fix xx
> fix   lost connection inner 2037

- src/main/java/com/actiontech/dble/server/variables/MysqlVarsListener.java
- src/main/java/com/actiontech/dble/server/variables/VarsExtractorHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  BUG inner-2003
Type:  
  BUG
Influences：  
fix: select another dbInstance to try again when the dbInstance is unavailable
> fix: select another dbInstance to try again when the dbInstance is unavailable

- src/main/java/com/actiontech/dble/buffer/DirectByteBufferPool.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
Reason:  
  Improve inner-1492
Type:  
  Improve  
Influences：  
  remove tmp config
> inner-1492:remove tmp config

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
   fix xx
> update parameter Information inner 1898

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/cluster/logic/ConfigClusterLogic.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/util/DbXmlWriteJob.java
- src/main/java/com/actiontech/dble/meta/ReloadException.java
- src/main/java/com/actiontech/dble/meta/ReloadLogHelper.java
- src/main/java/com/actiontech/dble/meta/table/AbstractSchemaMetaHandler.java
- src/main/java/com/actiontech/dble/meta/table/ServerMetaHandler.java
- src/main/java/com/actiontech/dble/server/variables/VarsExtractorHandler.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/ManagerService.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadMetaData.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaDisable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaEnable.java
- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  BUG inner  1929
Type:  
Influences：  
   fix xx
> [inner-1929] adjust reload log

- .github/workflows/codeql.yml
Reason:  
  BUG 
Type:  
  BUG
Influences：  
fix: Set the jdk version of codeQL
> fix: Set the jdk version of codeQL

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix load data lost connection inner 2039

- src/main/java/com/actiontech/dble/server/response/SelectVariables.java
Reason:  
  BUG  inner-2004x
Type:  
  BUG
Influences：  
    fix for max_allowed_packet in multi select
> inner-2004: fix for max_allowed_packet in multi select

- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetectionTask.java
Reason:  
  Improve 
Type:  
  improve  
Influences：  
   fix xx
> fix  parameter display error inner 1846

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:  
  BUG inner-2004
Type:  
  BUG
Influences：  
fix: front-end determines that the packet size cannot exceed the set value
> fix: front-end determines that the packet size cannot exceed the set value

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:
  BUG inner-2004
Type:
  BUG
Influences：
fix: front-end determines that the packet size cannot exceed the set value
> fix: front-end determines that the packet size cannot exceed the set value(cherry-pick)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
Reason:  
  fix timer thread hang inner 1790 (#3287).  
Type:  
  BUG
Influences：  
  fix timer thread hang inner 1790 (#3287)
> fix timer thread hang inner 1790 (#3287)

- .github/workflows/codeql.yml
Reason:  
Type:  
Influences：  
fix: delete previous note alerts
> fix: delete previous note alerts

- .github/workflows/codeql.yml
Reason:  
Type:  
Influences：  
fix: codeQL
> fix: codeQL

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  BUG inner-1956-bugfix: fix for back-rw block
Type:  
  BUG 
Influences：  
   fix xx
> inner-1956-bugfix: fix for back-rw block

- src/main/java/com/actiontech/dble/services/FrontendService.java
Reason:
  BUG inner-2004
Type:
  BUG
Influences：
fix: front-end determines that the packet size cannot exceed the set value
> fix: ci wrong judgment

- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/main/java/com/actiontech/dble/statistic/stat/FrontActiveRatioStat.java
Reason:  
  BUG inner 2017
Type:  
Influences：  
   fix xx
> [inner-2017] adjust FrontActiveRatioStat's logic

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDDLExecuteHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeDdlPrepareHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResult.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResultCode.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
- src/main/java/com/actiontech/dble/net/mysql/MySQLPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/ServiceTask.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/handler/LoadDataProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/util/CompressUtil.java
Reason:  
  BUG big packet support
Type:  
  BUG
Influences：  
   inner-2050
> inner-2050: big packet support

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/meta/table/ServerMetaHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/singleton/HaConfigManager.java
Reason:  
  BUG 2049
Type:  
Influences：  
   fix xx
> [inner-2049] adjust log

- src/main/java/com/actiontech/dble/statistic/stat/FrontActiveRatioStat.java
Reason:  
  BUG inner 2055
Type:  
Influences：  
   fix xx
> [inner-2055] fix npe

- src/main/java/com/actiontech/dble/log/sqldump/SqlDumpLogHelper.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/LoadDataProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner 1983
Type:  
Influences：  
   fix xx
> [inner-1983] fix: in rwSplit, load data failure

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
Reason:  
  BUG #inner 1959. 
Type:  
  BUG
Influences：  
  fix bug about lock table
> inner 1959 - fix bug about lock table

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  BUG inner-1945-supplement
Type:  
  BUG
Influences：  
    report error packet when connection closed
> inner-1945-supplement: report error packet when connection closed

- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/util/SystemProperty.java
Reason:  
  BUG similar #3496 
Type:  
Influences：  
   fix xx
> [issue-3450] support the JDK parameters (cherry pick)

- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
Reason:  
   Improve 
Type:  
  improve  
Influences：  
   fix xx
> fix  modify the display default value inner 1846

- src/main/java/com/actiontech/dble/config/model/sharding/SchemaConfig.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertReplaceParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLProtoLogicHandler.java
- src/main/java/com/actiontech/dble/util/CharsetContext.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG 
Type:  
  BUG
   fix xx
> fix  performance optimization inner 1922 (#3489)

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG similar #3506 
Type:  
Influences：  
   fix xx
> [inner-2026&2030] fix bug with table aliases or schema name (cherry pick)

- src/main/java/com/actiontech/dble/route/parser/ManagerParseConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:
  BUG  inner-2046 inner-902/906  inner-603/605/606
Type:
  BUG
Influences：
fix: hint statement use executeSql
fix: wrong judgment when parsing reload
> fix: hint statement use executeSql（cherry-pick）

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  BUG inner-2062
Type:  
  BUG
Influences：  
  fix ci npe
> inner-2062: fix ci npe

- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
inner 1846
Reason:  
  BUG 
Type:  
  BUG
Influences：  
 
> fix Initialization status shows error

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner 2026
Type:  
  BUG
Influences：  
   fix xx
> [inner-2026] fix bug: not found group by `column`

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix npe when handler is null  inner 1859

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnectionHandler.java
Reason:  
  Improve inner-1945-supplement
Type:  
  Improve
Influences：  
  report error packet when connection closed
> inner-1945-supplement: report error packet when connection closed 

- src/main/resources/bootstrap_template.cnf
Reason:  
   Improve
Type:  
  Improve  
Influences：  
   fix xx
> fix parameter default value inner 2069

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPool.java
Reason:  
  BUG inner-2072
Type:  
  BUG
Influences：  
fix: runnableMap does not store complexQueryWorker threads
> fix: runnableMap does not store complexQueryWorker threads

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPool.java
Reason:
  BUG inner-2072
Type:
  BUG
Influences：
fix: runnableMap does not store complexQueryWorker threads
#3582
> fix: runnableMap does not store complexQueryWorker threads(cherry-pick)

- src/main/java/com/actiontech/dble/services/mysqlsharding/LoadDataProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner 1983, similar #3560 
Type:  
Influences：  
   fix xx
> [inner-1983] fix: in rwSplit, load data failure (cherry pick)

- src/main/java/com/actiontech/dble/log/sqldump/SqlDumpLogHelper.java
Reason:  
  BUG inner 2038
Type:  
Influences：  
   fix xx
> [inner-2083] fix SqlDumpLog's npe

- docker-images/dble-image/mgr/user.xml
- docker-images/dble-image/quick-start/user.xml
- src/main/resources/user_template.xml
Reason:  
   Improve #3590 .  
Type:  
  Improve  
Influences：  
  move root user blacklist to another user
> move root user blacklist to another user

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
https://github.com/actiontech/dble/pull/3470
Reason:  
  BUG
Type:  
  BUG 
Influences：  
  inner 1879
> fix npe when the frontend connection is closed, the statement is still send

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  BUG inner-2092
Type:  
Influences：  
   fix xx
> [inner-2092]: rwSplit's big package problem

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  BUG inner 2096 ,similar #3605 
Type:  
Influences：  
   fix xx
> [inner-2096] fix: the problem of hung in the 16M's big package

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/service/AbstractService.java
Reason:  
  BUG inner 2092, similar #3604 
Type:  
Influences：  
   fix xx
> [inner-2092] fix: rwSplit's big package problem

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  Issue 890 Refactoring DruidSelectParser (#1349) 、[#3543](https://github.com/actiontech/dble/pull/3543)
Type:  
  BUG
Influences：  
   fix group by xxx can not run with mysql8.0  when using global table
> Issue 890 Refactoring DruidSelectParser (actiontech#1349)

- src/main/java/com/actiontech/dble/cluster/ClusterController.java
- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/resources/cluster_template.cnf
- src/test/java/com/actiontech/dble/cache/DefaultLayedCachePoolTest.java
- src/test/resources/cluster.cnf
Reason:  
  BUG inner-2089
Type:  
  BUG
Influences：  
fix: grpc timeout configuration
> fix: grpc timeout configuration

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG 1855, similar [3358](https://github.com/actiontech/dble/pull/3358/files)
Type:  
Influences：  
   fix xx
> [inner-1855] fix: in 'join on subquery', subquery is executed repeatedly (cherry pick)

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
- src/main/java/com/actiontech/dble/net/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/NIOReactor.java
Conflicts:
src/main/java/com/actiontech/dble/backend/mysql/nio/handler/NewConnectionRespHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
  
> fix timer thread  hang inner 1790 & 2037 (#3287)

- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
Reason:  
  BUG inner-1998 
Type:  
Influences：  
   fix xx
> [inner-1998] remove redundant logs

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
  BUG inner-1716&inner-1955&inner-2091
Type:  
  BUG
Influences：  
fix: close the connection that is being created and the creation time exceeds the connectionTimeout value
> fix: close the connection that is being created and the creation time exceeds the connectionTimeout value

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/KillConnectionHandler.java
Reason:  
 revious commit https://github.com/actiontech/dble/commit/9f975b57f38bc6fc6b15aedbbb97402e2063efcb
Type:  
Influences：  
   fix xx
> Rollback the previously merged issue inner 2005

- pom.xml
Reason:  
Type:  
Influences：  
   fix xx
> upgrade log4j2 to 2.18.0 and fastjson to 1.2.83

- pom.xml
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:
  BUG inner-1716&inner-1955&inner-2091
Type:
  BUG
Influences：
fix: close the connection that is being created and the creation time exceeds the connectionTimeout value
> fix: close the connection that is being created and the creation time exceeds the connectionTimeout value (cherry-pick)

- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
Reason:  
  BUG inner 2119
Type:  
Influences：  
   fix xx
> [inner-2119] fix：DirectByteBuffer.array() brought the UnsupportedOperationException

- src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
Reason:  
Type:  
Influences：  
   fix xx
> fix ArrayIndexOutOfBoundException using big packet (cherry pick from #2659)

- src/main/java/com/actiontech/dble/net/mysql/BinaryRowDataPacket.java
- src/main/java/com/actiontech/dble/net/mysql/RowDataPacket.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2119] fix：DirectByteBuffer.array() brought the UnsupportedOperationException (cherry pick from #3621)

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
  Improve inner-2114: modify error msg from no handle to drop
Type:  
  Improve
Influences：  
   log
> inner-2114: modify error msg from no handle to drop

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAHandler.java
Reason:  
  BUG inner-2140
Type:  
  BUG
Influences：  
  fix the multi-thread bug for xa
> inner-2140: fix the multi-thread bug for xa

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/xa/XAHandler.java
Reason:  
  BUG inner-2142
Type:  
  BUG
Influences：  
   :fix npe for inner-2140
> inner-2142:fix npe for inner-2140

- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/MySQLProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/Impl/SSLProtoHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/proto/handler/ProtoHandlerResult.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/FrontendConnection.java
- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLFrontAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/LoadDataProtoHandlerImpl.java
- src/main/java/com/actiontech/dble/util/exception/NotSslRecordException.java
Reason:  
  BUG inner-2029
Type:  
  BUG
Influences：  
+ fix: adjust the identification process of the ssl protocol package 
+ solve the memory leak problem
> fix: adjust the identification process of the ssl protocol package

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner-2149
Type:  
  BUG
Influences：  
fix: when checking the back_log, dbInstance does not correspond to KeyVariables
> fix: when checking the back_log, dbInstance does not correspond to KeyVariables

- src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
Reason:  
  BUG inner 2144
Type:  
Influences：  
   fix xx
> [inner-2144] fix：sql_log's view with conditional query error

- src/main/java/com/actiontech/dble/backend/heartbeat/HeartbeatSQLJob.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/sharding/schema/Table.java
- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/meta/DDLProxyMetaManager.java
- src/main/java/com/actiontech/dble/plan/optimizer/JoinChooser.java
- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/server/status/GeneralLog.java
- src/main/java/com/actiontech/dble/services/BackendService.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/singleton/PauseShardingNodeManager.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  Improve 
Type:  
    Improve  
Influences：  
   fix xx
> fix  comma format inner 2159

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/LockTablesHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
Reason:  
  BUG inner 2157
Type:  
Influences：  
   fix lost connection bug from ddl
> [inner-2157] fix lost connection bug from ddl

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
Reason:  
  BUG inner-2163
Type:  
  BUG
Influences：  
fix: heartbeat connection lacks the assignment of connectionTimeout
> fix: heartbeat connection lacks the assignment of connectionTimeout

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
Reason:  
  Improve  inner-2158
Type:  
  Improve
Influences：  
   add connection create log info
> inner-2158:add connection create log info

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidInsertParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidReplaceParser.java
- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/FetchMySQLSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceTimeHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceZKHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/SequenceHandler.java
- src/main/java/com/actiontech/dble/route/util/PropertiesUtil.java
- src/main/java/com/actiontech/dble/server/handler/ServerLoadDataInfileHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/handler/ShardingValuesHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/singleton/SequenceManager.java
Reason:  
  BUG inner 1576、2161
Type:  
Influences：  
   fix xx
> [inner-1576&2161] adjust the trigger global sequence's load

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/server/parser/AbstractServerParse.java
- src/main/java/com/actiontech/dble/server/parser/RwSplitServerParse.java
- src/main/java/com/actiontech/dble/server/parser/ServerParseValidations.java
- src/main/java/com/actiontech/dble/server/parser/ShardingServerParse.java
Reason:
  Improving code readability by dividing the class and reducing duplicates by reusing methods.
Type:
  Architecture Improvement
Influences：
   - Created new class 'ServerParseValidations' which contains methods to handle parsing validations for 'RwSplitServerParse' and 'ShardingServerParse'. This reduced duplicate code and made the classes easier to understand.
- Moved many common parsing methods in 'RwSplitServerParse' and 'ShardingServerParse' to the base class 'AbstractServerParse' to remove duplicate code.
> refactored ServerParse classes

- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
Reason:  
  BUG inner-2089&inner-2051
Type:  
  BUG
Influences：  
fix: variable display and default settings
> fix: variable display and default settings

- src/main/java/com/actiontech/dble/meta/ViewMetaParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidAlterViewParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/ddl/DruidCreateOrReplaceViewParser.java
Reason:  
  BUG inner-2176
Type:  
  BUG
Influences：  
fix: view name parse issue and npe when no database selected
> fix: view name parse issue and npe when no database selected

- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner 2181
Type:  
Influences：  
   fix xx
> [inner-2181] adjust setRequestTime

- src/main/java/com/actiontech/dble/services/manager/response/StatisticCf.java
- src/main/java/com/actiontech/dble/statistic/sql/StatisticManager.java
Reason:  
  BUG inner 2180
Type:  
Influences：  
   fix xx
> [inner-2180] adjusted for thread-safe collections

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/IOProcessor.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:  
  BUG inner-2173
Type:  
  BUG
Influences：  
fix: close the connection that is being created and the creation time exceeds the connectionTimeout value
> fix: close the connection that is being created and the creation time exceeds the connectionTimeout value(cherry-pick)

- src/main/java/com/actiontech/dble/meta/ViewMeta.java
- src/main/java/com/actiontech/dble/server/util/SchemaUtil.java
Reason:  
  BUG similar [2287 ](https://github.com/actiontech/dble/pull/2287) 、[2282 ](https://github.com/actiontech/dble/pull/2282)、[2124](https://github.com/actiontech/dble/pull/2124)
Type:  
Influences：  
   fix xx
> cherry pick from inner685/627、issue 2063

- src/main/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnit.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/sqlengine/mpp/ColumnRoute.java
- src/test/java/com/actiontech/dble/route/parser/druid/RouteCalculateUnitTest.java
Reason:
  BUG #1997 
Type:
  BUG
Influences：
   #1997
> #1997 select/delete/update with '0x' (cherry-pick)

- src/main/java/com/actiontech/dble/manager/response/ShowConnectionPoolProperty.java
- src/main/java/com/actiontech/dble/manager/response/ShowConnectionSQLStatus.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fixed 'show @@connection.sql.status & show @@connection_pool' in python report ValueError inner 2188 

- src/main/java/com/actiontech/dble/manager/response/ShowConnectionPoolProperty.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fixed 'show @@connection_pool' in python report ValueError  inner 2188

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/backend/pool/PoolBase.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:
  Improve inner-1867&1933
Type:
  Improve
Influences：
fix: improve the connection pool to supplement the connection logic
> fix: improve the connection pool to supplement the connection logic(cherry-pick)

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/DbleSocketOptions.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/util/CompareUtil.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx
> add tcp level parameters to control connections inner 1716

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/backend/pool/PoolBase.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
Reason:
  Improve inner-1867
Type:
  Improve
Influences：
fix: improve the connection pool to supplement the connection logic
> fix: improve the connection pool to supplement the connection logic(cherry-pick) 

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
- src/main/java/com/actiontech/dble/net/NIOProcessor.java
Reason:
  BUG inner-2173
Type:
  BUG
Influences：
fix: close the connection that is being created and the creation time exceeds the connectionTimeout value
#3654
> fix: close the connection that is being created and the creation time exceeds the connectionTimeout value(cherry-pick) 

- .travis.yml
- pom.xml
Reason:  
Type:  
Influences：  
   fix xx
> adjust travis and quartz version

- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/singleton/SequenceManager.java
Reason:  
  BUG inner-2193
Type:  
Influences：  
   fix xx
> [inner-2193] when sequenceHandlerType=1, dryrun should detect the presence of nodeNode in the sequence_db_conf.properties

- src/main/java/com/actiontech/dble/route/parser/druid/ServerSchemaStatVisitor.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG inner-2196
Type:  
  BUG
Influences：  
  UPDATE SQL support sharding join global
> inner-2196: UPDATE SQL support sharding join global

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
Reason:  
  BUG inner-1867/inner-1740
Type:  
  BUG
Influences：  
fix: the timing of obtaining the number of waiting threads in the connection pool is wrong
> fix: the timing of obtaining the number of waiting threads in the connection pool is wrong

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  inner-2202&2201&2204
Type:  
  BUG
Influences：  
   :fix bug for multi table update
> inner-2202&2201&2204:fix bug for multi table update

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG fix bug for multi table update
Type:  
  BUG
Influences：  
  
> inner-2196-bugfix:fix bug for multi table update

- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceZKHandler.java
- src/main/java/com/actiontech/dble/singleton/SequenceManager.java
…
Reason:  
  BUG inner 2205
Type:  
Influences：  
   fix xx
> [inner-2205] should update the latest sequence_conf.properties when sequenceHandlerType=4 and executing 'reload @@config'

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/manager/ManagerBaseSelectHandler.java
Reason:  
  BUG inner 2208
Type:  
Influences：  
   fix xx
> [inner-2208] display column aliases correctly

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
Reason:  
  BUG inner-2196&2207
Type:  
Influences：  
  [ fix xx](inner-2196-bugfix2:fix for delete SQL)
> inner-2196-bugfix2:fix for delete SQL

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/btrace/provider/ConnectionPoolProvider.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleBackendConnections.java
Reason:  
  BUG inner-1740
Type:  
  BUG
Influences：  
fix: service is set to null and connection close is not atomic
> fix: service is set to null and connection close is not atomic

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidDeleteParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidModifyParser.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidUpdateParser.java
Reason:  
  BUG Inner 2196
Type:  
  BUG
Influences：  
   bugfix for multi table update
> Inner 2196 bugfix for multi table update

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
- src/main/java/com/actiontech/dble/route/handler/HintDbInstanceHandler.java
Reason:  
  BUG inner 2213
Type:  
Influences：  
   fix xx
> [inner-2213] adjust the basis of whether the 'readInstance' judgment

- pom.xml
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/RwSplitSelectVariablesHandler.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/RwSplitSelectHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix jdbc compatible pre-delivery statements error inner 2212

- src/main/java/com/actiontech/dble/backend/pool/ConnectionPool.java
- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
- src/main/java/com/actiontech/dble/net/connection/PooledConnection.java
- src/main/java/com/actiontech/dble/route/handler/HintDbInstanceHandler.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2213] adjust the basis of whether the 'readInstance' judgment (cherry pick from #3681)

- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLDetector.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner-2221/inner-2226
Type:  
  BUG
Influences：  
fix: add rwSplitUser also needs to check the version 
adjust heartbeat error message
> fix: add rwSplitUser also needs to check the version

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
fix: add type judgment
> fix: add type judgment

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG inner-2153
Type:  
  BUG
Influences：  
  fix bug for  "response tabular repose error" packet
> inner-2153:fix bug for  "response tabular repose error" packet

- src/main/java/com/actiontech/dble/services/manager/response/ShowConnectionPoolProperty.java
cherry pick from  https://github.com/actiontech/dble/pull/3659 & https://github.com/actiontech/dble/pull/3660
Reason:  
Type:  
Influences：  
   fix xx
> fixed 'show @@connection.sql.status & show @@connection_pool' in python report ValueError inner 2188

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/CommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/RollbackStage.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2222] clear the 'sendData' resource in the transaction correctly

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/TransactionHandlerManager.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/CommitStage.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/transaction/normal/stage/RollbackStage.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2222] clear the 'sendData' resource in the transaction correctly (cherry pick from #3702)

- src/main/java/com/actiontech/dble/net/IOProcessor.java
Reason:  
  BUG inner-2216
Type:  
  BUG
Influences：  
  fix NPE in backendCheck
> inner-2216:fix NPE in backendCheck

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
Reason:  
  BUG inner-2153-bugfix
Type:  
  BUG
Influences：  
  fix bug for  "response tabular repose error" packet
> inner-2153-bugfix:fix bug for  "response tabular repose error" packet

- src/main/java/com/actiontech/dble/net/connection/SSLHandler.java
Reason:  
  BUG inner-2235
Type:  
  BUG
Influences：  
fix: ssl not wrap all the information in the buffer
> fix: ssl not wrap all the content in the buffer

- src/main/java/com/actiontech/dble/backend/mysql/nio/MySQLConnection.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2213] adjust code

- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
Reason:  
  BUG inner-2048
Type:  
  BUG
Influences：  
fix: rw-split user are not limited by maxPacketSize of dble
> fix: rw-split user are not limited by maxPacketSize of dble

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2215] in execute protocol, prepare sql need to be recorded in sql_log

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PreparedStatementHolder.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2215] in execute protocol, prepare sql need to be recorded in sql_log(cherry pick)

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
- src/main/java/com/actiontech/dble/services/rwsplit/handle/PreparedStatementHolder.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2215] in execute protocol, prepare sql need to be recorded in sql_log (cherry pick)

- src/main/java/com/actiontech/dble/statistic/stat/UserSqlHighStat.java
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
> fix high cpu usage inner 2240

- src/main/java/com/actiontech/dble/config/model/ClusterConfig.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceZKHandler.java
- src/main/java/com/actiontech/dble/singleton/SequenceManager.java
Reason:  
  BUG similar #3675 
Type:  
Influences：  
   fix xx
> [inner-2205] should update the latest sequence_conf.properties when sequenceHandlerType=4 and executing 'reload @@config' (cherry pick from #3685)

- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
Reason:  
   Improve
Type:  
  Improve  
Influences：  
   fix xx
> fix use backend connection  information

- src/main/java/com/actiontech/dble/btrace/provider/GeneralProvider.java
- src/main/java/com/actiontech/dble/log/DailyRotateLogStore.java
- src/main/java/com/actiontech/dble/log/slow/SlowQueryLogProcessor.java
- src/main/java/com/actiontech/dble/manager/response/ReloadSlowQueryFlushPeriod.java
- src/main/java/com/actiontech/dble/server/NonBlockingSession.java
- src/main/java/com/actiontech/dble/server/status/SlowQueryLog.java
Reason:
  BUG inner-2230
Type:
  BUG
Influences：
after abnormal disk flush, fileChannel will not close
#3704
> fix: after abnormal disk flush, fileChannel will not close(cherry-pick) 

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/loader/SystemConfigLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/net/DbleSocketOptions.java
- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix parameter check inner 2239

- src/main/java/com/actiontech/dble/statistic/trace/RwTraceResult.java
- src/main/java/com/actiontech/dble/statistic/trace/SelectTraceResult.java
- src/main/java/com/actiontech/dble/statistic/trace/TraceResult.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2245] adjust record ComplexHandler's logic

- src/main/java/com/actiontech/dble/statistic/trace/RwTraceResult.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2249] filter scenarios where sql is empty

- src/main/resources/bootstrap_template.cnf
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix parameter name inner 2239

- src/main/resources/bootstrap_template.cnf
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2253] internal parameters are not displayed

- .github/auto_assign.yml
- .github/workflows/Auto_Review.yml
- .github/workflows/codeql.yml
- src/main/java/com/actiontech/dble/cluster/response/DataHostHaResponse.java
- src/main/java/com/actiontech/dble/cluster/response/XmlSchemaLoader.java
- src/main/java/com/actiontech/dble/cluster/xmltoKv/XmltoCluster.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/XmltoZkMain.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/xmltozk/listen/DataHostStatusTozkLoader.java
- src/main/java/com/actiontech/dble/config/loader/zkprocess/zktoxml/listen/SchemaszkToxmlLoader.java
- src/main/java/com/actiontech/dble/manager/response/DataHostDisable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostEnable.java
- src/main/java/com/actiontech/dble/manager/response/DataHostSwitch.java
fix: cherry-pick
DMP-5667 (#2181) 
no cluster ha with reload (#2182)
> fix: DMP-5667 and no cluster ha with reload

- src/main/java/com/actiontech/dble/services/BackendService.java
Reason:  
Type:  
Influences：  
   fix xx
> fix npe  inner 2232

- src/main/java/com/actiontech/dble/btrace/provider/SlowLogProvider.java
- src/main/java/com/actiontech/dble/server/trace/TraceResult.java
Reason:  
  Improve.  
Type:  
  Improve  
Influences：  
  btrace - add slowlog entry
> btrace - add slowlog entry

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceMySQLHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceTimeHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/IncrSequenceZKHandler.java
- src/main/java/com/actiontech/dble/route/sequence/handler/SequenceHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/DryRun.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/singleton/SequenceManager.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2161] sequence configuration should not be instantiated when dryrun (cherry pick from #3685)

- src/main/java/com/actiontech/dble/statistic/sql/analyzer/QueryConditionAnalyzer.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2260] fix: rwSplit + PS protocol + '-DenableStatisticAnalysis=1', happen NPE

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeHandler.java
- src/main/java/com/actiontech/dble/statistic/trace/AbstractTrackProbe.java
- src/main/java/com/actiontech/dble/statistic/trace/SelectTraceResult.java
- src/main/java/com/actiontech/dble/statistic/trace/TraceResult.java
- src/main/java/com/actiontech/dble/statistic/trace/TrackProbe.java
Reason:  
  BUG inner-2259
Type:  
Influences：  
   fix xx
> [inner-2259] fix: large and small table join scenario, 'show trace' result is empty

- src/main/java/com/actiontech/dble/cluster/ClusterHelper.java
- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
  BUG inner-2256
Type:  
  BUG
Influences：  
fix: narrow down the scope of syncing dbGroup state
> fix: narrow down the scope of syncing dbGroup state

- pom.xml
- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
Reason:  
Type:  
Influences：  
   fix xx
> upgrade grpc from 1.5.0 to 1.53.0

- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
Reason:  
  BUG inner-2283
Type:  
  BUG
Influences：  
fix: rows that do not need to be changed are not correctly removed during update or delete
> fix: rows that do not need to be changed are not correctly removed during update or delete

- pom.xml
- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
Reason:  
  simliar #3760 
Type:  
Influences：  
   fix xx
> [inner-2282] upgrade grpc from 1.5.0 to 1.53.0

- src/main/resources/sharding_template.xml
- src/main/resources/user_template.xml
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2276] add apNode to the configure template

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner-2283
Type:  
  BUG
Influences：  
fix: add null value judgment
> fix: add null value judgment

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
Reason:  
  BUG inner-2283
Type:  
  BUG
Influences：  
fix[inner-2283]: heartbeat_keep_alive add null value judgment
> fix[inner-2283]: heartbeat_keep_alive add null value judgment

- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/Property.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBGroup.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBInstance.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/HeartBeat.java
- src/main/java/com/actiontech/dble/config/model/user/UserConfig.java
- src/main/java/com/actiontech/dble/services/manager/handler/DeleteHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/InsertHandler.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/main/java/com/actiontech/dble/services/manager/information/ManagerWritableTable.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleEntry.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleRwSplitEntry.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowUser.java
- src/main/java/com/actiontech/dble/util/IntegerUtil.java
- src/main/java/com/actiontech/dble/util/LongUtil.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
Reason:  
  BUG inner-2290
Type:  
  BUG
Influences：  
merge dble_information related pr
> fix[inner-2290]:merge dble_information related pr

- src/main/resources/user_template.xml
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2276] adjust conf_template

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
cherry pick from https://github.com/actiontech/dble/pull/2144
Reason:  
Type:  
Influences：  
   fix xx
> fix npe  inner 2073

- src/main/java/com/actiontech/dble/config/util/ParameterMapping.java
- src/main/java/com/actiontech/dble/util/BooleanUtil.java
Reason:  
  Improve 
Type:  
      Improve  
Influences：  
   fix xx
> support 0/1/false/true compatibility with or without enabled inner 2117

- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2298] fix npe

- src/main/java/com/actiontech/dble/plan/util/FilterUtils.java
Reason:  
  BUG 
Type:  
Influences：  
   fix xx
> fix sql execution result error inner 590

- src/main/resources/sharding_template.xml
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2276] remove duplicate tables

- src/main/java/com/actiontech/dble/services/manager/information/ManagerTableUtil.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbGroup.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner-2283
Type:  
  BUG
Influences：  
fix: rows that do not need to be changed are not correctly removed during update or delete
> fix: rows that do not need to be changed are not correctly removed during update or delete(cherry-pick)

- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/test/java/com/actiontech/dble/parser/druid/DruidSelectParserTest.java
Reason:  
  BUG inner-2307
Type:  
  BUG
Influences：  
fix: determine whether an aggregate function is included in where
> fix: determine whether an aggregate function is included in where

- src/main/java/com/actiontech/dble/cluster/general/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/general/impl/ushard/UshardSender.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterClearKeyListener.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterOffLineListener.java
- src/main/java/com/actiontech/dble/cluster/general/listener/ClusterSingleKeyListener.java
- src/main/java/com/actiontech/dble/cluster/logic/PauseResumeClusterLogic.java
- src/main/java/com/actiontech/dble/log/transaction/TxnLogProcessor.java
- src/main/java/com/actiontech/dble/meta/PauseEndThreadPool.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOAcceptor.java
- src/main/java/com/actiontech/dble/net/impl/nio/NIOConnector.java
Reason:  
  BUG inner 2123
Type:  
Influences：  
   fix xx
> [inner-2123] prevent threads from exiting unexpectedly

- src/main/java/com/actiontech/dble/config/ServerConfig.java
Reason:  
  BUG inner-2310
Type:  
Influences：  
   fix xx
> [inner-2310] fix npe

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner 2309/ #3775 
Type:  
Influences：  
   fix xx
> [inner-2309] when clickhouse is included, the lowercase of all instances must be 0 (cherry pick from #3775)

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
Reason:  
  BUG inner-2303
Type:  
  BUG
Influences：  
fix: not checking the version number of clickhouse and not synchronization variables to clickhouse
> [inner-2303] fix: not checking the version number of clickhouse and not synchronization variables to clickhouse

- src/main/java/com/actiontech/dble/config/helper/TestSchemasTaskForClickHouse.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2218] fill AP_NODE_LACK alarm

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/builder/HandlerBuilder.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/BaseSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/util/HandlerTool.java
- src/main/java/com/actiontech/dble/route/RouteResultsetNode.java
- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
- src/main/java/com/actiontech/dble/route/util/ConditionUtil.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
- src/main/java/com/actiontech/dble/server/handler/ExplainHandler.java
Reason:  
  BUG inner-2315
Type:  
  BUG
Influences：  
The fields returned in the clickhouse-mysql protocol do not contain information about database/table, etc.
> [inner-2315] fix: handle clickhouse incompatibilities

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeQueryHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParseShow.java
- src/main/java/com/actiontech/dble/statistic/trace/RwTraceResult.java
- src/main/java/com/actiontech/dble/statistic/trace/RwTrackProbe.java
- src/main/java/com/actiontech/dble/statistic/trace/TraceResult.java
- src/main/java/com/actiontech/dble/statistic/trace/TrackProbe.java
- src/test/java/com/actiontech/dble/parser/ManagerParserTest.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2313&2314&2267] fix some minor issues

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DefaultDruidParser.java
Reason:  
  BUG inner-2328
Type:  
  BUG  
Influences：  
SQL across clickhouse libraries is not supported
> [inner-2328] fix: SQL across clickhouse libraries is not supported

- src/main/java/com/actiontech/dble/config/DbleTempConfig.java
- src/main/java/com/actiontech/dble/config/ServerConfig.java
- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/server/variables/SystemVariables.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
Type:  
Influences：  
   1、fix:the lowercase on the mysql side changes, after 'reload @@config_all', the heartbeat of the dbInstance should be in the error state
2、Unified lowercase variables
> [inner-2318] the lowercase on the mysql side changes, after 'reload @@config_all', the heartbeat of the dbInstance should be in the error state

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:  
  BUG inner-2320
Type:  
  BUG
Influences：  
shardingTable can direct route only when the rules and nodes are the same 
globalTable nodes are the same, they can be direct route
> [inner-2320] fix: shardingTable can direct route only when the rules and nodes are the same

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
Reason:
  BUG inner-2320
Type:
  BUG
Influences：
The direct route can only be selected when the shardnodes of all tables in SQL have intersection
> [inner-2320] fix: The direct route can only be selected when the shardnodes of all tables in SQL have intersection

- src/main/java/com/actiontech/dble/statistic/sql/analyzer/UserStatAbstractAnalyzer.java
Reason:  
Type:  
Influences：  
   fix xx
> atomic processing

- src/main/java/com/actiontech/dble/route/parser/druid/impl/DruidSelectParser.java
- src/main/java/com/actiontech/dble/route/util/RouterUtil.java
Reason:  
  BUG inner-2320
Type:  
  BUG
Influences：  
remove the route of noSharding
> [inner-2320] fix: remove the route of noSharding

- src/main/java/com/actiontech/dble/config/converter/DBConverter.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner-2306
Type:  
  BUG
Influences：  
databaseType should not be empty
add flowHighLevel/flowLowLevel parameter value check
> [inner-2306] fix: databaseType should not be empty

- src/main/resources/sharding_detail.xsd
Reason:  
  BUG inner-2141
Type:  
  BUG
Influences：  
childTable adds specifyCharset configuration item
> [inner-2141] fix: childTable adds specifyCharset configuration item

- src/main/assembly/conf/log4j2.xml
- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/alarm/AlarmCode.java
- src/main/java/com/actiontech/dble/alarm/ToResolveContainer.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/main/java/com/actiontech/dble/singleton/ThreadChecker.java
- src/main/java/com/actiontech/dble/singleton/ThreadCheckerScheduler.java
- src/main/java/com/actiontech/dble/util/ExecutorUtil.java
- src/main/java/com/actiontech/dble/util/NameableExecutor.java
- src/main/resources/log4j2.xml
Reason:  
Type:  
Influences：  
   fix xx
> [inner-1918] Timer thread detection hang

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
  BUG inner-2330&2329
Type:  
  BUG
Influences：  
    release connection at once for hint in rw-transaction
fix hint in  rw-transaction
> inner-2330&2329: release connection at once for hint in rw-transaction

- src/main/java/com/actiontech/dble/backend/datasource/LocalReadLoadBalancer.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
- src/main/java/com/actiontech/dble/cluster/zkprocess/entity/dbGroups/DBInstance.java
- src/main/java/com/actiontech/dble/config/loader/xml/XMLDbLoader.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/config/model/db/DbInstanceConfig.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/singleton/SystemParams.java
- src/main/java/com/actiontech/dble/util/StringUtil.java
- src/main/resources/db.dtd
Reason:  
  Improve  inner-1752
Type:  
  Improve    
Influences：  
[inner-1752] feat: local read support inner 1752
#3296
> [inner-1752] feat: local read support inner 1752(cherry-pick)

- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
fix: replace Chinese commas
> [inner-1752] fix: replace Chinese commas

- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/statistic/sql/handler/SqlStatisticHandler.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2347] fix npe

- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2334&2336&2337] add memory and random a mysql contrast lowerCase logic

- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleDbInstance.java
Reason:  
  BUG inner-1787
Type:  
  BUG
Influences：  
fix: statement insertion errors
#3301
> [inner-1787] fix: statement insertion errors(cherry-pick)

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
- src/main/java/com/actiontech/dble/backend/heartbeat/MySQLHeartbeat.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeSelectHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/MultiNodeMergeAndOrderHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/OrderByHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/groupby/DirectGroupByHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/JoinHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/query/impl/join/NotInHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/xa/XaCheckHandler.java
- src/main/java/com/actiontech/dble/cluster/logic/AbstractClusterLogic.java
- src/main/java/com/actiontech/dble/meta/ProxyMetaManager.java
- src/main/java/com/actiontech/dble/route/parser/ManagerParse.java
- src/main/java/com/actiontech/dble/route/sequence/handler/DistributedSequenceHandler.java
- src/main/java/com/actiontech/dble/services/FrontendService.java
- src/main/java/com/actiontech/dble/services/manager/ManagerQueryHandler.java
- src/main/java/com/actiontech/dble/services/manager/dump/DumpFileHandler.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPool.java
- src/main/java/com/actiontech/dble/services/manager/information/tables/DbleThreadPoolTask.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowThreadPool.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowThreadPoolTask.java
- src/main/java/com/actiontech/dble/services/manager/response/ThreadHandler.java
- src/main/java/com/actiontech/dble/singleton/Scheduler.java
- src/main/java/com/actiontech/dble/singleton/ThreadChecker.java
- src/main/java/com/actiontech/dble/singleton/ThreadCheckerScheduler.java
- src/main/java/com/actiontech/dble/singleton/ThreadManager.java
- src/main/java/com/actiontech/dble/util/ExecutorUtil.java
- src/main/java/com/actiontech/dble/util/NameableScheduledThreadPoolExecutor.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2112] implement interrupt thread through interrupt()/shutdownNow()

- src/main/java/com/actiontech/dble/config/util/ConfigUtil.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2352] enhancing intelligent judgment of isAllDbInstancesChange()

- src/main/java/com/actiontech/dble/DbleServer.java
- src/main/java/com/actiontech/dble/services/manager/response/ShowHelp.java
- src/main/java/com/actiontech/dble/services/manager/response/ThreadHandler.java
- src/main/java/com/actiontech/dble/singleton/SerializableLock.java
- src/main/java/com/actiontech/dble/singleton/ThreadChecker.java
- src/main/java/com/actiontech/dble/singleton/ThreadManager.java
- src/main/java/com/actiontech/dble/util/ExecutorUtil.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2351] print thread stackTrace

- src/main/java/com/actiontech/dble/services/mysqlauthenticate/MySQLBackAuthService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLCurrentResponseService.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2350] need to deal with NPE in performance mode

- docker-images/dble-image/mgr/bootstrap.cnf
- docker-images/dble-image/quick-start/bootstrap.cnf
- docker-images/dble-image/rwSplit/bootstrap.cnf
- src/main/resources/bootstrap_template.cnf
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2353] adjust docker-image's cnf param

- src/main/java/com/actiontech/dble/net/connection/AbstractConnection.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/ShardingService.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2194] fix: questions and transactions occasional appear as 0

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/BaseDDLHandler.java
- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ddl/MultiNodeDdlPrepareHandler.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2368] fix: when some nodes have been closed during the ddl execution phase, the front side needs to respond with an error.

- src/main/java/com/actiontech/dble/config/helper/GetAndSyncDbInstanceKeyVariables.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2129] When getKeyVariables, npe occasionally appears in dble.log

- src/main/java/com/actiontech/dble/server/status/LoadDataBatch.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2190] collections adjusted to be thread-safe

- src/main/java/com/actiontech/dble/statistic/sql/StatisticRecord.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2251] fix: splitUser + enable statistics npe appears using python + ps protocol

- src/main/java/com/actiontech/dble/net/service/AbstractService.java
- src/main/java/com/actiontech/dble/net/service/ServiceTask.java
(cherry picked from commit 2b7c5cc536ee9b092eb51492eacc711ca0e7d20e)
Reason:  
Type:  
Influences：  
   fix xx
> inner-983&2184: fixed load data lost connection (#2545)

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2371] fix: sql execution hang problem caused by the inability to respond to the front side due to unprocessed packets (2).

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbGroup.java
- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
Type:  
Influences：  
   fix xx
> [inner-2377] Ensure the orderliness of stop/start operations of dbinstance

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix an error that occurred during commit during load data inner 2191

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/ConnectionHeartBeatHandler.java
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix xx
> fix npe when enable the testWhileIdle parameter

- src/main/java/com/actiontech/dble/plan/common/time/MyTime.java
pick from  https://github.com/actiontech/dble/pull/3786
> [inner-2311] fix: precision is missing when datetime/timestamp/time are converted to strings

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
Reason:  
Type:  
Influences：  
   fix xx
> fix npe inner 349

- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
(cherry picked from commit dcff228b4c13bf0fd9f7bb0d52f9c18aaba36b59、07c0c1f1c986a71fb74d0fcc0379965592c63b49)
Reason:  
  BUG similar：https://github.com/actiontech/dble/pull/3839、https://github.com/actiontech/dble/pull/3845
Type:  
Influences：  
   fix xx
> [inner-2371] fix: sql execution hang problem caused by the inability to respond to the front side due to unprocessed packets.

- src/main/java/com/actiontech/dble/backend/mysql/nio/handler/MultiNodeLoadDataHandler.java
Reason:  
Type:  
Influences：  
   fix xx
>  rollback fix npe inner 2191

- src/main/java/com/actiontech/dble/backend/mysql/ByteUtil.java
- src/main/java/com/actiontech/dble/net/handler/BackEndRecycleRunnable.java
- src/main/java/com/actiontech/dble/net/mysql/PreparedClosePacket.java
- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/BusinessService.java
- src/main/java/com/actiontech/dble/services/mysqlsharding/MySQLResponseService.java
- src/main/java/com/actiontech/dble/services/rwsplit/PSHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/PreparedStatementHolder.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitHandler.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitService.java
Reason:  
Type:  
Influences：  
   fix xx
> strength prepare statement protocol inner 1475

- src/main/java/com/actiontech/dble/cluster/ClusterLogic.java
- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/config/model/SystemConfig.java
- src/main/java/com/actiontech/dble/services/manager/handler/UpdateHandler.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadContext.java
- src/main/java/com/actiontech/dble/services/manager/response/UniqueDbInstance.java
Reason:  
  Improve  inner-2383: skip test other connection on some case
Type:  
  Improve
Influences：  
   update dbinstance
> inner-2383: skip test other connection on some case

- src/main/java/com/actiontech/dble/config/ConfigInitializer.java
- src/main/java/com/actiontech/dble/services/manager/response/ReloadConfig.java
Reason:  
Type:  
Influences：  
   fix xx
> inner-2383-supplement:fix ci

- src/main/java/com/actiontech/dble/statistic/trace/TraceResult.java
Reason:  
  BUG #3875
Type:  
Influences：  
   fix xx
> [inner-2390] fix: sqlSlowTime does not take effect

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG inner-2396:fix delayThreshold not work properly
Type:  
  BUG
Influences：  
   delay detect
> inner-2396:fix delayThreshold not work properly

- pom.xml
- src/main/java/com/actiontech/dble/cluster/impl/UcoreSender.java
- src/main/java/com/actiontech/dble/cluster/impl/ushard/UshardSender.java
Reason:  
   Bug inner-2389: update jar
Type:  
  Bug  
Influences：  
   fix BUG
> inner-2389: update jar

- pom.xml
Reason:  
  BUG inner-2389
Type:  
  BUG
Influences：  
   lib incompatible
> inner-2389: fix guava incompatible

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
Reason:  
  BUG  cherrypick: inner-2396:fix delayThreshold not work properly
Type:  
  BUG
Influences：  
  delay detect
> cherrypick: inner-2396:fix delayThreshold not work properly

- pom.xml
Reason:  
   Improve :move univocity-parsers config
Type:  
  Improve  
Influences：  
  
> move univocity-parsers config

- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
Reason:  
  Improve :upload metadata for  ha switch
Type:  
  Improve  
Influences：  
  
> inner-2407-supplement ： upload metadata for HA switch

- src/main/java/com/actiontech/dble/backend/datasource/PhysicalDatasource.java
Reason:  
  BUG 
Type:  
  BUG
> fix IdleHeartBeat inner 2399

- src/main/java/com/actiontech/dble/net/connection/BackendConnection.java
Reason:  
  BUG ssl supplyment:fix non encrypted can't connect
Type:  
  BUG
Influences：  
   fix xx
> ssl supplyment:fix non encrypted

- src/main/java/com/actiontech/dble/services/manager/response/ha/DbGroupHaSwitch.java
Reason:  
  BUG inner-2407-supplement
Type:  
  BUG  upload metadata for switch
Influences：  
   fix xx
> inner-2407-supplement ： upload metadata for switch

- src/main/java/com/actiontech/dble/rwsplit/RWSplitNonBlockingSession.java
- src/main/java/com/actiontech/dble/services/rwsplit/RWSplitQueryHandler.java
- src/main/java/com/actiontech/dble/singleton/RouteService.java
Reason:  
Type:  
Influences：  
   fix xx
> ATK-4339&ATK-4341 -supplement:fix hint doesn't work
